public class Control_Extend {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Control.Extend"); }
    };
    public static Object arrayExtend = FFI_STUB;
    public static Object arrayExtend(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Control.Extend.arrayExtend"); }

public static final Object extendFn = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (g_2) -> { return (java.util.function.Function<Object, Object>) (w_3) -> { return ((java.util.function.Function<Object, Object>) (f_1)).apply((java.util.function.Function<Object, Object>) (w_prime__4) -> { return ((java.util.function.Function<Object, Object>) (g_2)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictSemigroup_0).get("append"))).apply(w_3))).apply(w_prime__4)); }); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return Data_Functor.functorFn; }; return new __Record$46_75_6e_63_74_6f_72_30_O$65_78_74_65_6e_64_O(new String[]{"extend", "Functor0"}, __field1, __field0); } }).get(); };
public static final Object extendArray = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = Control_Extend.arrayExtend; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Functor.functorArray; }; return new __Record$46_75_6e_63_74_6f_72_30_O$65_78_74_65_6e_64_O(new String[]{"extend", "Functor0"}, __field1, __field0); } }).get();
public static final Object extend = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("extend"); };
public static final Object extendFlipped = (java.util.function.Function<Object, Object>) (dictExtend_0) -> { return (java.util.function.Function<Object, Object>) (w_1) -> { return (java.util.function.Function<Object, Object>) (f_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictExtend_0).get("extend"))).apply(f_2))).apply(w_1); }; }; };
public static final Object duplicate = (java.util.function.Function<Object, Object>) (dictExtend_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictExtend_0).get("extend"))).apply(((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn)); };
public static final Object composeCoKleisliFlipped = (java.util.function.Function<Object, Object>) (dictExtend_0) -> { return (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (g_2) -> { return (java.util.function.Function<Object, Object>) (w_3) -> { return ((java.util.function.Function<Object, Object>) (f_1)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictExtend_0).get("extend"))).apply(g_2))).apply(w_3)); }; }; }; };
public static final Object composeCoKleisli = (java.util.function.Function<Object, Object>) (dictExtend_0) -> { return (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (g_2) -> { return (java.util.function.Function<Object, Object>) (w_3) -> { return ((java.util.function.Function<Object, Object>) (g_2)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictExtend_0).get("extend"))).apply(f_1))).apply(w_3)); }; }; }; };
}
