public class Control_Applicative {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Control.Applicative"); }
    };


public static final Object pure = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("pure"); };
public static final Object unless = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ( ((Boolean) ((!(((Boolean) (v_1)))))) ? v1_2 : ( ((Boolean) (v_1)) ? ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_0).get("pure"))).apply(Data_Unit.unit) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }; };
public static final Object when = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ( ((Boolean) (v_1)) ? v1_2 : ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_0).get("pure"))).apply(Data_Unit.unit)); }; }; };
public static final Object liftA1 = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> { Object Apply0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_0).get("Apply0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_2) -> { return (java.util.function.Function<Object, Object>) (a_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Apply0_1).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_0).get("pure"))).apply(f_2)))).apply(a_3); }; }; };
public static final Object applicativeProxy = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return Type_Proxy.__singleton$Proxy.value; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Control_Apply.applyProxy; }; return new __Record$41_70_70_6c_79_30_O$70_75_72_65_O(new String[]{"pure", "Apply0"}, __field1, __field0); } }).get();
public static final Object applicativeFn = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return x_0; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Control_Apply.applyFn; }; return new __Record$41_70_70_6c_79_30_O$70_75_72_65_O(new String[]{"pure", "Apply0"}, __field1, __field0); } }).get();
public static final Object applicativeArray = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_0) -> { return new Object[]{x_0}; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Control_Apply.applyArray; }; return new __Record$41_70_70_6c_79_30_O$70_75_72_65_O(new String[]{"pure", "Apply0"}, __field1, __field0); } }).get();
}
