public class Control_Monad {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Control.Monad"); }
    };


public static final Object whenM = (java.util.function.Function<Object, Object>) (dictMonad_0) -> { Object Bind1_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonad_0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object Applicative0_2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (mb_3) -> { return (java.util.function.Function<Object, Object>) (m_4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bind1_1).get("bind"))).apply(mb_3))).apply((java.util.function.Function<Object, Object>) (b_5) -> { return ( ((Boolean) (b_5)) ? m_4 : ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Applicative0_2).get("pure"))).apply(Data_Unit.unit)); }); }; }; };
public static final Object unlessM = (java.util.function.Function<Object, Object>) (dictMonad_0) -> { Object Bind1_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonad_0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object Applicative0_2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (mb_3) -> { return (java.util.function.Function<Object, Object>) (m_4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bind1_1).get("bind"))).apply(mb_3))).apply((java.util.function.Function<Object, Object>) (b_5) -> { return ( ((Boolean) ((!(((Boolean) (b_5)))))) ? m_4 : ( ((Boolean) (b_5)) ? ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Applicative0_2).get("pure"))).apply(Data_Unit.unit) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }); }; }; };
public static final Object monadProxy = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Control_Applicative.applicativeProxy; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Control_Bind.bindProxy; }; return new __Record$41_70_70_6c_69_63_61_74_69_76_65_30_O$42_69_6e_64_31_O(new String[]{"Applicative0", "Bind1"}, __field0, __field1); } }).get();
public static final Object monadFn = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Control_Applicative.applicativeFn; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Control_Bind.bindFn; }; return new __Record$41_70_70_6c_69_63_61_74_69_76_65_30_O$42_69_6e_64_31_O(new String[]{"Applicative0", "Bind1"}, __field0, __field1); } }).get();
public static final Object monadArray = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Control_Applicative.applicativeArray; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Control_Bind.bindArray; }; return new __Record$41_70_70_6c_69_63_61_74_69_76_65_30_O$42_69_6e_64_31_O(new String[]{"Applicative0", "Bind1"}, __field0, __field1); } }).get();
public static final Object liftM1 = (java.util.function.Function<Object, Object>) (dictMonad_0) -> { Object Bind1_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonad_0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object Applicative0_2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_3) -> { return (java.util.function.Function<Object, Object>) (a_4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bind1_1).get("bind"))).apply(a_4))).apply((java.util.function.Function<Object, Object>) (a_prime__5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Applicative0_2).get("pure"))).apply(((java.util.function.Function<Object, Object>) (f_3)).apply(a_prime__5)); }); }; }; };
public static final Object ap = (java.util.function.Function<Object, Object>) (dictMonad_0) -> { Object Bind1_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonad_0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object Applicative0_2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_3) -> { return (java.util.function.Function<Object, Object>) (a_4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bind1_1).get("bind"))).apply(f_3))).apply((java.util.function.Function<Object, Object>) (f_prime__5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bind1_1).get("bind"))).apply(a_4))).apply((java.util.function.Function<Object, Object>) (a_prime__6) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Applicative0_2).get("pure"))).apply(((java.util.function.Function<Object, Object>) (f_prime__5)).apply(a_prime__6)); }); }); }; }; };
}
