public class Control_Biapply {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Control.Biapply"); }
    };


public static final Object biapplyTuple = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return new Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (((Data_Tuple.Tuple) (Object)(v_0)).value0)).apply(((Data_Tuple.Tuple) (Object)(v1_1)).value0), ((java.util.function.Function<Object, Object>) (((Data_Tuple.Tuple) (Object)(v_0)).value1)).apply(((Data_Tuple.Tuple) (Object)(v1_1)).value1)); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Bifunctor.bifunctorTuple; }; return new __Record$42_69_66_75_6e_63_74_6f_72_30_O$62_69_61_70_70_6c_79_O(new String[]{"biapply", "Bifunctor0"}, __field1, __field0); } }).get();
public static final Object biapply = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("biapply"); };
public static final Object biapplyFirst = (java.util.function.Function<Object, Object>) (dictBiapply_0) -> { Object Bifunctor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapply_0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (a_2) -> { return (java.util.function.Function<Object, Object>) (b_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapply_0).get("biapply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bifunctor0_1).get("bimap"))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_4 = ((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn); return (java.util.function.Function<Object, Object>) (v_5) -> { return __local_var_4; }; } }).get()))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_4 = ((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn); return (java.util.function.Function<Object, Object>) (v_5) -> { return __local_var_4; }; } }).get())))).apply(a_2)))).apply(b_3); }; }; };
public static final Object biapplySecond = (java.util.function.Function<Object, Object>) (dictBiapply_0) -> { Object Bifunctor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapply_0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (a_2) -> { return (java.util.function.Function<Object, Object>) (b_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapply_0).get("biapply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bifunctor0_1).get("bimap"))).apply(Data_Function.$const))).apply(Data_Function.$const)))).apply(a_2)))).apply(b_3); }; }; };
public static final Object bilift2 = (java.util.function.Function<Object, Object>) (dictBiapply_0) -> { Object Bifunctor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapply_0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_2) -> { return (java.util.function.Function<Object, Object>) (g_3) -> { return (java.util.function.Function<Object, Object>) (a_4) -> { return (java.util.function.Function<Object, Object>) (b_5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapply_0).get("biapply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bifunctor0_1).get("bimap"))).apply(f_2))).apply(g_3)))).apply(a_4)))).apply(b_5); }; }; }; }; };
public static final Object bilift3 = (java.util.function.Function<Object, Object>) (dictBiapply_0) -> { Object Bifunctor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapply_0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_2) -> { return (java.util.function.Function<Object, Object>) (g_3) -> { return (java.util.function.Function<Object, Object>) (a_4) -> { return (java.util.function.Function<Object, Object>) (b_5) -> { return (java.util.function.Function<Object, Object>) (c_6) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapply_0).get("biapply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapply_0).get("biapply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bifunctor0_1).get("bimap"))).apply(f_2))).apply(g_3)))).apply(a_4)))).apply(b_5)))).apply(c_6); }; }; }; }; }; };
}
