public class Control_Apply {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Control.Apply"); }
    };
    public static Object arrayApply = FFI_STUB;
    public static Object arrayApply(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Control.Apply.arrayApply"); }

public static final Object applyProxy = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return Type_Proxy.__singleton$Proxy.value; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Functor.functorProxy; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get();
public static final Object applyFn = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (g_1) -> { return (java.util.function.Function<Object, Object>) (x_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_0)).apply(x_2))).apply(((java.util.function.Function<Object, Object>) (g_1)).apply(x_2)); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Functor.functorFn; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get();
public static final Object applyArray = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = Control_Apply.arrayApply; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Functor.functorArray; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get();
public static final Object apply = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("apply"); };
public static final Object applyFirst = (java.util.function.Function<Object, Object>) (dictApply_0) -> { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (a_2) -> { return (java.util.function.Function<Object, Object>) (b_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1).get("map"))).apply(Data_Function.$const))).apply(a_2)))).apply(b_3); }; }; };
public static final Object applySecond = (java.util.function.Function<Object, Object>) (dictApply_0) -> { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (a_2) -> { return (java.util.function.Function<Object, Object>) (b_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1).get("map"))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_4 = ((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn); return (java.util.function.Function<Object, Object>) (v_5) -> { return __local_var_4; }; } }).get()))).apply(a_2)))).apply(b_3); }; }; };
public static final Object lift2 = (java.util.function.Function<Object, Object>) (dictApply_0) -> { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_2) -> { return (java.util.function.Function<Object, Object>) (a_3) -> { return (java.util.function.Function<Object, Object>) (b_4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1).get("map"))).apply(f_2))).apply(a_3)))).apply(b_4); }; }; }; };
public static final Object lift3 = (java.util.function.Function<Object, Object>) (dictApply_0) -> { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_2) -> { return (java.util.function.Function<Object, Object>) (a_3) -> { return (java.util.function.Function<Object, Object>) (b_4) -> { return (java.util.function.Function<Object, Object>) (c_5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1).get("map"))).apply(f_2))).apply(a_3)))).apply(b_4)))).apply(c_5); }; }; }; }; };
public static final Object lift4 = (java.util.function.Function<Object, Object>) (dictApply_0) -> { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_2) -> { return (java.util.function.Function<Object, Object>) (a_3) -> { return (java.util.function.Function<Object, Object>) (b_4) -> { return (java.util.function.Function<Object, Object>) (c_5) -> { return (java.util.function.Function<Object, Object>) (d_6) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1).get("map"))).apply(f_2))).apply(a_3)))).apply(b_4)))).apply(c_5)))).apply(d_6); }; }; }; }; }; };
public static final Object lift5 = (java.util.function.Function<Object, Object>) (dictApply_0) -> { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_2) -> { return (java.util.function.Function<Object, Object>) (a_3) -> { return (java.util.function.Function<Object, Object>) (b_4) -> { return (java.util.function.Function<Object, Object>) (c_5) -> { return (java.util.function.Function<Object, Object>) (d_6) -> { return (java.util.function.Function<Object, Object>) (e_7) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1).get("map"))).apply(f_2))).apply(a_3)))).apply(b_4)))).apply(c_5)))).apply(d_6)))).apply(e_7); }; }; }; }; }; }; };
}
