public class Control_Bind {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Control.Bind"); }
    };
    // FFI provided by ../javapurs-prelude/src/Control/Bind.java
    public static Object arrayBind = (java.util.function.Function<Object, Object>) (arrObj) -> (java.util.function.Function<Object, Object>) (f) -> {
        Object[] arr = (Object[]) arrObj;
        java.util.List<Object> result = new java.util.ArrayList<>();
        for (Object item : arr) {
            Object[] mapped = (Object[]) ((java.util.function.Function<Object, Object>) f).apply(item);
            for (Object mappedItem : mapped) {
                result.add(mappedItem);
            }
        }
        return result.toArray(new Object[0]);
    };


public static final Object discard = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("discard"); };
public static final Object bindProxy = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return Type_Proxy.__singleton$Proxy.value; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Control_Apply.applyProxy; }; return new __Record$41_70_70_6c_79_30_O$62_69_6e_64_O(new String[]{"bind", "Apply0"}, __field1, __field0); } }).get();
public static final Object bindFn = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (m_0) -> { return (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (x_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_1)).apply(((java.util.function.Function<Object, Object>) (m_0)).apply(x_2)))).apply(x_2); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Control_Apply.applyFn; }; return new __Record$41_70_70_6c_79_30_O$62_69_6e_64_O(new String[]{"bind", "Apply0"}, __field1, __field0); } }).get();
public static final Object bindArray = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = Control_Bind.arrayBind; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Control_Apply.applyArray; }; return new __Record$41_70_70_6c_79_30_O$62_69_6e_64_O(new String[]{"bind", "Apply0"}, __field1, __field0); } }).get();
public static final Object bind = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("bind"); };
public static final Object bindFlipped = (java.util.function.Function<Object, Object>) (dictBind_0) -> { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (Control_Bind.bind)).apply(dictBind_0); return (java.util.function.Function<Object, Object>) (b_2) -> { return (java.util.function.Function<Object, Object>) (a_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_1)).apply(a_3))).apply(b_2); }; }; };
public static final Object composeKleisliFlipped = (java.util.function.Function<Object, Object>) (dictBind_0) -> { return (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (g_2) -> { return (java.util.function.Function<Object, Object>) (a_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Bind.bind)).apply(dictBind_0))).apply(((java.util.function.Function<Object, Object>) (g_2)).apply(a_3)))).apply(f_1); }; }; }; };
public static final Object composeKleisli = (java.util.function.Function<Object, Object>) (dictBind_0) -> { return (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (g_2) -> { return (java.util.function.Function<Object, Object>) (a_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBind_0).get("bind"))).apply(((java.util.function.Function<Object, Object>) (f_1)).apply(a_3)))).apply(g_2); }; }; }; };
public static final Object discardProxy = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictBind_0) -> { return ((java.util.function.Function<Object, Object>) (Control_Bind.bind)).apply(dictBind_0); }; return new __Record$64_69_73_63_61_72_64_O(new String[]{"discard"}, __field0); } }).get();
public static final Object discardUnit = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictBind_0) -> { return ((java.util.function.Function<Object, Object>) (Control_Bind.bind)).apply(dictBind_0); }; return new __Record$64_69_73_63_61_72_64_O(new String[]{"discard"}, __field0); } }).get();
public static final Object ifM = (java.util.function.Function<Object, Object>) (dictBind_0) -> { return (java.util.function.Function<Object, Object>) (cond_1) -> { return (java.util.function.Function<Object, Object>) (t_2) -> { return (java.util.function.Function<Object, Object>) (f_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBind_0).get("bind"))).apply(cond_1))).apply((java.util.function.Function<Object, Object>) (cond_prime__4) -> { return ( ((Boolean) (cond_prime__4)) ? t_2 : f_3); }); }; }; }; };
public static final Object join = (java.util.function.Function<Object, Object>) (dictBind_0) -> { return (java.util.function.Function<Object, Object>) (m_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBind_0).get("bind"))).apply(m_1))).apply(((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn)); }; };
}
