public class Data_Profunctor {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Profunctor"); }
    };


public static final Object profunctorFn = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (a2b_0) -> { return (java.util.function.Function<Object, Object>) (c2d_1) -> { return (java.util.function.Function<Object, Object>) (b2c_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.composeFlipped)).apply(Control_Semigroupoid.semigroupoidFn))).apply(a2b_0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.composeFlipped)).apply(Control_Semigroupoid.semigroupoidFn))).apply(b2c_2))).apply(c2d_1)); }; }; }; return new __Record$64_69_6d_61_70_O(new String[]{"dimap"}, __field0); } }).get();
public static final Object dimap = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("dimap"); };
public static final Object lcmap = (java.util.function.Function<Object, Object>) (dictProfunctor_0) -> { return (java.util.function.Function<Object, Object>) (a2b_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictProfunctor_0).get("dimap"))).apply(a2b_1))).apply(((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn)); }; };
public static final Object rmap = (java.util.function.Function<Object, Object>) (dictProfunctor_0) -> { return (java.util.function.Function<Object, Object>) (b2c_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictProfunctor_0).get("dimap"))).apply(((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn)))).apply(b2c_1); }; };
public static final Object unwrapIso = (java.util.function.Function<Object, Object>) (dictProfunctor_0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictProfunctor_0).get("dimap"))).apply(((java.util.function.Function<Object, Object>) (Data_Newtype.wrap)).apply(null /* TODO: PrimUndefined */)))).apply(((java.util.function.Function<Object, Object>) (Data_Newtype.unwrap)).apply(null /* TODO: PrimUndefined */)); }; };
public static final Object wrapIso = (java.util.function.Function<Object, Object>) (dictProfunctor_0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictProfunctor_0).get("dimap"))).apply(((java.util.function.Function<Object, Object>) (Data_Newtype.unwrap)).apply(null /* TODO: PrimUndefined */)))).apply(((java.util.function.Function<Object, Object>) (Data_Newtype.wrap)).apply(null /* TODO: PrimUndefined */)); }; }; };
public static final Object arr = (java.util.function.Function<Object, Object>) (dictCategory_0) -> { Object identity2_1 = ((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(dictCategory_0); return (java.util.function.Function<Object, Object>) (dictProfunctor_2) -> { return (java.util.function.Function<Object, Object>) (f_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictProfunctor_2).get("dimap"))).apply(((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn)))).apply(f_3))).apply(identity2_1); }; }; };
}
