public class Data_CommutativeRing {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.CommutativeRing"); }
    };


public static final Object commutativeRingUnit = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Ring.ringUnit; }; return new __Record$52_69_6e_67_30_O(new String[]{"Ring0"}, __field0); } }).get();
public static final Object commutativeRingRecordNil = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Ring.ringRecordNil; }; return new __Record$52_69_6e_67_52_65_63_6f_72_64_30_O(new String[]{"RingRecord0"}, __field0); } }).get();
public static final Object commutativeRingRecordCons = (java.util.function.Function<Object, Object>) (dictIsSymbol_0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return (java.util.function.Function<Object, Object>) (dictCommutativeRingRecord_2) -> { Object ringRecordCons1_3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ring.ringRecordCons)).apply(dictIsSymbol_0))).apply(null /* TODO: PrimUndefined */))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictCommutativeRingRecord_2).get("RingRecord0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictCommutativeRing_4) -> { Object ringRecordCons2_5 = ((java.util.function.Function<Object, Object>) (ringRecordCons1_3)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictCommutativeRing_4).get("Ring0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_6) -> { return ringRecordCons2_5; }; return new __Record$52_69_6e_67_52_65_63_6f_72_64_30_O(new String[]{"RingRecord0"}, __field0); } }).get(); }; }; }; };
public static final Object commutativeRingRecord = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return (java.util.function.Function<Object, Object>) (dictCommutativeRingRecord_1) -> { Object ringRecord1_2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ring.ringRecord)).apply(null /* TODO: PrimUndefined */))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictCommutativeRingRecord_1).get("RingRecord0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> { return ringRecord1_2; }; return new __Record$52_69_6e_67_30_O(new String[]{"Ring0"}, __field0); } }).get(); }; };
public static final Object commutativeRingProxy = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Ring.ringProxy; }; return new __Record$52_69_6e_67_30_O(new String[]{"Ring0"}, __field0); } }).get();
public static final Object commutativeRingNumber = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Ring.ringNumber; }; return new __Record$52_69_6e_67_30_O(new String[]{"Ring0"}, __field0); } }).get();
public static final Object commutativeRingInt = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Ring.ringInt; }; return new __Record$52_69_6e_67_30_O(new String[]{"Ring0"}, __field0); } }).get();
public static final Object commutativeRingFn = (java.util.function.Function<Object, Object>) (dictCommutativeRing_0) -> { Object ringFn_1 = ((java.util.function.Function<Object, Object>) (Data_Ring.ringFn)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictCommutativeRing_0).get("Ring0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return ringFn_1; }; return new __Record$52_69_6e_67_30_O(new String[]{"Ring0"}, __field0); } }).get(); };
}
