public class Data_Unfoldable1 {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Unfoldable1"); }
    };
    public static Object unfoldr1ArrayImpl = FFI_STUB;
    public static Object unfoldr1ArrayImpl(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Unfoldable1.unfoldr1ArrayImpl"); }

public static final Object unfoldr1 = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("unfoldr1"); };
public static final Object unfoldable1Maybe = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (b_1) -> { return new Data_Maybe.Just(((Data_Tuple.Tuple) (Object)(((java.util.function.Function<Object, Object>) (f_0)).apply(b_1))).value0); }; }; return new __Record$75_6e_66_6f_6c_64_72_31_O(new String[]{"unfoldr1"}, __field0); } }).get();
public static final Object unfoldable1Array = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Unfoldable1.unfoldr1ArrayImpl)).apply(Data_Maybe.isNothing))).apply((java.util.function.Function<Object, Object>) (v_0) -> { return ( ((Boolean) ((v_0 instanceof Data_Maybe.Just))) ? ((Data_Maybe.Just) (Object)(v_0)).value0 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()); }))).apply(Data_Tuple.fst))).apply(Data_Tuple.snd); return new __Record$75_6e_66_6f_6c_64_72_31_O(new String[]{"unfoldr1"}, __field0); } }).get();
public static final Object replicate1 = (java.util.function.Function<Object, Object>) (dictUnfoldable1_0) -> { return (java.util.function.Function<Object, Object>) (n_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictUnfoldable1_0).get("unfoldr1"))).apply((java.util.function.Function<Object, Object>) (i_3) -> { return ( ((Boolean) ((((int) (i_3)) <= ((int) (0))))) ? new Data_Tuple.Tuple(v_2, Data_Maybe.__singleton$Nothing.value) : new Data_Tuple.Tuple(v_2, new Data_Maybe.Just((((int) (i_3)) - ((int) (1)))))); }))).apply((((int) (n_1)) - ((int) (1)))); }; }; };
public static final Object replicate1A = (java.util.function.Function<Object, Object>) (dictApply_0) -> { return (java.util.function.Function<Object, Object>) (dictUnfoldable1_1) -> { return (java.util.function.Function<Object, Object>) (dictTraversable1_2) -> { return (java.util.function.Function<Object, Object>) (n_3) -> { return (java.util.function.Function<Object, Object>) (m_4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictTraversable1_2).get("sequence1"))).apply(dictApply_0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictUnfoldable1_1).get("unfoldr1"))).apply((java.util.function.Function<Object, Object>) (i_5) -> { return ( ((Boolean) ((((int) (i_5)) <= ((int) (0))))) ? new Data_Tuple.Tuple(m_4, Data_Maybe.__singleton$Nothing.value) : new Data_Tuple.Tuple(m_4, new Data_Maybe.Just((((int) (i_5)) - ((int) (1)))))); }))).apply((((int) (n_3)) - ((int) (1))))); }; }; }; }; };
public static final Object singleton = (java.util.function.Function<Object, Object>) (dictUnfoldable1_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictUnfoldable1_0).get("unfoldr1"))).apply((java.util.function.Function<Object, Object>) (i_2) -> { return ( ((Boolean) ((((int) (i_2)) <= ((int) (0))))) ? new Data_Tuple.Tuple(v_1, Data_Maybe.__singleton$Nothing.value) : new Data_Tuple.Tuple(v_1, new Data_Maybe.Just((((int) (i_2)) - ((int) (1)))))); }))).apply(0); }; };
public static final Object range = (java.util.function.Function<Object, Object>) (dictUnfoldable1_0) -> { return (java.util.function.Function<Object, Object>) (start_1) -> { return (java.util.function.Function<Object, Object>) (end_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictUnfoldable1_0).get("unfoldr1"))).apply((new java.util.function.Supplier<Object>() { public Object get() { int __local_var_3 = ((int) (( ((Boolean) ((((int) (end_2)) >= ((int) (start_1))))) ? 1 : -1))); return (java.util.function.Function<Object, Object>) (i_4) -> { int i_prime__5 = ((int) ((((int) (i_4)) + ((int) (__local_var_3))))); return new Data_Tuple.Tuple(i_4, ( ((Boolean) ((((int) (i_4)) == ((int) (end_2))))) ? Data_Maybe.__singleton$Nothing.value : new Data_Maybe.Just(i_prime__5))); }; } }).get()))).apply(start_1); }; }; };
public static final Object iterateN = (java.util.function.Function<Object, Object>) (dictUnfoldable1_0) -> { return (java.util.function.Function<Object, Object>) (n_1) -> { return (java.util.function.Function<Object, Object>) (f_2) -> { return (java.util.function.Function<Object, Object>) (s_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictUnfoldable1_0).get("unfoldr1"))).apply((java.util.function.Function<Object, Object>) (v_4) -> { return new Data_Tuple.Tuple(((Data_Tuple.Tuple) (Object)(v_4)).value0, ( ((Boolean) ((((int) (((Data_Tuple.Tuple) (Object)(v_4)).value1)) > ((int) (0))))) ? new Data_Maybe.Just(new Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (f_2)).apply(((Data_Tuple.Tuple) (Object)(v_4)).value0), (((int) (((Data_Tuple.Tuple) (Object)(v_4)).value1)) - ((int) (1))))) : Data_Maybe.__singleton$Nothing.value)); }))).apply(new Data_Tuple.Tuple(s_3, (((int) (n_1)) - ((int) (1))))); }; }; }; };
}
