public class Data_Functor_Coproduct_Inject {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Functor.Coproduct.Inject"); }
    };


public static final Object prj = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("prj"); };
public static final Object injectReflexive = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn); final Object __field1 = Data_Maybe.Just; return new __Record$69_6e_6a_O$70_72_6a_O(new String[]{"inj", "prj"}, __field0, __field1); } }).get();
public static final Object injectLeft = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(Data_Functor_Coproduct.Coproduct))).apply(Data_Either.Left); final Object __field1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Functor_Coproduct.coproduct)).apply(Data_Maybe.Just))).apply((java.util.function.Function<Object, Object>) (v_0) -> { return Data_Maybe.__singleton$Nothing.value; }); return new __Record$69_6e_6a_O$70_72_6a_O(new String[]{"inj", "prj"}, __field0, __field1); } }).get();
public static final Object inj = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("inj"); };
public static final Object injectRight = (java.util.function.Function<Object, Object>) (dictInject_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(Data_Functor_Coproduct.Coproduct))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(Data_Either.Right))).apply(((java.util.function.Function<Object, Object>) (Data_Functor_Coproduct_Inject.inj)).apply(dictInject_0))); final Object __field1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Functor_Coproduct.coproduct)).apply((java.util.function.Function<Object, Object>) (v_1) -> { return Data_Maybe.__singleton$Nothing.value; }))).apply(((java.util.function.Function<Object, Object>) (Data_Functor_Coproduct_Inject.prj)).apply(dictInject_0)); return new __Record$69_6e_6a_O$70_72_6a_O(new String[]{"inj", "prj"}, __field0, __field1); } }).get(); };
}
