public class Data_Ring {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Ring"); }
    };
    // FFI provided by ../javapurs-prelude/src/Data/Ring.java
    public static Object intSub = (java.util.function.Function<Object, Object>) (x) -> (java.util.function.Function<Object, Object>) (y) -> (Integer) x - (Integer) y;
    public static Object numSub = (java.util.function.Function<Object, Object>) (x) -> (java.util.function.Function<Object, Object>) (y) -> (Double) x - (Double) y;


public static final Object subRecord = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("subRecord"); };
public static final Object sub = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("sub"); };
public static final Object ringUnit = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return Data_Unit.unit; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Semiring.semiringUnit; }; return new __Record$53_65_6d_69_72_69_6e_67_30_O$73_75_62_O(new String[]{"sub", "Semiring0"}, __field1, __field0); } }).get();
public static final Object ringRecordNil = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return (java.util.function.Function<Object, Object>) (v2_2) -> { return (new java.util.function.Supplier<Object>() { public Object get() { return new __Record$(new String[]{}); } }).get(); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Semiring.semiringRecordNil; }; return new __Record$53_65_6d_69_72_69_6e_67_52_65_63_6f_72_64_30_O$73_75_62_52_65_63_6f_72_64_O(new String[]{"subRecord", "SemiringRecord0"}, __field1, __field0); } }).get();
public static final Object ringRecordCons = (java.util.function.Function<Object, Object>) (dictIsSymbol_0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return (java.util.function.Function<Object, Object>) (dictRingRecord_2) -> { Object semiringRecordCons1_3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Semiring.semiringRecordCons)).apply(dictIsSymbol_0))).apply(null /* TODO: PrimUndefined */))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRingRecord_2).get("SemiringRecord0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictRing_4) -> { Object semiringRecordCons2_5 = ((java.util.function.Function<Object, Object>) (semiringRecordCons1_3)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_4).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_6) -> { return (java.util.function.Function<Object, Object>) (ra_7) -> { return (java.util.function.Function<Object, Object>) (rb_8) -> { Object key_9 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictIsSymbol_0).get("reflectSymbol"))).apply(Type_Proxy.__singleton$Proxy.value); Object get_10 = ((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeGet)).apply(key_9); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeSet)).apply(key_9))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_4).get("sub"))).apply(((java.util.function.Function<Object, Object>) (get_10)).apply(ra_7)))).apply(((java.util.function.Function<Object, Object>) (get_10)).apply(rb_8))))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRingRecord_2).get("subRecord"))).apply(Type_Proxy.__singleton$Proxy.value))).apply(ra_7))).apply(rb_8)); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_6) -> { return semiringRecordCons2_5; }; return new __Record$53_65_6d_69_72_69_6e_67_52_65_63_6f_72_64_30_O$73_75_62_52_65_63_6f_72_64_O(new String[]{"subRecord", "SemiringRecord0"}, __field1, __field0); } }).get(); }; }; }; };
public static final Object ringRecord = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return (java.util.function.Function<Object, Object>) (dictRingRecord_1) -> { Object semiringRecord1_2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Semiring.semiringRecord)).apply(null /* TODO: PrimUndefined */))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRingRecord_1).get("SemiringRecord0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRingRecord_1).get("subRecord"))).apply(Type_Proxy.__singleton$Proxy.value); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> { return semiringRecord1_2; }; return new __Record$53_65_6d_69_72_69_6e_67_30_O$73_75_62_O(new String[]{"sub", "Semiring0"}, __field1, __field0); } }).get(); }; };
public static final Object ringProxy = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return Type_Proxy.__singleton$Proxy.value; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Semiring.semiringProxy; }; return new __Record$53_65_6d_69_72_69_6e_67_30_O$73_75_62_O(new String[]{"sub", "Semiring0"}, __field1, __field0); } }).get();
public static final Object ringNumber = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = Data_Ring.numSub; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Semiring.semiringNumber; }; return new __Record$53_65_6d_69_72_69_6e_67_30_O$73_75_62_O(new String[]{"sub", "Semiring0"}, __field1, __field0); } }).get();
public static final Object ringInt = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = Data_Ring.intSub; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Semiring.semiringInt; }; return new __Record$53_65_6d_69_72_69_6e_67_30_O$73_75_62_O(new String[]{"sub", "Semiring0"}, __field1, __field0); } }).get();
public static final Object ringFn = (java.util.function.Function<Object, Object>) (dictRing_0) -> { Object semiringFn_1 = ((java.util.function.Function<Object, Object>) (Data_Semiring.semiringFn)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_0).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_2) -> { return (java.util.function.Function<Object, Object>) (g_3) -> { return (java.util.function.Function<Object, Object>) (x_4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_0).get("sub"))).apply(((java.util.function.Function<Object, Object>) (f_2)).apply(x_4)))).apply(((java.util.function.Function<Object, Object>) (g_3)).apply(x_4)); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return semiringFn_1; }; return new __Record$53_65_6d_69_72_69_6e_67_30_O$73_75_62_O(new String[]{"sub", "Semiring0"}, __field1, __field0); } }).get(); };
public static final Object negate = (java.util.function.Function<Object, Object>) (dictRing_0) -> { Object Semiring0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_0).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (a_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_0).get("sub"))).apply(((java.util.Map<String, Object>) Semiring0_1).get("zero")))).apply(a_2); }; };
}
