public class Data_Eq_Generic {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Eq.Generic"); }
    };


public static final Object genericEqNoConstructors = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return true; }; }; return new __Record$67_65_6e_65_72_69_63_45_71_27_O(new String[]{"genericEq'"}, __field0); } }).get();
public static final Object genericEqNoArguments = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return true; }; }; return new __Record$67_65_6e_65_72_69_63_45_71_27_O(new String[]{"genericEq'"}, __field0); } }).get();
public static final Object genericEqArgument = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEq_0).get("eq"))).apply(v_1))).apply(v1_2); }; }; return new __Record$67_65_6e_65_72_69_63_45_71_27_O(new String[]{"genericEq'"}, __field0); } }).get(); };
public static final Object genericEqprime = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("genericEq'"); };
public static final Object genericEqConstructor = (java.util.function.Function<Object, Object>) (dictGenericEq_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericEq_0).get("genericEq'"))).apply(v_1))).apply(v1_2); }; }; return new __Record$67_65_6e_65_72_69_63_45_71_27_O(new String[]{"genericEq'"}, __field0); } }).get(); };
public static final Object genericEqProduct = (java.util.function.Function<Object, Object>) (dictGenericEq_0) -> { return (java.util.function.Function<Object, Object>) (dictGenericEq1_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { return (((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericEq_0).get("genericEq'"))).apply(((Data_Generic_Rep.Product) (Object)(v_2)).value0))).apply(((Data_Generic_Rep.Product) (Object)(v1_3)).value0))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericEq1_1).get("genericEq'"))).apply(((Data_Generic_Rep.Product) (Object)(v_2)).value1))).apply(((Data_Generic_Rep.Product) (Object)(v1_3)).value1)))); }; }; return new __Record$67_65_6e_65_72_69_63_45_71_27_O(new String[]{"genericEq'"}, __field0); } }).get(); }; };
public static final Object genericEqSum = (java.util.function.Function<Object, Object>) (dictGenericEq_0) -> { return (java.util.function.Function<Object, Object>) (dictGenericEq1_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { return ( ((Boolean) ((v_2 instanceof Data_Generic_Rep.Inl))) ? (((Boolean) ((v1_3 instanceof Data_Generic_Rep.Inl))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericEq_0).get("genericEq'"))).apply(((Data_Generic_Rep.Inl) (Object)(v_2)).value0))).apply(((Data_Generic_Rep.Inl) (Object)(v1_3)).value0)))) : (((Boolean) ((v_2 instanceof Data_Generic_Rep.Inr))) && ((Boolean) ((((Boolean) ((v1_3 instanceof Data_Generic_Rep.Inr))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericEq1_1).get("genericEq'"))).apply(((Data_Generic_Rep.Inr) (Object)(v_2)).value0))).apply(((Data_Generic_Rep.Inr) (Object)(v1_3)).value0)))))))); }; }; return new __Record$67_65_6e_65_72_69_63_45_71_27_O(new String[]{"genericEq'"}, __field0); } }).get(); }; };
public static final Object genericEq = (java.util.function.Function<Object, Object>) (dictGeneric_0) -> { return (java.util.function.Function<Object, Object>) (dictGenericEq_1) -> { return (java.util.function.Function<Object, Object>) (x_2) -> { return (java.util.function.Function<Object, Object>) (y_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericEq_1).get("genericEq'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0).get("from"))).apply(x_2)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0).get("from"))).apply(y_3)); }; }; }; };
}
