public class Data_Distributive {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Distributive"); }
    };


public static final Object distributiveIdentity = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(Data_Identity.Identity))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0).get("map"))).apply(((java.util.function.Function<Object, Object>) (Data_Newtype.unwrap)).apply(null /* TODO: PrimUndefined */))); }; final Object __field1 = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> { return (java.util.function.Function<Object, Object>) (f_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(Data_Identity.Identity))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0).get("map"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (Data_Newtype.unwrap)).apply(null /* TODO: PrimUndefined */)))).apply(f_1))); }; }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Identity.functorIdentity; }; return new __Record$46_75_6e_63_74_6f_72_30_O$63_6f_6c_6c_65_63_74_O$64_69_73_74_72_69_62_75_74_65_O(new String[]{"distribute", "collect", "Functor0"}, __field2, __field1, __field0); } }).get();
public static final Object distribute = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("distribute"); };
private static Object __lazy_value_distributiveFunction;
private static int __lazy_state_distributiveFunction;
private static Object __lazy_get_distributiveFunction() { if (__lazy_state_distributiveFunction == 2) return __lazy_value_distributiveFunction; if (__lazy_state_distributiveFunction == 1) throw new IllegalStateException("Recursive initialization of distributiveFunction"); __lazy_state_distributiveFunction = 1; __lazy_value_distributiveFunction = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> { return (java.util.function.Function<Object, Object>) (a_1) -> { return (java.util.function.Function<Object, Object>) (e_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0).get("map"))).apply((java.util.function.Function<Object, Object>) (v_3) -> { return ((java.util.function.Function<Object, Object>) (v_3)).apply(e_2); }))).apply(a_1); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> { return (java.util.function.Function<Object, Object>) (f_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Distributive.distribute)).apply(Data_Distributive.__lazy_get_distributiveFunction()))).apply(dictFunctor_0)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0).get("map"))).apply(f_1)); }; }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Functor.functorFn; }; return new __Record$46_75_6e_63_74_6f_72_30_O$63_6f_6c_6c_65_63_74_O$64_69_73_74_72_69_62_75_74_65_O(new String[]{"distribute", "collect", "Functor0"}, __field2, __field1, __field0); } }).get(); __lazy_state_distributiveFunction = 2; return __lazy_value_distributiveFunction; }
public static final Object distributiveFunction = __lazy_get_distributiveFunction();
public static final Object cotraverse = (java.util.function.Function<Object, Object>) (dictDistributive_0) -> { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictDistributive_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); Object distribute1_2 = ((java.util.function.Function<Object, Object>) (Data_Distributive.distribute)).apply(dictDistributive_0); return (java.util.function.Function<Object, Object>) (dictFunctor_3) -> { Object distribute2_4 = ((java.util.function.Function<Object, Object>) (distribute1_2)).apply(dictFunctor_3); return (java.util.function.Function<Object, Object>) (f_5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1).get("map"))).apply(f_5)))).apply(distribute2_4); }; }; };
public static final Object collectDefault = (java.util.function.Function<Object, Object>) (dictDistributive_0) -> { Object distribute1_1 = ((java.util.function.Function<Object, Object>) (Data_Distributive.distribute)).apply(dictDistributive_0); return (java.util.function.Function<Object, Object>) (dictFunctor_2) -> { Object distribute2_3 = ((java.util.function.Function<Object, Object>) (distribute1_1)).apply(dictFunctor_2); return (java.util.function.Function<Object, Object>) (f_4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(distribute2_3))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_2).get("map"))).apply(f_4)); }; }; };
private static Object __lazy_value_distributiveTuple;
private static int __lazy_state_distributiveTuple;
private static Object __lazy_get_distributiveTuple() { if (__lazy_state_distributiveTuple == 2) return __lazy_value_distributiveTuple; if (__lazy_state_distributiveTuple == 1) throw new IllegalStateException("Recursive initialization of distributiveTuple"); __lazy_state_distributiveTuple = 1; __lazy_value_distributiveTuple = (java.util.function.Function<Object, Object>) (dictTypeEquals_0) -> { return Data_Distributive.__direct$5(dictTypeEquals_0); }; __lazy_state_distributiveTuple = 2; return __lazy_value_distributiveTuple; }
public static final Object distributiveTuple = __lazy_get_distributiveTuple();
private static Object __direct$5(Object dictTypeEquals_0) { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictFunctor_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Distributive.collectDefault)).apply(Data_Distributive.__direct$5(dictTypeEquals_0)))).apply(dictFunctor_1); }; final Object __field1 = (java.util.function.Function<Object, Object>) (dictFunctor_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (Data_Tuple.Tuple)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Type_Equality.proof)).apply(dictTypeEquals_0))).apply((java.util.function.Function<Object, Object>) (a_2) -> { return a_2; }))).apply(Data_Unit.unit))))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_1).get("map"))).apply(Data_Tuple.snd)); }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return Data_Tuple.functorTuple; }; return new __Record$46_75_6e_63_74_6f_72_30_O$63_6f_6c_6c_65_63_74_O$64_69_73_74_72_69_62_75_74_65_O(new String[]{"collect", "distribute", "Functor0"}, __field2, __field0, __field1); } }).get(); }
public static final Object collect = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("collect"); };
public static final Object distributeDefault = (java.util.function.Function<Object, Object>) (dictDistributive_0) -> { return (java.util.function.Function<Object, Object>) (dictFunctor_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictDistributive_0).get("collect"))).apply(dictFunctor_1))).apply(((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn)); }; };
}
