public class Data_Monoid_Conj {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Monoid.Conj"); }
    };


public static final Object Conj = (java.util.function.Function<Object, Object>) (x_0) -> { return x_0; };
public static final Object showConj = (java.util.function.Function<Object, Object>) (dictShow_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (((String) ((((String) ("(Conj ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); };
public static final Object semiringConj = (java.util.function.Function<Object, Object>) (dictHeytingAlgebra_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.Map<String, Object>) dictHeytingAlgebra_0).get("tt"); final Object __field1 = ((java.util.Map<String, Object>) dictHeytingAlgebra_0).get("ff"); final Object __field2 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictHeytingAlgebra_0).get("conj"))).apply(v_1))).apply(v1_2); }; }; final Object __field3 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictHeytingAlgebra_0).get("disj"))).apply(v_1))).apply(v1_2); }; }; return new __Record$61_64_64_O$6d_75_6c_O$6f_6e_65_O$7a_65_72_6f_O(new String[]{"zero", "one", "add", "mul"}, __field2, __field3, __field1, __field0); } }).get(); };
public static final Object semigroupConj = (java.util.function.Function<Object, Object>) (dictHeytingAlgebra_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictHeytingAlgebra_0).get("conj"))).apply(v_1))).apply(v1_2); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get(); };
public static final Object ordConj = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return dictOrd_0; };
public static final Object monoidConj = (java.util.function.Function<Object, Object>) (dictHeytingAlgebra_0) -> { Object semigroupConj1_1 = ((java.util.function.Function<Object, Object>) (Data_Monoid_Conj.semigroupConj)).apply(dictHeytingAlgebra_0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.Map<String, Object>) dictHeytingAlgebra_0).get("tt"); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return semigroupConj1_1; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get(); };
public static final Object functorConj = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (m_1) -> { return ((java.util.function.Function<Object, Object>) (f_0)).apply(m_1); }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get();
public static final Object eqConj = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return dictEq_0; };
public static final Object eq1Conj = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return ((java.util.function.Function<Object, Object>) (Data_Eq.eq)).apply(dictEq_0); }; return new __Record$65_71_31_O(new String[]{"eq1"}, __field0); } }).get();
public static final Object ord1Conj = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return ((java.util.function.Function<Object, Object>) (Data_Ord.compare)).apply(dictOrd_0); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Monoid_Conj.eq1Conj; }; return new __Record$45_71_31_30_O$63_6f_6d_70_61_72_65_31_O(new String[]{"compare1", "Eq10"}, __field1, __field0); } }).get();
public static final Object boundedConj = (java.util.function.Function<Object, Object>) (dictBounded_0) -> { return dictBounded_0; };
public static final Object applyConj = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return ((java.util.function.Function<Object, Object>) (v_0)).apply(v1_1); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Monoid_Conj.functorConj; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get();
public static final Object bindConj = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (f_1) -> { return ((java.util.function.Function<Object, Object>) (f_1)).apply(v_0); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Monoid_Conj.applyConj; }; return new __Record$41_70_70_6c_79_30_O$62_69_6e_64_O(new String[]{"bind", "Apply0"}, __field1, __field0); } }).get();
public static final Object applicativeConj = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = Data_Monoid_Conj.Conj; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Monoid_Conj.applyConj; }; return new __Record$41_70_70_6c_79_30_O$70_75_72_65_O(new String[]{"pure", "Apply0"}, __field1, __field0); } }).get();
public static final Object monadConj = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Monoid_Conj.applicativeConj; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Monoid_Conj.bindConj; }; return new __Record$41_70_70_6c_69_63_61_74_69_76_65_30_O$42_69_6e_64_31_O(new String[]{"Applicative0", "Bind1"}, __field0, __field1); } }).get();
}
