public class Data_Divisible {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Divisible"); }
    };


public static final Object divisiblePredicate = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return true; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Divide.dividePredicate; }; return new __Record$44_69_76_69_64_65_30_O$63_6f_6e_71_75_65_72_O(new String[]{"conquer", "Divide0"}, __field1, __field0); } }).get();
public static final Object divisibleOp = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> { Object divideOp_1 = ((java.util.function.Function<Object, Object>) (Data_Divide.divideOp)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_2 = ((java.util.Map<String, Object>) dictMonoid_0).get("mempty"); return (java.util.function.Function<Object, Object>) (v_3) -> { return __local_var_2; }; } }).get(); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return divideOp_1; }; return new __Record$44_69_76_69_64_65_30_O$63_6f_6e_71_75_65_72_O(new String[]{"conquer", "Divide0"}, __field1, __field0); } }).get(); };
public static final Object divisibleEquivalence = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return true; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Divide.divideEquivalence; }; return new __Record$44_69_76_69_64_65_30_O$63_6f_6e_71_75_65_72_O(new String[]{"conquer", "Divide0"}, __field1, __field0); } }).get();
public static final Object divisibleComparison = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return Data_Ordering.__singleton$EQ.value; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Divide.divideComparison; }; return new __Record$44_69_76_69_64_65_30_O$63_6f_6e_71_75_65_72_O(new String[]{"conquer", "Divide0"}, __field1, __field0); } }).get();
public static final Object conquer = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("conquer"); };
}
