public class Data_BooleanAlgebra {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.BooleanAlgebra"); }
    };


public static final Object booleanAlgebraUnit = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_HeytingAlgebra.heytingAlgebraUnit; }; return new __Record$48_65_79_74_69_6e_67_41_6c_67_65_62_72_61_30_O(new String[]{"HeytingAlgebra0"}, __field0); } }).get();
public static final Object booleanAlgebraRecordNil = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_HeytingAlgebra.heytingAlgebraRecordNil; }; return new __Record$48_65_79_74_69_6e_67_41_6c_67_65_62_72_61_52_65_63_6f_72_64_30_O(new String[]{"HeytingAlgebraRecord0"}, __field0); } }).get();
public static final Object booleanAlgebraRecordCons = (java.util.function.Function<Object, Object>) (dictIsSymbol_0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return (java.util.function.Function<Object, Object>) (dictBooleanAlgebraRecord_2) -> { Object heytingAlgebraRecordCons1_3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_HeytingAlgebra.heytingAlgebraRecordCons)).apply(dictIsSymbol_0))).apply(null /* TODO: PrimUndefined */))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBooleanAlgebraRecord_2).get("HeytingAlgebraRecord0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictBooleanAlgebra_4) -> { Object heytingAlgebraRecordCons2_5 = ((java.util.function.Function<Object, Object>) (heytingAlgebraRecordCons1_3)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBooleanAlgebra_4).get("HeytingAlgebra0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_6) -> { return heytingAlgebraRecordCons2_5; }; return new __Record$48_65_79_74_69_6e_67_41_6c_67_65_62_72_61_52_65_63_6f_72_64_30_O(new String[]{"HeytingAlgebraRecord0"}, __field0); } }).get(); }; }; }; };
public static final Object booleanAlgebraRecord = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return (java.util.function.Function<Object, Object>) (dictBooleanAlgebraRecord_1) -> { Object heytingAlgebraRecord1_2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_HeytingAlgebra.heytingAlgebraRecord)).apply(null /* TODO: PrimUndefined */))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBooleanAlgebraRecord_1).get("HeytingAlgebraRecord0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> { return heytingAlgebraRecord1_2; }; return new __Record$48_65_79_74_69_6e_67_41_6c_67_65_62_72_61_30_O(new String[]{"HeytingAlgebra0"}, __field0); } }).get(); }; };
public static final Object booleanAlgebraProxy = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_HeytingAlgebra.heytingAlgebraProxy; }; return new __Record$48_65_79_74_69_6e_67_41_6c_67_65_62_72_61_30_O(new String[]{"HeytingAlgebra0"}, __field0); } }).get();
public static final Object booleanAlgebraFn = (java.util.function.Function<Object, Object>) (dictBooleanAlgebra_0) -> { Object heytingAlgebraFunction_1 = ((java.util.function.Function<Object, Object>) (Data_HeytingAlgebra.heytingAlgebraFunction)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBooleanAlgebra_0).get("HeytingAlgebra0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return heytingAlgebraFunction_1; }; return new __Record$48_65_79_74_69_6e_67_41_6c_67_65_62_72_61_30_O(new String[]{"HeytingAlgebra0"}, __field0); } }).get(); };
public static final Object booleanAlgebraBoolean = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_HeytingAlgebra.heytingAlgebraBoolean; }; return new __Record$48_65_79_74_69_6e_67_41_6c_67_65_62_72_61_30_O(new String[]{"HeytingAlgebra0"}, __field0); } }).get();
}
