public class Data_Functor_Clown {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Functor.Clown"); }
    };


public static final Object Clown = (java.util.function.Function<Object, Object>) (x_0) -> { return x_0; };
public static final Object showClown = (java.util.function.Function<Object, Object>) (dictShow_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (((String) ((((String) ("(Clown ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); };
public static final Object profunctorClown = (java.util.function.Function<Object, Object>) (dictContravariant_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictContravariant_0).get("cmap"))).apply(f_1))).apply(v1_3); }; }; }; return new __Record$64_69_6d_61_70_O(new String[]{"dimap"}, __field0); } }).get(); };
public static final Object ordClown = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return dictOrd_0; };
public static final Object newtypeClown = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object hoistClown = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return ((java.util.function.Function<Object, Object>) (f_0)).apply(v_1); }; };
public static final Object functorClown = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return v1_1; }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get();
public static final Object eqClown = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return dictEq_0; };
public static final Object bifunctorClown = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0).get("map"))).apply(f_1))).apply(v1_3); }; }; }; return new __Record$62_69_6d_61_70_O(new String[]{"bimap"}, __field0); } }).get(); };
public static final Object biapplyClown = (java.util.function.Function<Object, Object>) (dictApply_0) -> { Object bifunctorClown1_1 = ((java.util.function.Function<Object, Object>) (Data_Functor_Clown.bifunctorClown)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("apply"))).apply(v_2))).apply(v1_3); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return bifunctorClown1_1; }; return new __Record$42_69_66_75_6e_63_74_6f_72_30_O$62_69_61_70_70_6c_79_O(new String[]{"biapply", "Bifunctor0"}, __field1, __field0); } }).get(); };
public static final Object biapplicativeClown = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> { Object biapplyClown1_1 = ((java.util.function.Function<Object, Object>) (Data_Functor_Clown.biapplyClown)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_0).get("Apply0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (a_2) -> { return (java.util.function.Function<Object, Object>) (v_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_0).get("pure"))).apply(a_2); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return biapplyClown1_1; }; return new __Record$42_69_61_70_70_6c_79_30_O$62_69_70_75_72_65_O(new String[]{"bipure", "Biapply0"}, __field1, __field0); } }).get(); };
}
