public class Data_Ring_Generic {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Ring.Generic"); }
    };


public static final Object genericSubprime = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("genericSub'"); };
public static final Object genericSub = (java.util.function.Function<Object, Object>) (dictGeneric_0) -> { Object to_1 = ((java.util.function.Function<Object, Object>) (Data_Generic_Rep.to)).apply(dictGeneric_0); return (java.util.function.Function<Object, Object>) (dictGenericRing_2) -> { return (java.util.function.Function<Object, Object>) (x_3) -> { return (java.util.function.Function<Object, Object>) (y_4) -> { return ((java.util.function.Function<Object, Object>) (to_1)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericRing_2).get("genericSub'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0).get("from"))).apply(x_3)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0).get("from"))).apply(y_4))); }; }; }; };
public static final Object genericRingProduct = (java.util.function.Function<Object, Object>) (dictGenericRing_0) -> { return (java.util.function.Function<Object, Object>) (dictGenericRing1_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { return new Data_Generic_Rep.Product(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericRing_0).get("genericSub'"))).apply(((Data_Generic_Rep.Product) (Object)(v_2)).value0))).apply(((Data_Generic_Rep.Product) (Object)(v1_3)).value0), ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericRing1_1).get("genericSub'"))).apply(((Data_Generic_Rep.Product) (Object)(v_2)).value1))).apply(((Data_Generic_Rep.Product) (Object)(v1_3)).value1)); }; }; return new __Record$67_65_6e_65_72_69_63_53_75_62_27_O(new String[]{"genericSub'"}, __field0); } }).get(); }; };
public static final Object genericRingNoArguments = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return Data_Generic_Rep.__singleton$NoArguments.value; }; }; return new __Record$67_65_6e_65_72_69_63_53_75_62_27_O(new String[]{"genericSub'"}, __field0); } }).get();
public static final Object genericRingConstructor = (java.util.function.Function<Object, Object>) (dictGenericRing_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericRing_0).get("genericSub'"))).apply(v_1))).apply(v1_2); }; }; return new __Record$67_65_6e_65_72_69_63_53_75_62_27_O(new String[]{"genericSub'"}, __field0); } }).get(); };
public static final Object genericRingArgument = (java.util.function.Function<Object, Object>) (dictRing_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_0).get("sub"))).apply(v_1))).apply(v1_2); }; }; return new __Record$67_65_6e_65_72_69_63_53_75_62_27_O(new String[]{"genericSub'"}, __field0); } }).get(); };
}
