public class Data_Profunctor_Split {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Profunctor.Split"); }
    };


public static final class SplitF {
            public final Object value0;
            public final Object value1;
            public final Object value2;
            public SplitF(Object value0, Object value1, Object value2) {
                this.value0 = value0;
                this.value1 = value1;
                this.value2 = value2;
            }
        }
public static final Object SplitF = (java.util.function.Function<Object, Object>) (value0) -> (java.util.function.Function<Object, Object>) (value1) -> (java.util.function.Function<Object, Object>) (value2) -> { return new Data_Profunctor_Split.SplitF(value0, value1, value2); };
public static final Object unSplit = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_0)).apply(((Data_Profunctor_Split.SplitF) (Object)(v_1)).value0))).apply(((Data_Profunctor_Split.SplitF) (Object)(v_1)).value1))).apply(((Data_Profunctor_Split.SplitF) (Object)(v_1)).value2); }; };
public static final Object split = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (g_1) -> { return (java.util.function.Function<Object, Object>) (fx_2) -> { return new Data_Profunctor_Split.SplitF(f_0, g_1, fx_2); }; }; };
public static final Object profunctorSplit = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (g_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (h_3) -> { return (java.util.function.Function<Object, Object>) (i_4) -> { Object __local_var_5 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(h_3))).apply(f_0); Object __local_var_6 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(g_1))).apply(i_4); return (java.util.function.Function<Object, Object>) (fx_7) -> { return new Data_Profunctor_Split.SplitF(__local_var_5, __local_var_6, fx_7); }; }; })).apply(((Data_Profunctor_Split.SplitF) (Object)(v_2)).value0))).apply(((Data_Profunctor_Split.SplitF) (Object)(v_2)).value1))).apply(((Data_Profunctor_Split.SplitF) (Object)(v_2)).value2); }; }; }; return new __Record$64_69_6d_61_70_O(new String[]{"dimap"}, __field0); } }).get();
public static final Object lowerSplit = (java.util.function.Function<Object, Object>) (dictInvariant_0) -> { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (Data_Functor_Invariant.imap)).apply(dictInvariant_0); return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (b_3) -> { return (java.util.function.Function<Object, Object>) (a_4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_1)).apply(a_4))).apply(b_3); }; })).apply(((Data_Profunctor_Split.SplitF) (Object)(v_2)).value0))).apply(((Data_Profunctor_Split.SplitF) (Object)(v_2)).value1))).apply(((Data_Profunctor_Split.SplitF) (Object)(v_2)).value2); }; };
public static final Object liftSplit = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_0 = ((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn); Object __local_var_1 = ((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn); return (java.util.function.Function<Object, Object>) (fx_2) -> { return new Data_Profunctor_Split.SplitF(__local_var_0, __local_var_1, fx_2); }; } }).get();
public static final Object hoistSplit = (java.util.function.Function<Object, Object>) (nat_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (f_2) -> { return (java.util.function.Function<Object, Object>) (g_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply((java.util.function.Function<Object, Object>) (fx_4) -> { return new Data_Profunctor_Split.SplitF(f_2, g_3, fx_4); }))).apply(nat_0); }; })).apply(((Data_Profunctor_Split.SplitF) (Object)(v_1)).value0))).apply(((Data_Profunctor_Split.SplitF) (Object)(v_1)).value1))).apply(((Data_Profunctor_Split.SplitF) (Object)(v_1)).value2); }; };
public static final Object functorSplit = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (g_2) -> { return (java.util.function.Function<Object, Object>) (h_3) -> { return (java.util.function.Function<Object, Object>) (fx_4) -> { return new Data_Profunctor_Split.SplitF(g_2, ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(f_0))).apply(h_3), fx_4); }; }; })).apply(((Data_Profunctor_Split.SplitF) (Object)(v_1)).value0))).apply(((Data_Profunctor_Split.SplitF) (Object)(v_1)).value1))).apply(((Data_Profunctor_Split.SplitF) (Object)(v_1)).value2); }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get();
}
