public class Data_Array_NonEmpty_Internal {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Array.NonEmpty.Internal"); }
    };
    public static Object foldl1Impl = FFI_STUB;
    public static Object foldl1Impl(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Array.NonEmpty.Internal.foldl1Impl"); }
    public static Object foldr1Impl = FFI_STUB;
    public static Object foldr1Impl(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Array.NonEmpty.Internal.foldr1Impl"); }
    public static Object traverse1Impl = FFI_STUB;
    public static Object traverse1Impl(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Array.NonEmpty.Internal.traverse1Impl"); }

public static final Object NonEmptyArray = (java.util.function.Function<Object, Object>) (x_0) -> { return x_0; };
public static final Object unfoldable1NonEmptyArray = Data_Unfoldable1.unfoldable1Array;
public static final Object traversableWithIndexNonEmptyArray = Data_TraversableWithIndex.traversableWithIndexArray;
public static final Object traversableNonEmptyArray = Data_Traversable.traversableArray;
public static final Object showNonEmptyArray = (java.util.function.Function<Object, Object>) (dictShow_0) -> { Object showArray_1 = ((java.util.function.Function<Object, Object>) (Data_Show.showArray)).apply(dictShow_0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return (((String) ((((String) ("(NonEmptyArray ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) showArray_1).get("show"))).apply(v_2)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); };
public static final Object semigroupNonEmptyArray = Data_Semigroup.semigroupArray;
public static final Object ordNonEmptyArray = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return ((java.util.function.Function<Object, Object>) (Data_Ord.ordArray)).apply(dictOrd_0); };
public static final Object ord1NonEmptyArray = Data_Ord.ord1Array;
public static final Object monadNonEmptyArray = Control_Monad.monadArray;
public static final Object functorWithIndexNonEmptyArray = Data_FunctorWithIndex.functorWithIndexArray;
public static final Object functorNonEmptyArray = Data_Functor.functorArray;
public static final Object foldableWithIndexNonEmptyArray = Data_FoldableWithIndex.foldableWithIndexArray;
public static final Object foldableNonEmptyArray = Data_Foldable.foldableArray;
private static Object __lazy_value_foldable1NonEmptyArray;
private static int __lazy_state_foldable1NonEmptyArray;
private static Object __lazy_get_foldable1NonEmptyArray() { if (__lazy_state_foldable1NonEmptyArray == 2) return __lazy_value_foldable1NonEmptyArray; if (__lazy_state_foldable1NonEmptyArray == 1) throw new IllegalStateException("Recursive initialization of foldable1NonEmptyArray"); __lazy_state_foldable1NonEmptyArray = 1; __lazy_value_foldable1NonEmptyArray = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Semigroup_Foldable.foldMap1DefaultL)).apply(Data_Array_NonEmpty_Internal.__lazy_get_foldable1NonEmptyArray()))).apply(Data_Functor.functorArray))).apply(dictSemigroup_0); }; final Object __field1 = (java.util.function.Function<Object, Object>) (__local_var_0) -> { return (java.util.function.Function<Object, Object>) (__local_var_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Array_NonEmpty_Internal.foldr1Impl)).apply(__local_var_0))).apply(__local_var_1); }; }; final Object __field2 = (java.util.function.Function<Object, Object>) (__local_var_0) -> { return (java.util.function.Function<Object, Object>) (__local_var_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Array_NonEmpty_Internal.foldl1Impl)).apply(__local_var_0))).apply(__local_var_1); }; }; final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Foldable.foldableArray; }; return new __Record$46_6f_6c_64_61_62_6c_65_30_O$66_6f_6c_64_4d_61_70_31_O$66_6f_6c_64_6c_31_O$66_6f_6c_64_72_31_O(new String[]{"foldMap1", "foldr1", "foldl1", "Foldable0"}, __field3, __field0, __field2, __field1); } }).get(); __lazy_state_foldable1NonEmptyArray = 2; return __lazy_value_foldable1NonEmptyArray; }
public static final Object foldable1NonEmptyArray = __lazy_get_foldable1NonEmptyArray();
private static Object __lazy_value_traversable1NonEmptyArray;
private static int __lazy_state_traversable1NonEmptyArray;
private static Object __lazy_get_traversable1NonEmptyArray() { if (__lazy_state_traversable1NonEmptyArray == 2) return __lazy_value_traversable1NonEmptyArray; if (__lazy_state_traversable1NonEmptyArray == 1) throw new IllegalStateException("Recursive initialization of traversable1NonEmptyArray"); __lazy_state_traversable1NonEmptyArray = 1; __lazy_value_traversable1NonEmptyArray = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictApply_0) -> { Object apply_1 = ((java.util.function.Function<Object, Object>) (Control_Apply.apply)).apply(dictApply_0); Object go__map_2 = ((java.util.function.Function<Object, Object>) (Data_Functor.map)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (f_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Array_NonEmpty_Internal.traverse1Impl)).apply(apply_1))).apply(go__map_2))).apply(f_3); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (dictApply_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Semigroup_Traversable.sequence1Default)).apply(Data_Array_NonEmpty_Internal.__lazy_get_traversable1NonEmptyArray()))).apply(dictApply_0); }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Array_NonEmpty_Internal.foldable1NonEmptyArray; }; final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Traversable.traversableArray; }; return new __Record$46_6f_6c_64_61_62_6c_65_31_30_O$54_72_61_76_65_72_73_61_62_6c_65_31_O$73_65_71_75_65_6e_63_65_31_O$74_72_61_76_65_72_73_65_31_O(new String[]{"traverse1", "sequence1", "Foldable10", "Traversable1"}, __field2, __field3, __field1, __field0); } }).get(); __lazy_state_traversable1NonEmptyArray = 2; return __lazy_value_traversable1NonEmptyArray; }
public static final Object traversable1NonEmptyArray = __lazy_get_traversable1NonEmptyArray();
public static final Object eqNonEmptyArray = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return ((java.util.function.Function<Object, Object>) (Data_Eq.eqArray)).apply(dictEq_0); };
public static final Object eq1NonEmptyArray = Data_Eq.eq1Array;
public static final Object bindNonEmptyArray = Control_Bind.bindArray;
public static final Object applyNonEmptyArray = Control_Apply.applyArray;
public static final Object applicativeNonEmptyArray = Control_Applicative.applicativeArray;
public static final Object altNonEmptyArray = Control_Alt.altArray;
}
