public class Data_EuclideanRing {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.EuclideanRing"); }
    };
    // FFI provided by ../javapurs-prelude/src/Data/EuclideanRing.java
    public static Object intDegree = (java.util.function.Function<Object, Object>) (x) -> Math.abs((Integer) x);
    public static Object intDiv = (java.util.function.Function<Object, Object>) (x) -> (java.util.function.Function<Object, Object>) (y) -> {
        int xInt = (Integer) x;
        int yInt = (Integer) y;
        if (yInt == 0) return 0;
        if (yInt > 0) return (int) Math.floor((double) xInt / yInt);
        return -(int) Math.floor((double) xInt / -yInt);
    };
    public static Object intMod = (java.util.function.Function<Object, Object>) (x) -> (java.util.function.Function<Object, Object>) (y) -> {
        int xInt = (Integer) x;
        int yInt = (Integer) y;
        if (yInt == 0) return 0;
        int yy = Math.abs(yInt);
        return ((xInt % yy) + yy) % yy;
    };
    public static Object numDiv = (java.util.function.Function<Object, Object>) (x) -> (java.util.function.Function<Object, Object>) (y) -> (Double) x / (Double) y;


public static final Object mod = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("mod"); };
private static Object __lazy_value_gcd;
private static int __lazy_state_gcd;
private static Object __lazy_get_gcd() { if (__lazy_state_gcd == 2) return __lazy_value_gcd; if (__lazy_state_gcd == 1) throw new IllegalStateException("Recursive initialization of gcd"); __lazy_state_gcd = 1; __lazy_value_gcd = (java.util.function.Function<Object, Object>) (dictEq_0) -> (java.util.function.Function<Object, Object>) (dictEuclideanRing_1) -> { return Data_EuclideanRing.__direct$1(dictEq_0, dictEuclideanRing_1); }; __lazy_state_gcd = 2; return __lazy_value_gcd; }
public static final Object gcd = __lazy_get_gcd();
private static Object __direct$1(Object dictEq_0, Object dictEuclideanRing_1) { Object zero_2 = ((java.util.function.Function<Object, Object>) (Data_Semiring.zero)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEuclideanRing_1).get("CommutativeRing0"))).apply(null /* TODO: PrimUndefined */)).get("Ring0"))).apply(null /* TODO: PrimUndefined */)).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (a_3) -> { return (java.util.function.Function<Object, Object>) (b_4) -> { return ( ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEq_0).get("eq"))).apply(b_4))).apply(zero_2))) ? a_3 : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_EuclideanRing.__direct$1(dictEq_0, dictEuclideanRing_1))).apply(b_4))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEuclideanRing_1).get("mod"))).apply(a_3))).apply(b_4))); }; }; }
public static final Object euclideanRingNumber = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return 1; }; final Object __field1 = Data_EuclideanRing.numDiv; final Object __field2 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return 0.0; }; }; final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_CommutativeRing.commutativeRingNumber; }; return new __Record$43_6f_6d_6d_75_74_61_74_69_76_65_52_69_6e_67_30_O$64_65_67_72_65_65_O$64_69_76_O$6d_6f_64_O(new String[]{"degree", "div", "mod", "CommutativeRing0"}, __field3, __field0, __field1, __field2); } }).get();
public static final Object euclideanRingInt = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = Data_EuclideanRing.intDegree; final Object __field1 = Data_EuclideanRing.intDiv; final Object __field2 = Data_EuclideanRing.intMod; final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_CommutativeRing.commutativeRingInt; }; return new __Record$43_6f_6d_6d_75_74_61_74_69_76_65_52_69_6e_67_30_O$64_65_67_72_65_65_O$64_69_76_O$6d_6f_64_O(new String[]{"degree", "div", "mod", "CommutativeRing0"}, __field3, __field0, __field1, __field2); } }).get();
public static final Object div = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("div"); };
public static final Object lcm = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return (java.util.function.Function<Object, Object>) (dictEuclideanRing_1) -> { Object Ring0_2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEuclideanRing_1).get("CommutativeRing0"))).apply(null /* TODO: PrimUndefined */)).get("Ring0"))).apply(null /* TODO: PrimUndefined */); Object zero_3 = ((java.util.function.Function<Object, Object>) (Data_Semiring.zero)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Ring0_2).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)); Object Semiring0_4 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Ring0_2).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (a_5) -> { return (java.util.function.Function<Object, Object>) (b_6) -> { return ( ((Boolean) ((((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEq_0).get("eq"))).apply(a_5))).apply(zero_3))) || ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEq_0).get("eq"))).apply(b_6))).apply(zero_3)))))) ? zero_3 : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEuclideanRing_1).get("div"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Semiring0_4).get("mul"))).apply(a_5))).apply(b_6)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (( ((Boolean) ((Data_EuclideanRing.gcd == null))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_EuclideanRing.gcd)).apply(dictEq_0))).apply(dictEuclideanRing_1) : Data_EuclideanRing.__direct$1(dictEq_0, dictEuclideanRing_1)))).apply(a_5))).apply(b_6))); }; }; }; };
public static final Object degree = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("degree"); };
}
