public class Data_Semigroup_Traversable {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Semigroup.Traversable"); }
    };


public static final Object traverse1 = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("traverse1"); };
public static final Object traversableTuple = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictApply_0) -> { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_2) -> { return (java.util.function.Function<Object, Object>) (v_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1).get("map"))).apply(((java.util.function.Function<Object, Object>) (Data_Tuple.Tuple)).apply(((Data_Tuple.Tuple) (Object)(v_3)).value0)))).apply(((java.util.function.Function<Object, Object>) (f_2)).apply(((Data_Tuple.Tuple) (Object)(v_3)).value1)); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (dictApply_0) -> { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1).get("map"))).apply(((java.util.function.Function<Object, Object>) (Data_Tuple.Tuple)).apply(((Data_Tuple.Tuple) (Object)(v_2)).value0)))).apply(((Data_Tuple.Tuple) (Object)(v_2)).value1); }; }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Semigroup_Foldable.foldableTuple; }; final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Traversable.traversableTuple; }; return new __Record$46_6f_6c_64_61_62_6c_65_31_30_O$54_72_61_76_65_72_73_61_62_6c_65_31_O$73_65_71_75_65_6e_63_65_31_O$74_72_61_76_65_72_73_65_31_O(new String[]{"traverse1", "sequence1", "Foldable10", "Traversable1"}, __field2, __field3, __field1, __field0); } }).get();
public static final Object traversableIdentity = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictApply_0) -> { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_2) -> { return (java.util.function.Function<Object, Object>) (v_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1).get("map"))).apply(Data_Identity.Identity))).apply(((java.util.function.Function<Object, Object>) (f_2)).apply(v_3)); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (dictApply_0) -> { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1).get("map"))).apply(Data_Identity.Identity))).apply(v_2); }; }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Semigroup_Foldable.foldableIdentity; }; final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Traversable.traversableIdentity; }; return new __Record$46_6f_6c_64_61_62_6c_65_31_30_O$54_72_61_76_65_72_73_61_62_6c_65_31_O$73_65_71_75_65_6e_63_65_31_O$74_72_61_76_65_72_73_65_31_O(new String[]{"traverse1", "sequence1", "Foldable10", "Traversable1"}, __field2, __field3, __field1, __field0); } }).get();
public static final Object sequence1Default = (java.util.function.Function<Object, Object>) (dictTraversable1_0) -> { return (java.util.function.Function<Object, Object>) (dictApply_1) -> { return Data_Semigroup_Traversable.__direct$3(dictTraversable1_0, dictApply_1); }; };
private static Object __direct$3(Object dictTraversable1_0, Object dictApply_1) { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictTraversable1_0).get("traverse1"))).apply(dictApply_1))).apply(((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn)); }
private static Object __lazy_value_traversableDual;
private static int __lazy_state_traversableDual;
private static Object __lazy_get_traversableDual() { if (__lazy_state_traversableDual == 2) return __lazy_value_traversableDual; if (__lazy_state_traversableDual == 1) throw new IllegalStateException("Recursive initialization of traversableDual"); __lazy_state_traversableDual = 1; __lazy_value_traversableDual = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictApply_0) -> { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_2) -> { return (java.util.function.Function<Object, Object>) (v_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1).get("map"))).apply(Data_Monoid_Dual.Dual))).apply(((java.util.function.Function<Object, Object>) (f_2)).apply(v_3)); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (dictApply_0) -> { return ( ((Boolean) ((Data_Semigroup_Traversable.sequence1Default == null))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Semigroup_Traversable.sequence1Default)).apply(Data_Semigroup_Traversable.__lazy_get_traversableDual()))).apply(dictApply_0) : Data_Semigroup_Traversable.__direct$3(Data_Semigroup_Traversable.__lazy_get_traversableDual(), dictApply_0)); }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Semigroup_Foldable.foldableDual; }; final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Traversable.traversableDual; }; return new __Record$46_6f_6c_64_61_62_6c_65_31_30_O$54_72_61_76_65_72_73_61_62_6c_65_31_O$73_65_71_75_65_6e_63_65_31_O$74_72_61_76_65_72_73_65_31_O(new String[]{"traverse1", "sequence1", "Foldable10", "Traversable1"}, __field2, __field3, __field1, __field0); } }).get(); __lazy_state_traversableDual = 2; return __lazy_value_traversableDual; }
public static final Object traversableDual = __lazy_get_traversableDual();
private static Object __lazy_value_traversableMultiplicative;
private static int __lazy_state_traversableMultiplicative;
private static Object __lazy_get_traversableMultiplicative() { if (__lazy_state_traversableMultiplicative == 2) return __lazy_value_traversableMultiplicative; if (__lazy_state_traversableMultiplicative == 1) throw new IllegalStateException("Recursive initialization of traversableMultiplicative"); __lazy_state_traversableMultiplicative = 1; __lazy_value_traversableMultiplicative = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictApply_0) -> { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_2) -> { return (java.util.function.Function<Object, Object>) (v_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1).get("map"))).apply(Data_Monoid_Multiplicative.Multiplicative))).apply(((java.util.function.Function<Object, Object>) (f_2)).apply(v_3)); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (dictApply_0) -> { return ( ((Boolean) ((Data_Semigroup_Traversable.sequence1Default == null))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Semigroup_Traversable.sequence1Default)).apply(Data_Semigroup_Traversable.__lazy_get_traversableMultiplicative()))).apply(dictApply_0) : Data_Semigroup_Traversable.__direct$3(Data_Semigroup_Traversable.__lazy_get_traversableMultiplicative(), dictApply_0)); }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Semigroup_Foldable.foldableMultiplicative; }; final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Traversable.traversableMultiplicative; }; return new __Record$46_6f_6c_64_61_62_6c_65_31_30_O$54_72_61_76_65_72_73_61_62_6c_65_31_O$73_65_71_75_65_6e_63_65_31_O$74_72_61_76_65_72_73_65_31_O(new String[]{"traverse1", "sequence1", "Foldable10", "Traversable1"}, __field2, __field3, __field1, __field0); } }).get(); __lazy_state_traversableMultiplicative = 2; return __lazy_value_traversableMultiplicative; }
public static final Object traversableMultiplicative = __lazy_get_traversableMultiplicative();
public static final Object sequence1 = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("sequence1"); };
public static final Object traverse1Default = (java.util.function.Function<Object, Object>) (dictTraversable1_0) -> { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictTraversable1_0).get("Traversable1"))).apply(null /* TODO: PrimUndefined */)).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (dictApply_2) -> { return (java.util.function.Function<Object, Object>) (f_3) -> { return (java.util.function.Function<Object, Object>) (ta_4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictTraversable1_0).get("sequence1"))).apply(dictApply_2))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1).get("map"))).apply(f_3))).apply(ta_4)); }; }; }; };
}
