public class Data_Either_Inject {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Either.Inject"); }
    };


public static final Object prj = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("prj"); };
public static final Object injectReflexive = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn); final Object __field1 = Data_Maybe.Just; return new __Record$69_6e_6a_O$70_72_6a_O(new String[]{"inj", "prj"}, __field0, __field1); } }).get();
public static final Object injectLeft = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = Data_Either.Left; final Object __field1 = (java.util.function.Function<Object, Object>) (v2_0) -> { return ( ((Boolean) ((v2_0 instanceof Data_Either.Left))) ? new Data_Maybe.Just(((Data_Either.Left) (Object)(v2_0)).value0) : ( ((Boolean) ((v2_0 instanceof Data_Either.Right))) ? Data_Maybe.__singleton$Nothing.value : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; return new __Record$69_6e_6a_O$70_72_6a_O(new String[]{"inj", "prj"}, __field0, __field1); } }).get();
public static final Object inj = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("inj"); };
public static final Object injectRight = (java.util.function.Function<Object, Object>) (dictInject_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(Data_Either.Right))).apply(((java.util.function.Function<Object, Object>) (Data_Either_Inject.inj)).apply(dictInject_0)); final Object __field1 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (Data_Either_Inject.prj)).apply(dictInject_0); return (java.util.function.Function<Object, Object>) (v2_2) -> { return ( ((Boolean) ((v2_2 instanceof Data_Either.Left))) ? Data_Maybe.__singleton$Nothing.value : ( ((Boolean) ((v2_2 instanceof Data_Either.Right))) ? ((java.util.function.Function<Object, Object>) (__local_var_1)).apply(((Data_Either.Right) (Object)(v2_2)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; } }).get(); return new __Record$69_6e_6a_O$70_72_6a_O(new String[]{"inj", "prj"}, __field0, __field1); } }).get(); };
}
