public class Data_DivisionRing {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.DivisionRing"); }
    };


public static final Object recip = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("recip"); };
public static final Object rightDiv = (java.util.function.Function<Object, Object>) (dictDivisionRing_0) -> { Object Semiring0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictDivisionRing_0).get("Ring0"))).apply(null /* TODO: PrimUndefined */)).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (a_2) -> { return (java.util.function.Function<Object, Object>) (b_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Semiring0_1).get("mul"))).apply(a_2))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictDivisionRing_0).get("recip"))).apply(b_3)); }; }; };
public static final Object leftDiv = (java.util.function.Function<Object, Object>) (dictDivisionRing_0) -> { Object Semiring0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictDivisionRing_0).get("Ring0"))).apply(null /* TODO: PrimUndefined */)).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (a_2) -> { return (java.util.function.Function<Object, Object>) (b_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Semiring0_1).get("mul"))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictDivisionRing_0).get("recip"))).apply(b_3)))).apply(a_2); }; }; };
public static final Object divisionringNumber = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_0) -> { return (((Double) (1.0)) / ((Double) (x_0))); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Ring.ringNumber; }; return new __Record$52_69_6e_67_30_O$72_65_63_69_70_O(new String[]{"recip", "Ring0"}, __field1, __field0); } }).get();
}
