public class Data_Profunctor_Strong {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Profunctor.Strong"); }
    };


public static final Object strongFn = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (a2b_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return new Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (a2b_0)).apply(((Data_Tuple.Tuple) (Object)(v_1)).value0), ((Data_Tuple.Tuple) (Object)(v_1)).value1); }; }; final Object __field1 = ((java.util.function.Function<Object, Object>) (Data_Functor.map)).apply(Data_Tuple.functorTuple); final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Profunctor.profunctorFn; }; return new __Record$50_72_6f_66_75_6e_63_74_6f_72_30_O$66_69_72_73_74_O$73_65_63_6f_6e_64_O(new String[]{"first", "second", "Profunctor0"}, __field2, __field0, __field1); } }).get();
public static final Object second = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("second"); };
public static final Object first = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("first"); };
public static final Object splitStrong = (java.util.function.Function<Object, Object>) (dictSemigroupoid_0) -> { return (java.util.function.Function<Object, Object>) (dictStrong_1) -> { return (java.util.function.Function<Object, Object>) (l_2) -> { return (java.util.function.Function<Object, Object>) (r_3) -> { return Data_Profunctor_Strong.__direct$3(dictSemigroupoid_0, dictStrong_1, l_2, r_3); }; }; }; };
private static Object __direct$3(Object dictSemigroupoid_0, Object dictStrong_1, Object l_2, Object r_3) { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.composeFlipped)).apply(dictSemigroupoid_0))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictStrong_1).get("first"))).apply(l_2)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictStrong_1).get("second"))).apply(r_3)); }
public static final Object fanout = (java.util.function.Function<Object, Object>) (dictSemigroupoid_0) -> { return (java.util.function.Function<Object, Object>) (dictStrong_1) -> { Object Profunctor0_2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictStrong_1).get("Profunctor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (l_3) -> { return (java.util.function.Function<Object, Object>) (r_4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Profunctor0_2).get("dimap"))).apply((java.util.function.Function<Object, Object>) (a_5) -> { return new Data_Tuple.Tuple(a_5, a_5); }))).apply(((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn)))).apply(( ((Boolean) ((Data_Profunctor_Strong.splitStrong == null))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Profunctor_Strong.splitStrong)).apply(dictSemigroupoid_0))).apply(dictStrong_1))).apply(l_3))).apply(r_4) : Data_Profunctor_Strong.__direct$3(dictSemigroupoid_0, dictStrong_1, l_3, r_4))); }; }; }; };
}
