public class Data_Const {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Const"); }
    };


public static final Object Const = (java.util.function.Function<Object, Object>) (x_0) -> { return x_0; };
public static final Object showConst = (java.util.function.Function<Object, Object>) (dictShow_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (((String) ((((String) ("(Const ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); };
public static final Object semiringConst = (java.util.function.Function<Object, Object>) (dictSemiring_0) -> { return dictSemiring_0; };
public static final Object semigroupoidConst = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return v1_1; }; }; return new __Record$63_6f_6d_70_6f_73_65_O(new String[]{"compose"}, __field0); } }).get();
public static final Object semigroupConst = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> { return dictSemigroup_0; };
public static final Object ringConst = (java.util.function.Function<Object, Object>) (dictRing_0) -> { return dictRing_0; };
public static final Object ordConst = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return dictOrd_0; };
public static final Object newtypeConst = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object monoidConst = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> { return dictMonoid_0; };
public static final Object heytingAlgebraConst = (java.util.function.Function<Object, Object>) (dictHeytingAlgebra_0) -> { return dictHeytingAlgebra_0; };
public static final Object functorConst = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (m_1) -> { return m_1; }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get();
public static final Object invariantConst = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (Data_Functor_Invariant.imapF)).apply(Data_Const.functorConst); return new __Record$69_6d_61_70_O(new String[]{"imap"}, __field0); } }).get();
public static final Object euclideanRingConst = (java.util.function.Function<Object, Object>) (dictEuclideanRing_0) -> { return dictEuclideanRing_0; };
public static final Object eqConst = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return dictEq_0; };
public static final Object eq1Const = (java.util.function.Function<Object, Object>) (dictEq_0) -> { Object eq_1 = ((java.util.function.Function<Object, Object>) (Data_Eq.eq)).apply(dictEq_0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictEq1_2) -> { return eq_1; }; return new __Record$65_71_31_O(new String[]{"eq1"}, __field0); } }).get(); };
public static final Object ord1Const = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { Object compare_1 = ((java.util.function.Function<Object, Object>) (Data_Ord.compare)).apply(dictOrd_0); Object eq1Const1_2 = ((java.util.function.Function<Object, Object>) (Data_Const.eq1Const)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("Eq0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictOrd1_3) -> { return compare_1; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> { return eq1Const1_2; }; return new __Record$45_71_31_30_O$63_6f_6d_70_61_72_65_31_O(new String[]{"compare1", "Eq10"}, __field1, __field0); } }).get(); };
public static final Object commutativeRingConst = (java.util.function.Function<Object, Object>) (dictCommutativeRing_0) -> { return dictCommutativeRing_0; };
public static final Object boundedConst = (java.util.function.Function<Object, Object>) (dictBounded_0) -> { return dictBounded_0; };
public static final Object booleanAlgebraConst = (java.util.function.Function<Object, Object>) (dictBooleanAlgebra_0) -> { return dictBooleanAlgebra_0; };
public static final Object applyConst = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictSemigroup_0).get("append"))).apply(v_1))).apply(v1_2); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return Data_Const.functorConst; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get(); };
public static final Object applicativeConst = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> { Object applyConst1_1 = ((java.util.function.Function<Object, Object>) (Data_Const.applyConst)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.Map<String, Object>) dictMonoid_0).get("mempty"); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return applyConst1_1; }; return new __Record$41_70_70_6c_79_30_O$70_75_72_65_O(new String[]{"pure", "Apply0"}, __field1, __field0); } }).get(); };
}
