public class Data_Functor {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Functor"); }
    };
    public static Object arrayMap = FFI_STUB;
    public static Object arrayMap(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Functor.arrayMap"); }

public static final Object map = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("map"); };
public static final Object mapFlipped = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> { return (java.util.function.Function<Object, Object>) (fa_1) -> { return (java.util.function.Function<Object, Object>) (f_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0).get("map"))).apply(f_2))).apply(fa_1); }; }; };
public static final Object $void = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0).get("map"))).apply((java.util.function.Function<Object, Object>) (v_1) -> { return Data_Unit.unit; }); };
public static final Object voidLeft = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> { return (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (x_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0).get("map"))).apply((java.util.function.Function<Object, Object>) (v_3) -> { return x_2; }))).apply(f_1); }; }; };
public static final Object voidRight = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> { return (java.util.function.Function<Object, Object>) (x_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0).get("map"))).apply((java.util.function.Function<Object, Object>) (v_2) -> { return x_1; }); }; };
public static final Object functorProxy = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return Type_Proxy.__singleton$Proxy.value; }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get();
public static final Object functorFn = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn); return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get();
public static final Object functorArray = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = Data_Functor.arrayMap; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get();
public static final Object flap = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> { return (java.util.function.Function<Object, Object>) (ff_1) -> { return (java.util.function.Function<Object, Object>) (x_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0).get("map"))).apply((java.util.function.Function<Object, Object>) (f_3) -> { return ((java.util.function.Function<Object, Object>) (f_3)).apply(x_2); }))).apply(ff_1); }; }; };
}
