public class Data_Functor_Invariant {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Functor.Invariant"); }
    };


public static final Object invariantMultiplicative = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (f_0)).apply(v1_2); }; }; }; return new __Record$69_6d_61_70_O(new String[]{"imap"}, __field0); } }).get();
public static final Object invariantEndo = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (ab_0) -> { return (java.util.function.Function<Object, Object>) (ba_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(ab_0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(v_2))).apply(ba_1)); }; }; }; return new __Record$69_6d_61_70_O(new String[]{"imap"}, __field0); } }).get();
public static final Object invariantDual = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (f_0)).apply(v1_2); }; }; }; return new __Record$69_6d_61_70_O(new String[]{"imap"}, __field0); } }).get();
public static final Object invariantDisj = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (f_0)).apply(v1_2); }; }; }; return new __Record$69_6d_61_70_O(new String[]{"imap"}, __field0); } }).get();
public static final Object invariantConj = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (f_0)).apply(v1_2); }; }; }; return new __Record$69_6d_61_70_O(new String[]{"imap"}, __field0); } }).get();
public static final Object invariantAdditive = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (f_0)).apply(v1_2); }; }; }; return new __Record$69_6d_61_70_O(new String[]{"imap"}, __field0); } }).get();
public static final Object imapF = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> { return (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0).get("map"))).apply(f_1); }; }; };
public static final Object invariantArray = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (Data_Functor_Invariant.imapF)).apply(Data_Functor.functorArray); return new __Record$69_6d_61_70_O(new String[]{"imap"}, __field0); } }).get();
public static final Object invariantFn = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (Data_Functor_Invariant.imapF)).apply(Data_Functor.functorFn); return new __Record$69_6d_61_70_O(new String[]{"imap"}, __field0); } }).get();
public static final Object imap = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("imap"); };
public static final Object invariantAlternate = (java.util.function.Function<Object, Object>) (dictInvariant_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (g_2) -> { return (java.util.function.Function<Object, Object>) (v_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictInvariant_0).get("imap"))).apply(f_1))).apply(g_2))).apply(v_3); }; }; }; return new __Record$69_6d_61_70_O(new String[]{"imap"}, __field0); } }).get(); };
}
