public class Data_Semiring_Generic {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Semiring.Generic"); }
    };


public static final Object genericZeroprime = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("genericZero'"); };
public static final Object genericZero = (java.util.function.Function<Object, Object>) (dictGeneric_0) -> { return (java.util.function.Function<Object, Object>) (dictGenericSemiring_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0).get("to"))).apply(((java.util.Map<String, Object>) dictGenericSemiring_1).get("genericZero'")); }; };
public static final Object genericSemiringNoArguments = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return Data_Generic_Rep.__singleton$NoArguments.value; }; }; final Object __field1 = Data_Generic_Rep.__singleton$NoArguments.value; final Object __field2 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return Data_Generic_Rep.__singleton$NoArguments.value; }; }; final Object __field3 = Data_Generic_Rep.__singleton$NoArguments.value; return new __Record$67_65_6e_65_72_69_63_41_64_64_27_O$67_65_6e_65_72_69_63_4d_75_6c_27_O$67_65_6e_65_72_69_63_4f_6e_65_27_O$67_65_6e_65_72_69_63_5a_65_72_6f_27_O(new String[]{"genericAdd'", "genericZero'", "genericMul'", "genericOne'"}, __field0, __field2, __field3, __field1); } }).get();
public static final Object genericSemiringArgument = (java.util.function.Function<Object, Object>) (dictSemiring_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictSemiring_0).get("add"))).apply(v_1))).apply(v1_2); }; }; final Object __field1 = ((java.util.Map<String, Object>) dictSemiring_0).get("zero"); final Object __field2 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictSemiring_0).get("mul"))).apply(v_1))).apply(v1_2); }; }; final Object __field3 = ((java.util.Map<String, Object>) dictSemiring_0).get("one"); return new __Record$67_65_6e_65_72_69_63_41_64_64_27_O$67_65_6e_65_72_69_63_4d_75_6c_27_O$67_65_6e_65_72_69_63_4f_6e_65_27_O$67_65_6e_65_72_69_63_5a_65_72_6f_27_O(new String[]{"genericAdd'", "genericZero'", "genericMul'", "genericOne'"}, __field0, __field2, __field3, __field1); } }).get(); };
public static final Object genericOneprime = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("genericOne'"); };
public static final Object genericOne = (java.util.function.Function<Object, Object>) (dictGeneric_0) -> { return (java.util.function.Function<Object, Object>) (dictGenericSemiring_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0).get("to"))).apply(((java.util.Map<String, Object>) dictGenericSemiring_1).get("genericOne'")); }; };
public static final Object genericMulprime = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("genericMul'"); };
public static final Object genericMul = (java.util.function.Function<Object, Object>) (dictGeneric_0) -> { Object to_1 = ((java.util.function.Function<Object, Object>) (Data_Generic_Rep.to)).apply(dictGeneric_0); return (java.util.function.Function<Object, Object>) (dictGenericSemiring_2) -> { return (java.util.function.Function<Object, Object>) (x_3) -> { return (java.util.function.Function<Object, Object>) (y_4) -> { return ((java.util.function.Function<Object, Object>) (to_1)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemiring_2).get("genericMul'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0).get("from"))).apply(x_3)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0).get("from"))).apply(y_4))); }; }; }; };
public static final Object genericAddprime = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("genericAdd'"); };
public static final Object genericSemiringConstructor = (java.util.function.Function<Object, Object>) (dictGenericSemiring_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemiring_0).get("genericAdd'"))).apply(v_1))).apply(v1_2); }; }; final Object __field1 = ((java.util.Map<String, Object>) dictGenericSemiring_0).get("genericZero'"); final Object __field2 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemiring_0).get("genericMul'"))).apply(v_1))).apply(v1_2); }; }; final Object __field3 = ((java.util.Map<String, Object>) dictGenericSemiring_0).get("genericOne'"); return new __Record$67_65_6e_65_72_69_63_41_64_64_27_O$67_65_6e_65_72_69_63_4d_75_6c_27_O$67_65_6e_65_72_69_63_4f_6e_65_27_O$67_65_6e_65_72_69_63_5a_65_72_6f_27_O(new String[]{"genericAdd'", "genericZero'", "genericMul'", "genericOne'"}, __field0, __field2, __field3, __field1); } }).get(); };
public static final Object genericSemiringProduct = (java.util.function.Function<Object, Object>) (dictGenericSemiring_0) -> { return (java.util.function.Function<Object, Object>) (dictGenericSemiring1_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { return new Data_Generic_Rep.Product(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemiring_0).get("genericAdd'"))).apply(((Data_Generic_Rep.Product) (Object)(v_2)).value0))).apply(((Data_Generic_Rep.Product) (Object)(v1_3)).value0), ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemiring1_1).get("genericAdd'"))).apply(((Data_Generic_Rep.Product) (Object)(v_2)).value1))).apply(((Data_Generic_Rep.Product) (Object)(v1_3)).value1)); }; }; final Object __field1 = new Data_Generic_Rep.Product(((java.util.Map<String, Object>) dictGenericSemiring_0).get("genericZero'"), ((java.util.Map<String, Object>) dictGenericSemiring1_1).get("genericZero'")); final Object __field2 = (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { return new Data_Generic_Rep.Product(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemiring_0).get("genericMul'"))).apply(((Data_Generic_Rep.Product) (Object)(v_2)).value0))).apply(((Data_Generic_Rep.Product) (Object)(v1_3)).value0), ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemiring1_1).get("genericMul'"))).apply(((Data_Generic_Rep.Product) (Object)(v_2)).value1))).apply(((Data_Generic_Rep.Product) (Object)(v1_3)).value1)); }; }; final Object __field3 = new Data_Generic_Rep.Product(((java.util.Map<String, Object>) dictGenericSemiring_0).get("genericOne'"), ((java.util.Map<String, Object>) dictGenericSemiring1_1).get("genericOne'")); return new __Record$67_65_6e_65_72_69_63_41_64_64_27_O$67_65_6e_65_72_69_63_4d_75_6c_27_O$67_65_6e_65_72_69_63_4f_6e_65_27_O$67_65_6e_65_72_69_63_5a_65_72_6f_27_O(new String[]{"genericAdd'", "genericZero'", "genericMul'", "genericOne'"}, __field0, __field2, __field3, __field1); } }).get(); }; };
public static final Object genericAdd = (java.util.function.Function<Object, Object>) (dictGeneric_0) -> { Object to_1 = ((java.util.function.Function<Object, Object>) (Data_Generic_Rep.to)).apply(dictGeneric_0); return (java.util.function.Function<Object, Object>) (dictGenericSemiring_2) -> { return (java.util.function.Function<Object, Object>) (x_3) -> { return (java.util.function.Function<Object, Object>) (y_4) -> { return ((java.util.function.Function<Object, Object>) (to_1)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemiring_2).get("genericAdd'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0).get("from"))).apply(x_3)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0).get("from"))).apply(y_4))); }; }; }; };
}
