public class Data_Semigroup_Foldable {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Semigroup.Foldable"); }
    };


public static final class FoldRight1 {
            public final Object value0;
            public final Object value1;
            public FoldRight1(Object value0, Object value1) {
                this.value0 = value0;
                this.value1 = value1;
            }
        }
public static final Object JoinWith = (java.util.function.Function<Object, Object>) (x_0) -> { return x_0; };
public static final Object FoldRight1 = (java.util.function.Function<Object, Object>) (value0) -> (java.util.function.Function<Object, Object>) (value1) -> { return new Data_Semigroup_Foldable.FoldRight1(value0, value1); };
public static final Object Act = (java.util.function.Function<Object, Object>) (x_0) -> { return x_0; };
public static final Object semigroupJoinWith = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return (java.util.function.Function<Object, Object>) (j_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictSemigroup_0).get("append"))).apply(((java.util.function.Function<Object, Object>) (v_1)).apply(j_3)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictSemigroup_0).get("append"))).apply(j_3))).apply(((java.util.function.Function<Object, Object>) (v1_2)).apply(j_3))); }; }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get(); };
public static final Object semigroupAct = (java.util.function.Function<Object, Object>) (dictApply_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Apply.applySecond)).apply(dictApply_0))).apply(v_1))).apply(v1_2); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get(); };
public static final Object runFoldRight1 = (java.util.function.Function<Object, Object>) (v_0) -> { return ((java.util.function.Function<Object, Object>) (((Data_Semigroup_Foldable.FoldRight1) (Object)(v_0)).value0)).apply(((Data_Semigroup_Foldable.FoldRight1) (Object)(v_0)).value1); };
public static final Object mkFoldRight1 = ((java.util.function.Function<Object, Object>) (Data_Semigroup_Foldable.FoldRight1)).apply(Data_Function.$const);
public static final Object getAct = (java.util.function.Function<Object, Object>) (v_0) -> { return v_0; };
public static final Object foldr1 = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("foldr1"); };
public static final Object foldl1 = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("foldl1"); };
public static final Object maximumBy = (java.util.function.Function<Object, Object>) (dictFoldable1_0) -> { return (java.util.function.Function<Object, Object>) (cmp_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable1_0).get("foldl1"))).apply((java.util.function.Function<Object, Object>) (x_2) -> { return (java.util.function.Function<Object, Object>) (y_3) -> { return ( ((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (cmp_1)).apply(x_2))).apply(y_3) instanceof Data_Ordering.GT))) ? x_2 : y_3); }; }); }; };
public static final Object minimumBy = (java.util.function.Function<Object, Object>) (dictFoldable1_0) -> { return (java.util.function.Function<Object, Object>) (cmp_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable1_0).get("foldl1"))).apply((java.util.function.Function<Object, Object>) (x_2) -> { return (java.util.function.Function<Object, Object>) (y_3) -> { return ( ((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (cmp_1)).apply(x_2))).apply(y_3) instanceof Data_Ordering.LT))) ? x_2 : y_3); }; }); }; };
public static final Object foldableTuple = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> { return (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (f_1)).apply(((Data_Tuple.Tuple) (Object)(v_2)).value1); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return ((Data_Tuple.Tuple) (Object)(v1_1)).value1; }; }; final Object __field2 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return ((Data_Tuple.Tuple) (Object)(v1_1)).value1; }; }; final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Foldable.foldableTuple; }; return new __Record$46_6f_6c_64_61_62_6c_65_30_O$66_6f_6c_64_4d_61_70_31_O$66_6f_6c_64_6c_31_O$66_6f_6c_64_72_31_O(new String[]{"foldMap1", "foldr1", "foldl1", "Foldable0"}, __field3, __field0, __field2, __field1); } }).get();
public static final Object foldableMultiplicative = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return v1_1; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return v1_1; }; }; final Object __field2 = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> { return (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (f_1)).apply(v_2); }; }; }; final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Foldable.foldableMultiplicative; }; return new __Record$46_6f_6c_64_61_62_6c_65_30_O$66_6f_6c_64_4d_61_70_31_O$66_6f_6c_64_6c_31_O$66_6f_6c_64_72_31_O(new String[]{"foldr1", "foldl1", "foldMap1", "Foldable0"}, __field3, __field2, __field1, __field0); } }).get();
public static final Object foldableIdentity = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> { return (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (f_1)).apply(v_2); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return v1_1; }; }; final Object __field2 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return v1_1; }; }; final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Foldable.foldableIdentity; }; return new __Record$46_6f_6c_64_61_62_6c_65_30_O$66_6f_6c_64_4d_61_70_31_O$66_6f_6c_64_6c_31_O$66_6f_6c_64_72_31_O(new String[]{"foldMap1", "foldl1", "foldr1", "Foldable0"}, __field3, __field0, __field1, __field2); } }).get();
public static final Object foldableDual = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return v1_1; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return v1_1; }; }; final Object __field2 = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> { return (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (f_1)).apply(v_2); }; }; }; final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Foldable.foldableDual; }; return new __Record$46_6f_6c_64_61_62_6c_65_30_O$66_6f_6c_64_4d_61_70_31_O$66_6f_6c_64_6c_31_O$66_6f_6c_64_72_31_O(new String[]{"foldr1", "foldl1", "foldMap1", "Foldable0"}, __field3, __field2, __field1, __field0); } }).get();
public static final Object foldRight1Semigroup = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { Object __local_var_2 = ((Data_Semigroup_Foldable.FoldRight1) (Object)(v_0)).value1; return new Data_Semigroup_Foldable.FoldRight1((java.util.function.Function<Object, Object>) (a_3) -> { return (java.util.function.Function<Object, Object>) (f_4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((Data_Semigroup_Foldable.FoldRight1) (Object)(v_0)).value0)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_4)).apply(__local_var_2))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((Data_Semigroup_Foldable.FoldRight1) (Object)(v1_1)).value0)).apply(a_3))).apply(f_4))))).apply(f_4); }; }, ((Data_Semigroup_Foldable.FoldRight1) (Object)(v1_1)).value1); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get();
public static final Object foldMap1DefaultR = (java.util.function.Function<Object, Object>) (dictFoldable1_0) -> { return (java.util.function.Function<Object, Object>) (dictFunctor_1) -> { return (java.util.function.Function<Object, Object>) (dictSemigroup_2) -> { Object append_3 = ((java.util.function.Function<Object, Object>) (Data_Semigroup.append)).apply(dictSemigroup_2); return (java.util.function.Function<Object, Object>) (f_4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.composeFlipped)).apply(Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_1).get("map"))).apply(f_4)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable1_0).get("foldr1"))).apply(append_3)); }; }; }; };
public static final Object foldMap1DefaultL = (java.util.function.Function<Object, Object>) (dictFoldable1_0) -> { return (java.util.function.Function<Object, Object>) (dictFunctor_1) -> { return (java.util.function.Function<Object, Object>) (dictSemigroup_2) -> { Object append_3 = ((java.util.function.Function<Object, Object>) (Data_Semigroup.append)).apply(dictSemigroup_2); return (java.util.function.Function<Object, Object>) (f_4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.composeFlipped)).apply(Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_1).get("map"))).apply(f_4)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable1_0).get("foldl1"))).apply(append_3)); }; }; }; };
public static final Object foldMap1 = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("foldMap1"); };
public static final Object foldl1Default = (java.util.function.Function<Object, Object>) (dictFoldable1_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(Data_Semigroup_Foldable.runFoldRight1))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Semigroup_Foldable.foldMap1)).apply(dictFoldable1_0))).apply(((java.util.function.Function<Object, Object>) (Data_Monoid_Dual.semigroupDual)).apply(Data_Semigroup_Foldable.foldRight1Semigroup))))).apply(Data_Semigroup_Foldable.mkFoldRight1)); return (java.util.function.Function<Object, Object>) (b_2) -> { return (java.util.function.Function<Object, Object>) (a_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_1)).apply(a_3))).apply(b_2); }; }; } }).get()))).apply(Data_Function.flip); };
public static final Object foldr1Default = (java.util.function.Function<Object, Object>) (dictFoldable1_0) -> { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(Data_Semigroup_Foldable.runFoldRight1))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable1_0).get("foldMap1"))).apply(Data_Semigroup_Foldable.foldRight1Semigroup))).apply(Data_Semigroup_Foldable.mkFoldRight1)); return (java.util.function.Function<Object, Object>) (b_2) -> { return (java.util.function.Function<Object, Object>) (a_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_1)).apply(a_3))).apply(b_2); }; }; };
public static final Object intercalateMap = (java.util.function.Function<Object, Object>) (dictFoldable1_0) -> { return (java.util.function.Function<Object, Object>) (dictSemigroup_1) -> { return Data_Semigroup_Foldable.__direct$23(dictFoldable1_0, dictSemigroup_1); }; };
private static Object __direct$23(Object dictFoldable1_0, Object dictSemigroup_1) { Object semigroupJoinWith1_2 = ((java.util.function.Function<Object, Object>) (Data_Semigroup_Foldable.semigroupJoinWith)).apply(dictSemigroup_1); return (java.util.function.Function<Object, Object>) (j_3) -> { return (java.util.function.Function<Object, Object>) (f_4) -> { return (java.util.function.Function<Object, Object>) (foldable_5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable1_0).get("foldMap1"))).apply(semigroupJoinWith1_2))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(Data_Semigroup_Foldable.JoinWith))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(Data_Function.$const))).apply(f_4))))).apply(foldable_5))).apply(j_3); }; }; }; }
public static final Object intercalate = (java.util.function.Function<Object, Object>) (dictFoldable1_0) -> { return (java.util.function.Function<Object, Object>) (dictSemigroup_1) -> { Object __local_var_2 = ( ((Boolean) ((Data_Semigroup_Foldable.intercalateMap == null))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Semigroup_Foldable.intercalateMap)).apply(dictFoldable1_0))).apply(dictSemigroup_1) : Data_Semigroup_Foldable.__direct$23(dictFoldable1_0, dictSemigroup_1)); Object __local_var_3 = ((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn); return (java.util.function.Function<Object, Object>) (a_4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_2)).apply(a_4))).apply(__local_var_3); }; }; };
public static final Object maximum = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { Object semigroupMax_1 = ((java.util.function.Function<Object, Object>) (Data_Ord_Max.semigroupMax)).apply(dictOrd_0); return (java.util.function.Function<Object, Object>) (dictFoldable1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Semigroup_Foldable.foldMap1)).apply(dictFoldable1_2))).apply(semigroupMax_1))).apply(((java.util.function.Function<Object, Object>) (Data_Newtype.wrap)).apply(null /* TODO: PrimUndefined */)); }; };
public static final Object minimum = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { Object semigroupMin_1 = ((java.util.function.Function<Object, Object>) (Data_Ord_Min.semigroupMin)).apply(dictOrd_0); return (java.util.function.Function<Object, Object>) (dictFoldable1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Semigroup_Foldable.foldMap1)).apply(dictFoldable1_2))).apply(semigroupMin_1))).apply(((java.util.function.Function<Object, Object>) (Data_Newtype.wrap)).apply(null /* TODO: PrimUndefined */)); }; };
public static final Object traverse1_ = (java.util.function.Function<Object, Object>) (dictFoldable1_0) -> { return (java.util.function.Function<Object, Object>) (dictApply_1) -> { return Data_Semigroup_Foldable.__direct$27(dictFoldable1_0, dictApply_1); }; };
private static Object __direct$27(Object dictFoldable1_0, Object dictApply_1) { Object Functor0_2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_1).get("Functor0"))).apply(null /* TODO: PrimUndefined */); Object semigroupAct1_3 = ((java.util.function.Function<Object, Object>) (Data_Semigroup_Foldable.semigroupAct)).apply(dictApply_1); return (java.util.function.Function<Object, Object>) (f_4) -> { return (java.util.function.Function<Object, Object>) (t_5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_2).get("map"))).apply((java.util.function.Function<Object, Object>) (v_6) -> { return Data_Unit.unit; }))).apply(((java.util.function.Function<Object, Object>) (Data_Semigroup_Foldable.getAct)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable1_0).get("foldMap1"))).apply(semigroupAct1_3))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(Data_Semigroup_Foldable.Act))).apply(f_4)))).apply(t_5))); }; }; }
public static final Object for1_ = (java.util.function.Function<Object, Object>) (dictFoldable1_0) -> { return (java.util.function.Function<Object, Object>) (dictApply_1) -> { Object __local_var_2 = ( ((Boolean) ((Data_Semigroup_Foldable.traverse1_ == null))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Semigroup_Foldable.traverse1_)).apply(dictFoldable1_0))).apply(dictApply_1) : Data_Semigroup_Foldable.__direct$27(dictFoldable1_0, dictApply_1)); return (java.util.function.Function<Object, Object>) (b_3) -> { return (java.util.function.Function<Object, Object>) (a_4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_2)).apply(a_4))).apply(b_3); }; }; }; };
public static final Object sequence1_ = (java.util.function.Function<Object, Object>) (dictFoldable1_0) -> { return (java.util.function.Function<Object, Object>) (dictApply_1) -> { return ((java.util.function.Function<Object, Object>) (( ((Boolean) ((Data_Semigroup_Foldable.traverse1_ == null))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Semigroup_Foldable.traverse1_)).apply(dictFoldable1_0))).apply(dictApply_1) : Data_Semigroup_Foldable.__direct$27(dictFoldable1_0, dictApply_1)))).apply(((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn)); }; };
public static final Object fold1 = (java.util.function.Function<Object, Object>) (dictFoldable1_0) -> { return (java.util.function.Function<Object, Object>) (dictSemigroup_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable1_0).get("foldMap1"))).apply(dictSemigroup_1))).apply(((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn)); }; };
}
