public class Data_Decidable {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Decidable"); }
    };


public static final Object lose = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("lose"); };
public static final Object lost = (java.util.function.Function<Object, Object>) (dictDecidable_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictDecidable_0).get("lose"))).apply(((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn)); };
public static final Object decidablePredicate = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (a_1) -> { Object spin_2 = (java.util.function.Function<Object, Object>) (v_3) -> { Object __tco_v_3 = v_3; while(true) { final Object __final_v_3 = __tco_v_3; try { { final Object __next_v_3 = __final_v_3; __tco_v_3 = __next_v_3; continue; } } catch (TcoLoop __tco_ex) { __tco_v_3 = __tco_ex.args[0]; } } }; return ((java.util.function.Function<Object, Object>) (spin_2)).apply(((java.util.function.Function<Object, Object>) (f_0)).apply(a_1)); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Decide.choosePredicate; }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Divisible.divisiblePredicate; }; return new __Record$44_65_63_69_64_65_30_O$44_69_76_69_73_69_62_6c_65_31_O$6c_6f_73_65_O(new String[]{"lose", "Decide0", "Divisible1"}, __field1, __field2, __field0); } }).get();
public static final Object decidableOp = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> { Object chooseOp_1 = ((java.util.function.Function<Object, Object>) (Data_Decide.chooseOp)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); Object divisibleOp_2 = ((java.util.function.Function<Object, Object>) (Data_Divisible.divisibleOp)).apply(dictMonoid_0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_3) -> { return (java.util.function.Function<Object, Object>) (a_4) -> { Object spin_5 = (java.util.function.Function<Object, Object>) (v_6) -> { Object __tco_v_6 = v_6; while(true) { final Object __final_v_6 = __tco_v_6; try { { final Object __next_v_6 = __final_v_6; __tco_v_6 = __next_v_6; continue; } } catch (TcoLoop __tco_ex) { __tco_v_6 = __tco_ex.args[0]; } } }; return ((java.util.function.Function<Object, Object>) (spin_5)).apply(((java.util.function.Function<Object, Object>) (f_3)).apply(a_4)); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> { return chooseOp_1; }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> { return divisibleOp_2; }; return new __Record$44_65_63_69_64_65_30_O$44_69_76_69_73_69_62_6c_65_31_O$6c_6f_73_65_O(new String[]{"lose", "Decide0", "Divisible1"}, __field1, __field2, __field0); } }).get(); };
public static final Object decidableEquivalence = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (a_1) -> { Object spin_2 = (java.util.function.Function<Object, Object>) (v_3) -> { Object __tco_v_3 = v_3; while(true) { final Object __final_v_3 = __tco_v_3; try { { final Object __next_v_3 = __final_v_3; __tco_v_3 = __next_v_3; continue; } } catch (TcoLoop __tco_ex) { __tco_v_3 = __tco_ex.args[0]; } } }; return ((java.util.function.Function<Object, Object>) (spin_2)).apply(((java.util.function.Function<Object, Object>) (f_0)).apply(a_1)); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Decide.chooseEquivalence; }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Divisible.divisibleEquivalence; }; return new __Record$44_65_63_69_64_65_30_O$44_69_76_69_73_69_62_6c_65_31_O$6c_6f_73_65_O(new String[]{"lose", "Decide0", "Divisible1"}, __field1, __field2, __field0); } }).get();
public static final Object decidableComparison = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (a_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { Object spin_3 = (java.util.function.Function<Object, Object>) (v_4) -> { Object __tco_v_4 = v_4; while(true) { final Object __final_v_4 = __tco_v_4; try { { final Object __next_v_4 = __final_v_4; __tco_v_4 = __next_v_4; continue; } } catch (TcoLoop __tco_ex) { __tco_v_4 = __tco_ex.args[0]; } } }; return ((java.util.function.Function<Object, Object>) (spin_3)).apply(((java.util.function.Function<Object, Object>) (f_0)).apply(a_1)); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Decide.chooseComparison; }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Divisible.divisibleComparison; }; return new __Record$44_65_63_69_64_65_30_O$44_69_76_69_73_69_62_6c_65_31_O$6c_6f_73_65_O(new String[]{"lose", "Decide0", "Divisible1"}, __field1, __field2, __field0); } }).get();
}
