public class Data_Functor_Flip {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Functor.Flip"); }
    };


public static final Object Flip = (java.util.function.Function<Object, Object>) (x_0) -> { return x_0; };
public static final Object showFlip = (java.util.function.Function<Object, Object>) (dictShow_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (((String) ((((String) ("(Flip ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); };
public static final Object semigroupoidFlip = (java.util.function.Function<Object, Object>) (dictSemigroupoid_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(dictSemigroupoid_0))).apply(v1_2))).apply(v_1); }; }; return new __Record$63_6f_6d_70_6f_73_65_O(new String[]{"compose"}, __field0); } }).get(); };
public static final Object ordFlip = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return dictOrd_0; };
public static final Object newtypeFlip = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object functorFlip = (java.util.function.Function<Object, Object>) (dictBifunctor_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBifunctor_0).get("bimap"))).apply(f_1))).apply(((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn)))).apply(v_2); }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get(); };
public static final Object eqFlip = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return dictEq_0; };
public static final Object contravariantFlip = (java.util.function.Function<Object, Object>) (dictProfunctor_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictProfunctor_0).get("dimap"))).apply(f_1))).apply(((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn)))).apply(v_2); }; }; return new __Record$63_6d_61_70_O(new String[]{"cmap"}, __field0); } }).get(); };
public static final Object categoryFlip = (java.util.function.Function<Object, Object>) (dictCategory_0) -> { Object semigroupoidFlip1_1 = ((java.util.function.Function<Object, Object>) (Data_Functor_Flip.semigroupoidFlip)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictCategory_0).get("Semigroupoid0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(dictCategory_0); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return semigroupoidFlip1_1; }; return new __Record$53_65_6d_69_67_72_6f_75_70_6f_69_64_30_O$69_64_65_6e_74_69_74_79_O(new String[]{"identity", "Semigroupoid0"}, __field1, __field0); } }).get(); };
public static final Object bifunctorFlip = (java.util.function.Function<Object, Object>) (dictBifunctor_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (g_2) -> { return (java.util.function.Function<Object, Object>) (v_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBifunctor_0).get("bimap"))).apply(g_2))).apply(f_1))).apply(v_3); }; }; }; return new __Record$62_69_6d_61_70_O(new String[]{"bimap"}, __field0); } }).get(); };
public static final Object biapplyFlip = (java.util.function.Function<Object, Object>) (dictBiapply_0) -> { Object bifunctorFlip1_1 = ((java.util.function.Function<Object, Object>) (Data_Functor_Flip.bifunctorFlip)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapply_0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapply_0).get("biapply"))).apply(v_2))).apply(v1_3); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return bifunctorFlip1_1; }; return new __Record$42_69_66_75_6e_63_74_6f_72_30_O$62_69_61_70_70_6c_79_O(new String[]{"biapply", "Bifunctor0"}, __field1, __field0); } }).get(); };
public static final Object biapplicativeFlip = (java.util.function.Function<Object, Object>) (dictBiapplicative_0) -> { Object biapplyFlip1_1 = ((java.util.function.Function<Object, Object>) (Data_Functor_Flip.biapplyFlip)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapplicative_0).get("Biapply0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (a_2) -> { return (java.util.function.Function<Object, Object>) (b_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapplicative_0).get("bipure"))).apply(b_3))).apply(a_2); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return biapplyFlip1_1; }; return new __Record$42_69_61_70_70_6c_79_30_O$62_69_70_75_72_65_O(new String[]{"bipure", "Biapply0"}, __field1, __field0); } }).get(); };
}
