public class Data_Newtype {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Newtype"); }
    };


public static final Object wrap = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return ((java.util.function.Function<Object, Object>) (Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */); };
public static final Object unwrap = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return ((java.util.function.Function<Object, Object>) (Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */); };
public static final Object underF2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> { return (java.util.function.Function<Object, Object>) (v_4) -> { return ((java.util.function.Function<Object, Object>) (Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */); }; }; }; }; };
public static final Object underF = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> { return (java.util.function.Function<Object, Object>) (v_4) -> { return ((java.util.function.Function<Object, Object>) (Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */); }; }; }; }; };
public static final Object under2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */); }; }; };
public static final Object under = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */); }; }; };
public static final Object un = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return ((java.util.function.Function<Object, Object>) (Data_Newtype.unwrap)).apply(null /* TODO: PrimUndefined */); }; };
public static final Object traverse = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */); }; }; };
public static final Object overF2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> { return (java.util.function.Function<Object, Object>) (v_4) -> { return ((java.util.function.Function<Object, Object>) (Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */); }; }; }; }; };
public static final Object overF = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> { return (java.util.function.Function<Object, Object>) (v_4) -> { return ((java.util.function.Function<Object, Object>) (Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */); }; }; }; }; };
public static final Object over2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */); }; }; };
public static final Object over = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */); }; }; };
public static final Object newtypeMultiplicative = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object newtypeLast = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object newtypeFirst = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object newtypeEndo = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object newtypeDual = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object newtypeDisj = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object newtypeConj = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object newtypeAdditive = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object modify = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return (java.util.function.Function<Object, Object>) (fn_1) -> { return (java.util.function.Function<Object, Object>) (t_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply(((java.util.function.Function<Object, Object>) (fn_1)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply(t_2))); }; }; };
public static final Object collect = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */); }; }; };
public static final Object alaF = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> { return (java.util.function.Function<Object, Object>) (v_4) -> { return ((java.util.function.Function<Object, Object>) (Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */); }; }; }; }; };
public static final Object ala = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return (java.util.function.Function<Object, Object>) (v_3) -> { return (java.util.function.Function<Object, Object>) (f_4) -> { return ((java.util.function.Function<Object, Object>) (f_4)).apply(((java.util.function.Function<Object, Object>) (Data_Newtype.wrap)).apply(null /* TODO: PrimUndefined */)); }; }; }; }; };
}
