public class Data_Show_Generic {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Show.Generic"); }
    };
    public static Object intercalate = FFI_STUB;
    public static Object intercalate(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Show.Generic.intercalate"); }

public static final Object genericShowArgsNoArguments = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return new Object[]{}; }; return new __Record$67_65_6e_65_72_69_63_53_68_6f_77_41_72_67_73_O(new String[]{"genericShowArgs"}, __field0); } }).get();
public static final Object genericShowArgsArgument = (java.util.function.Function<Object, Object>) (dictShow_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return new Object[]{((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0).get("show"))).apply(v_1)}; }; return new __Record$67_65_6e_65_72_69_63_53_68_6f_77_41_72_67_73_O(new String[]{"genericShowArgs"}, __field0); } }).get(); };
public static final Object genericShowArgs = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("genericShowArgs"); };
public static final Object genericShowArgsProduct = (java.util.function.Function<Object, Object>) (dictGenericShowArgs_0) -> { return (java.util.function.Function<Object, Object>) (dictGenericShowArgs1_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Semigroup.concatArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericShowArgs_0).get("genericShowArgs"))).apply(((Data_Generic_Rep.Product) (Object)(v_2)).value0)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericShowArgs1_1).get("genericShowArgs"))).apply(((Data_Generic_Rep.Product) (Object)(v_2)).value1)); }; return new __Record$67_65_6e_65_72_69_63_53_68_6f_77_41_72_67_73_O(new String[]{"genericShowArgs"}, __field0); } }).get(); }; };
public static final Object genericShowConstructor = (java.util.function.Function<Object, Object>) (dictGenericShowArgs_0) -> { return (java.util.function.Function<Object, Object>) (dictIsSymbol_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { Object ctor_3 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictIsSymbol_1).get("reflectSymbol"))).apply(Type_Proxy.__singleton$Proxy.value); Object v1_4 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericShowArgs_0).get("genericShowArgs"))).apply(v_2); return ( ((Boolean) ((((int) (((Object[]) (Object)(v1_4)).length)) == ((int) (0))))) ? ctor_3 : (((String) ((((String) ("(")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Show_Generic.intercalate)).apply(" "))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Semigroup.concatArray)).apply(new Object[]{ctor_3}))).apply(v1_4))))))) + ((String) (")")))); }; return new __Record$67_65_6e_65_72_69_63_53_68_6f_77_27_O(new String[]{"genericShow'"}, __field0); } }).get(); }; };
public static final Object genericShowprime = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("genericShow'"); };
private static Object __lazy_value_genericShowNoConstructors;
private static int __lazy_state_genericShowNoConstructors;
private static Object __lazy_get_genericShowNoConstructors() { if (__lazy_state_genericShowNoConstructors == 2) return __lazy_value_genericShowNoConstructors; if (__lazy_state_genericShowNoConstructors == 1) throw new IllegalStateException("Recursive initialization of genericShowNoConstructors"); __lazy_state_genericShowNoConstructors = 1; __lazy_value_genericShowNoConstructors = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (a_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Data_Show_Generic.__lazy_get_genericShowNoConstructors()).get("genericShow'"))).apply(a_0); }; return new __Record$67_65_6e_65_72_69_63_53_68_6f_77_27_O(new String[]{"genericShow'"}, __field0); } }).get(); __lazy_state_genericShowNoConstructors = 2; return __lazy_value_genericShowNoConstructors; }
public static final Object genericShowNoConstructors = __lazy_get_genericShowNoConstructors();
public static final Object genericShowSum = (java.util.function.Function<Object, Object>) (dictGenericShow_0) -> { return (java.util.function.Function<Object, Object>) (dictGenericShow1_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return ( ((Boolean) ((v_2 instanceof Data_Generic_Rep.Inl))) ? ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericShow_0).get("genericShow'"))).apply(((Data_Generic_Rep.Inl) (Object)(v_2)).value0) : ( ((Boolean) ((v_2 instanceof Data_Generic_Rep.Inr))) ? ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericShow1_1).get("genericShow'"))).apply(((Data_Generic_Rep.Inr) (Object)(v_2)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; return new __Record$67_65_6e_65_72_69_63_53_68_6f_77_27_O(new String[]{"genericShow'"}, __field0); } }).get(); }; };
public static final Object genericShow = (java.util.function.Function<Object, Object>) (dictGeneric_0) -> { return (java.util.function.Function<Object, Object>) (dictGenericShow_1) -> { return (java.util.function.Function<Object, Object>) (x_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericShow_1).get("genericShow'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0).get("from"))).apply(x_2)); }; }; };
}
