public class Data_Profunctor_Choice {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Profunctor.Choice"); }
    };


public static final Object right = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("right"); };
public static final Object left = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("left"); };
public static final Object splitChoice = (java.util.function.Function<Object, Object>) (dictSemigroupoid_0) -> { return (java.util.function.Function<Object, Object>) (dictChoice_1) -> { return (java.util.function.Function<Object, Object>) (l_2) -> { return (java.util.function.Function<Object, Object>) (r_3) -> { return Data_Profunctor_Choice.__direct$2(dictSemigroupoid_0, dictChoice_1, l_2, r_3); }; }; }; };
private static Object __direct$2(Object dictSemigroupoid_0, Object dictChoice_1, Object l_2, Object r_3) { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.composeFlipped)).apply(dictSemigroupoid_0))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictChoice_1).get("left"))).apply(l_2)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictChoice_1).get("right"))).apply(r_3)); }
public static final Object fanin = (java.util.function.Function<Object, Object>) (dictSemigroupoid_0) -> { return (java.util.function.Function<Object, Object>) (dictChoice_1) -> { Object Profunctor0_2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictChoice_1).get("Profunctor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (l_3) -> { return (java.util.function.Function<Object, Object>) (r_4) -> { Object __local_var_5 = ((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Profunctor0_2).get("dimap"))).apply(((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn)))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_6 = ((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn); return (java.util.function.Function<Object, Object>) (v2_7) -> { return ( ((Boolean) ((v2_7 instanceof Data_Either.Left))) ? ((java.util.function.Function<Object, Object>) (__local_var_5)).apply(((Data_Either.Left) (Object)(v2_7)).value0) : ( ((Boolean) ((v2_7 instanceof Data_Either.Right))) ? ((java.util.function.Function<Object, Object>) (__local_var_6)).apply(((Data_Either.Right) (Object)(v2_7)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; } }).get()))).apply(( ((Boolean) ((Data_Profunctor_Choice.splitChoice == null))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Profunctor_Choice.splitChoice)).apply(dictSemigroupoid_0))).apply(dictChoice_1))).apply(l_3))).apply(r_4) : Data_Profunctor_Choice.__direct$2(dictSemigroupoid_0, dictChoice_1, l_3, r_4))); }; }; }; };
public static final Object choiceFn = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return ( ((Boolean) ((v1_1 instanceof Data_Either.Left))) ? new Data_Either.Left(((java.util.function.Function<Object, Object>) (v_0)).apply(((Data_Either.Left) (Object)(v1_1)).value0)) : ( ((Boolean) ((v1_1 instanceof Data_Either.Right))) ? new Data_Either.Right(((Data_Either.Right) (Object)(v1_1)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }; final Object __field1 = ((java.util.function.Function<Object, Object>) (Data_Functor.map)).apply(Data_Either.functorEither); final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Profunctor.profunctorFn; }; return new __Record$50_72_6f_66_75_6e_63_74_6f_72_30_O$6c_65_66_74_O$72_69_67_68_74_O(new String[]{"left", "right", "Profunctor0"}, __field2, __field0, __field1); } }).get();
}
