public class Data_Unfoldable {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Unfoldable"); }
    };
    public static Object unfoldrArrayImpl = FFI_STUB;
    public static Object unfoldrArrayImpl(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Unfoldable.unfoldrArrayImpl"); }

public static final Object unfoldr = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("unfoldr"); };
public static final Object unfoldableMaybe = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (b_1) -> { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (f_0)).apply(b_1); return ( ((Boolean) ((__local_var_2 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (Data_Tuple.fst)).apply(((Data_Maybe.Just) (Object)(__local_var_2)).value0)) : Data_Maybe.__singleton$Nothing.value); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Unfoldable1.unfoldable1Maybe; }; return new __Record$55_6e_66_6f_6c_64_61_62_6c_65_31_30_O$75_6e_66_6f_6c_64_72_O(new String[]{"unfoldr", "Unfoldable10"}, __field1, __field0); } }).get();
public static final Object unfoldableArray = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Unfoldable.unfoldrArrayImpl)).apply(Data_Maybe.isNothing))).apply((java.util.function.Function<Object, Object>) (v_0) -> { return ( ((Boolean) ((v_0 instanceof Data_Maybe.Just))) ? ((Data_Maybe.Just) (Object)(v_0)).value0 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()); }))).apply(Data_Tuple.fst))).apply(Data_Tuple.snd); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Unfoldable1.unfoldable1Array; }; return new __Record$55_6e_66_6f_6c_64_61_62_6c_65_31_30_O$75_6e_66_6f_6c_64_72_O(new String[]{"unfoldr", "Unfoldable10"}, __field1, __field0); } }).get();
public static final Object replicate = (java.util.function.Function<Object, Object>) (dictUnfoldable_0) -> { return (java.util.function.Function<Object, Object>) (n_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictUnfoldable_0).get("unfoldr"))).apply((java.util.function.Function<Object, Object>) (i_3) -> { return ( ((Boolean) ((((int) (i_3)) <= ((int) (0))))) ? Data_Maybe.__singleton$Nothing.value : new Data_Maybe.Just(new Data_Tuple.Tuple(v_2, (((int) (i_3)) - ((int) (1)))))); }))).apply(n_1); }; }; };
public static final Object replicateA = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> { return (java.util.function.Function<Object, Object>) (dictUnfoldable_1) -> { return (java.util.function.Function<Object, Object>) (dictTraversable_2) -> { return (java.util.function.Function<Object, Object>) (n_3) -> { return (java.util.function.Function<Object, Object>) (m_4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictTraversable_2).get("sequence"))).apply(dictApplicative_0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictUnfoldable_1).get("unfoldr"))).apply((java.util.function.Function<Object, Object>) (i_5) -> { return ( ((Boolean) ((((int) (i_5)) <= ((int) (0))))) ? Data_Maybe.__singleton$Nothing.value : new Data_Maybe.Just(new Data_Tuple.Tuple(m_4, (((int) (i_5)) - ((int) (1)))))); }))).apply(n_3)); }; }; }; }; };
public static final Object none = (java.util.function.Function<Object, Object>) (dictUnfoldable_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictUnfoldable_0).get("unfoldr"))).apply((java.util.function.Function<Object, Object>) (v_1) -> { return Data_Maybe.__singleton$Nothing.value; }))).apply(Data_Unit.unit); };
public static final Object fromMaybe = (java.util.function.Function<Object, Object>) (dictUnfoldable_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictUnfoldable_0).get("unfoldr"))).apply((java.util.function.Function<Object, Object>) (b_1) -> { return ( ((Boolean) ((b_1 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(new Data_Tuple.Tuple(((Data_Maybe.Just) (Object)(b_1)).value0, Data_Maybe.__singleton$Nothing.value)) : Data_Maybe.__singleton$Nothing.value); }); };
}
