public class Data_Identity {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Identity"); }
    };


public static final Object Identity = (java.util.function.Function<Object, Object>) (x_0) -> { return x_0; };
public static final Object showIdentity = (java.util.function.Function<Object, Object>) (dictShow_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (((String) ((((String) ("(Identity ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); };
public static final Object semiringIdentity = (java.util.function.Function<Object, Object>) (dictSemiring_0) -> { return dictSemiring_0; };
public static final Object semigroupIdentity = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> { return dictSemigroup_0; };
public static final Object ringIdentity = (java.util.function.Function<Object, Object>) (dictRing_0) -> { return dictRing_0; };
public static final Object ordIdentity = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return dictOrd_0; };
public static final Object newtypeIdentity = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object monoidIdentity = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> { return dictMonoid_0; };
public static final Object lazyIdentity = (java.util.function.Function<Object, Object>) (dictLazy_0) -> { return dictLazy_0; };
public static final Object heytingAlgebraIdentity = (java.util.function.Function<Object, Object>) (dictHeytingAlgebra_0) -> { return dictHeytingAlgebra_0; };
public static final Object functorIdentity = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (m_1) -> { return ((java.util.function.Function<Object, Object>) (f_0)).apply(m_1); }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get();
public static final Object invariantIdentity = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (Data_Functor_Invariant.imapF)).apply(Data_Identity.functorIdentity); return new __Record$69_6d_61_70_O(new String[]{"imap"}, __field0); } }).get();
public static final Object extendIdentity = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (m_1) -> { return ((java.util.function.Function<Object, Object>) (f_0)).apply(m_1); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Identity.functorIdentity; }; return new __Record$46_75_6e_63_74_6f_72_30_O$65_78_74_65_6e_64_O(new String[]{"extend", "Functor0"}, __field1, __field0); } }).get();
public static final Object euclideanRingIdentity = (java.util.function.Function<Object, Object>) (dictEuclideanRing_0) -> { return dictEuclideanRing_0; };
public static final Object eqIdentity = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return dictEq_0; };
public static final Object eq1Identity = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return ((java.util.function.Function<Object, Object>) (Data_Eq.eq)).apply(dictEq_0); }; return new __Record$65_71_31_O(new String[]{"eq1"}, __field0); } }).get();
public static final Object ord1Identity = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return ((java.util.function.Function<Object, Object>) (Data_Ord.compare)).apply(dictOrd_0); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Identity.eq1Identity; }; return new __Record$45_71_31_30_O$63_6f_6d_70_61_72_65_31_O(new String[]{"compare1", "Eq10"}, __field1, __field0); } }).get();
public static final Object comonadIdentity = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return v_0; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Identity.extendIdentity; }; return new __Record$45_78_74_65_6e_64_30_O$65_78_74_72_61_63_74_O(new String[]{"extract", "Extend0"}, __field1, __field0); } }).get();
public static final Object commutativeRingIdentity = (java.util.function.Function<Object, Object>) (dictCommutativeRing_0) -> { return dictCommutativeRing_0; };
public static final Object boundedIdentity = (java.util.function.Function<Object, Object>) (dictBounded_0) -> { return dictBounded_0; };
public static final Object booleanAlgebraIdentity = (java.util.function.Function<Object, Object>) (dictBooleanAlgebra_0) -> { return dictBooleanAlgebra_0; };
public static final Object applyIdentity = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return ((java.util.function.Function<Object, Object>) (v_0)).apply(v1_1); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Identity.functorIdentity; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get();
public static final Object bindIdentity = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (f_1) -> { return ((java.util.function.Function<Object, Object>) (f_1)).apply(v_0); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Identity.applyIdentity; }; return new __Record$41_70_70_6c_79_30_O$62_69_6e_64_O(new String[]{"bind", "Apply0"}, __field1, __field0); } }).get();
public static final Object applicativeIdentity = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = Data_Identity.Identity; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Identity.applyIdentity; }; return new __Record$41_70_70_6c_79_30_O$70_75_72_65_O(new String[]{"pure", "Apply0"}, __field1, __field0); } }).get();
public static final Object monadIdentity = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Identity.applicativeIdentity; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Identity.bindIdentity; }; return new __Record$41_70_70_6c_69_63_61_74_69_76_65_30_O$42_69_6e_64_31_O(new String[]{"Applicative0", "Bind1"}, __field0, __field1); } }).get();
public static final Object altIdentity = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return x_0; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Identity.functorIdentity; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_6c_74_O(new String[]{"alt", "Functor0"}, __field1, __field0); } }).get();
}
