public class Data_Ord_Down {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Ord.Down"); }
    };


public static final Object Down = (java.util.function.Function<Object, Object>) (x_0) -> { return x_0; };
public static final Object showDown = (java.util.function.Function<Object, Object>) (dictShow_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (((String) ((((String) ("(Down ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); };
public static final Object newtypeDown = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object eqDown = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return dictEq_0; };
public static final Object ordDown = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { Object eqDown1_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("Eq0"))).apply(null /* TODO: PrimUndefined */); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { Object __local_var_4 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(v_2))).apply(v1_3); return ( ((Boolean) ((__local_var_4 instanceof Data_Ordering.GT))) ? Data_Ordering.__singleton$LT.value : ( ((Boolean) ((__local_var_4 instanceof Data_Ordering.EQ))) ? Data_Ordering.__singleton$EQ.value : ( ((Boolean) ((__local_var_4 instanceof Data_Ordering.LT))) ? Data_Ordering.__singleton$GT.value : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return eqDown1_1; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get(); };
public static final Object boundedDown = (java.util.function.Function<Object, Object>) (dictBounded_0) -> { Object ordDown1_1 = ((java.util.function.Function<Object, Object>) (Data_Ord_Down.ordDown)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBounded_0).get("Ord0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.Map<String, Object>) dictBounded_0).get("bottom"); final Object __field1 = ((java.util.Map<String, Object>) dictBounded_0).get("top"); final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return ordDown1_1; }; return new __Record$4f_72_64_30_O$62_6f_74_74_6f_6d_O$74_6f_70_O(new String[]{"top", "bottom", "Ord0"}, __field2, __field1, __field0); } }).get(); };
}
