public class Data_Function {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Function"); }
    };


public static final Object on = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (g_1) -> { return (java.util.function.Function<Object, Object>) (x_2) -> { return (java.util.function.Function<Object, Object>) (y_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_0)).apply(((java.util.function.Function<Object, Object>) (g_1)).apply(x_2)))).apply(((java.util.function.Function<Object, Object>) (g_1)).apply(y_3)); }; }; }; };
public static final Object flip = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (b_1) -> { return (java.util.function.Function<Object, Object>) (a_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_0)).apply(a_2))).apply(b_1); }; }; };
public static final Object $const = (java.util.function.Function<Object, Object>) (a_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return a_0; }; };
public static final Object applyN = (java.util.function.Function<Object, Object>) (f_0) -> { Object go__go_1 = (java.util.function.Function<Object, Object>) (n_2) -> (java.util.function.Function<Object, Object>) (acc_3) -> { int __tco_n_2 = ((int) (n_2)); Object __tco_acc_3 = acc_3; while(true) { final int __final_n_2 = __tco_n_2; final Object __final_acc_3 = __tco_acc_3; try { if ((Boolean) ((((int) (__final_n_2)) <= ((int) (0))))) { return __final_acc_3; } else { { final int __next_n_2 = ((int) ((((int) (__final_n_2)) - ((int) (1))))); final Object __next_acc_3 = ((java.util.function.Function<Object, Object>) (f_0)).apply(__final_acc_3); __tco_n_2 = __next_n_2; __tco_acc_3 = __next_acc_3; continue; } } } catch (TcoLoop __tco_ex) { __tco_n_2 = ((int) (__tco_ex.args[0])); __tco_acc_3 = __tco_ex.args[1]; } } }; return go__go_1; };
public static final Object applyFlipped = (java.util.function.Function<Object, Object>) (x_0) -> { return (java.util.function.Function<Object, Object>) (f_1) -> { return ((java.util.function.Function<Object, Object>) (f_1)).apply(x_0); }; };
public static final Object apply = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (x_1) -> { return ((java.util.function.Function<Object, Object>) (f_0)).apply(x_1); }; };
}
