public class Data_Divide {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Divide"); }
    };


public static final Object dividePredicate = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return (java.util.function.Function<Object, Object>) (a_3) -> { Object v2_4 = ((java.util.function.Function<Object, Object>) (f_0)).apply(a_3); return (((Boolean) (((java.util.function.Function<Object, Object>) (v_1)).apply(((Data_Tuple.Tuple) (Object)(v2_4)).value0))) && ((Boolean) (((java.util.function.Function<Object, Object>) (v1_2)).apply(((Data_Tuple.Tuple) (Object)(v2_4)).value1)))); }; }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Predicate.contravariantPredicate; }; return new __Record$43_6f_6e_74_72_61_76_61_72_69_61_6e_74_30_O$64_69_76_69_64_65_O(new String[]{"divide", "Contravariant0"}, __field1, __field0); } }).get();
public static final Object divideOp = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { return (java.util.function.Function<Object, Object>) (a_4) -> { Object v2_5 = ((java.util.function.Function<Object, Object>) (f_1)).apply(a_4); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictSemigroup_0).get("append"))).apply(((java.util.function.Function<Object, Object>) (v_2)).apply(((Data_Tuple.Tuple) (Object)(v2_5)).value0)))).apply(((java.util.function.Function<Object, Object>) (v1_3)).apply(((Data_Tuple.Tuple) (Object)(v2_5)).value1)); }; }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> { return Data_Op.contravariantOp; }; return new __Record$43_6f_6e_74_72_61_76_61_72_69_61_6e_74_30_O$64_69_76_69_64_65_O(new String[]{"divide", "Contravariant0"}, __field1, __field0); } }).get(); };
public static final Object divideEquivalence = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return (java.util.function.Function<Object, Object>) (a_3) -> { return (java.util.function.Function<Object, Object>) (b_4) -> { Object v2_5 = ((java.util.function.Function<Object, Object>) (f_0)).apply(a_3); Object v3_6 = ((java.util.function.Function<Object, Object>) (f_0)).apply(b_4); return (((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v_1)).apply(((Data_Tuple.Tuple) (Object)(v2_5)).value0))).apply(((Data_Tuple.Tuple) (Object)(v3_6)).value0))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v1_2)).apply(((Data_Tuple.Tuple) (Object)(v2_5)).value1))).apply(((Data_Tuple.Tuple) (Object)(v3_6)).value1)))); }; }; }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Equivalence.contravariantEquivalence; }; return new __Record$43_6f_6e_74_72_61_76_61_72_69_61_6e_74_30_O$64_69_76_69_64_65_O(new String[]{"divide", "Contravariant0"}, __field1, __field0); } }).get();
public static final Object divideComparison = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return (java.util.function.Function<Object, Object>) (a_3) -> { return (java.util.function.Function<Object, Object>) (b_4) -> { Object v2_5 = ((java.util.function.Function<Object, Object>) (f_0)).apply(a_3); Object v3_6 = ((java.util.function.Function<Object, Object>) (f_0)).apply(b_4); Object __local_var_7 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v_1)).apply(((Data_Tuple.Tuple) (Object)(v2_5)).value0))).apply(((Data_Tuple.Tuple) (Object)(v3_6)).value0); Object __local_var_8 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v1_2)).apply(((Data_Tuple.Tuple) (Object)(v2_5)).value1))).apply(((Data_Tuple.Tuple) (Object)(v3_6)).value1); return ( ((Boolean) ((__local_var_7 instanceof Data_Ordering.LT))) ? Data_Ordering.__singleton$LT.value : ( ((Boolean) ((__local_var_7 instanceof Data_Ordering.GT))) ? Data_Ordering.__singleton$GT.value : ( ((Boolean) ((__local_var_7 instanceof Data_Ordering.EQ))) ? __local_var_8 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }; }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Comparison.contravariantComparison; }; return new __Record$43_6f_6e_74_72_61_76_61_72_69_61_6e_74_30_O$64_69_76_69_64_65_O(new String[]{"divide", "Contravariant0"}, __field1, __field0); } }).get();
public static final Object divide = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("divide"); };
public static final Object divided = (java.util.function.Function<Object, Object>) (dictDivide_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictDivide_0).get("divide"))).apply(((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn)); };
}
