public class Data_Maybe {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Maybe"); }
    };


public static final class Nothing {
            
            public Nothing() {
                
            }
        }
public static final class __singleton$Nothing {
    public static final Nothing value = new Nothing();
}
public static final class Just {
            public final Object value0;
            public Just(Object value0) {
                this.value0 = value0;
            }
        }
public static final Object Nothing = Data_Maybe.__singleton$Nothing.value;
public static final Object Just = (java.util.function.Function<Object, Object>) (value0) -> { return new Data_Maybe.Just(value0); };
public static final Object showMaybe = (java.util.function.Function<Object, Object>) (dictShow_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return ( ((Boolean) ((v_1 instanceof Data_Maybe.Just))) ? (((String) ((((String) ("(Just ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0).get("show"))).apply(((Data_Maybe.Just) (Object)(v_1)).value0)))))) + ((String) (")"))) : ( ((Boolean) ((v_1 instanceof Data_Maybe.Nothing))) ? "Nothing" : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); };
public static final Object semigroupMaybe = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ( ((Boolean) ((v_1 instanceof Data_Maybe.Nothing))) ? v1_2 : ( ((Boolean) ((v1_2 instanceof Data_Maybe.Nothing))) ? v_1 : ( ((Boolean) ((((Boolean) ((v_1 instanceof Data_Maybe.Just))) && ((Boolean) ((v1_2 instanceof Data_Maybe.Just)))))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictSemigroup_0).get("append"))).apply(((Data_Maybe.Just) (Object)(v_1)).value0))).apply(((Data_Maybe.Just) (Object)(v1_2)).value0)) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get(); };
public static final Object optional = (java.util.function.Function<Object, Object>) (dictAlt_0) -> { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictAlt_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (dictApplicative_2) -> { return (java.util.function.Function<Object, Object>) (a_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictAlt_0).get("alt"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1).get("map"))).apply(Data_Maybe.Just))).apply(a_3)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_2).get("pure"))).apply(Data_Maybe.__singleton$Nothing.value)); }; }; };
public static final Object monoidMaybe = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> { Object semigroupMaybe1_1 = ((java.util.function.Function<Object, Object>) (Data_Maybe.semigroupMaybe)).apply(dictSemigroup_0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = Data_Maybe.__singleton$Nothing.value; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return semigroupMaybe1_1; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get(); };
public static final Object maybeprime = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return (java.util.function.Function<Object, Object>) (v2_2) -> { return ( ((Boolean) ((v2_2 instanceof Data_Maybe.Nothing))) ? ((java.util.function.Function<Object, Object>) (v_0)).apply(Data_Unit.unit) : ( ((Boolean) ((v2_2 instanceof Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (v1_1)).apply(((Data_Maybe.Just) (Object)(v2_2)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }; };
public static final Object maybe = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return (java.util.function.Function<Object, Object>) (v2_2) -> { return ( ((Boolean) ((v2_2 instanceof Data_Maybe.Nothing))) ? v_0 : ( ((Boolean) ((v2_2 instanceof Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (v1_1)).apply(((Data_Maybe.Just) (Object)(v2_2)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }; };
public static final Object isNothing = (java.util.function.Function<Object, Object>) (v2_0) -> { return ( ((Boolean) ((v2_0 instanceof Data_Maybe.Nothing))) ? true : ( ((Boolean) ((v2_0 instanceof Data_Maybe.Just))) ? false : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); };
public static final Object isJust = (java.util.function.Function<Object, Object>) (v2_0) -> { return ( ((Boolean) ((v2_0 instanceof Data_Maybe.Nothing))) ? false : ( ((Boolean) ((v2_0 instanceof Data_Maybe.Just))) ? true : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); };
public static final Object genericMaybe = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_0) -> { return ( ((Boolean) ((x_0 instanceof Data_Generic_Rep.Inl))) ? Data_Maybe.__singleton$Nothing.value : ( ((Boolean) ((x_0 instanceof Data_Generic_Rep.Inr))) ? new Data_Maybe.Just(((Data_Generic_Rep.Inr) (Object)(x_0)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; final Object __field1 = (java.util.function.Function<Object, Object>) (x_0) -> { return ( ((Boolean) ((x_0 instanceof Data_Maybe.Nothing))) ? new Data_Generic_Rep.Inl(Data_Generic_Rep.__singleton$NoArguments.value) : ( ((Boolean) ((x_0 instanceof Data_Maybe.Just))) ? new Data_Generic_Rep.Inr(((Data_Maybe.Just) (Object)(x_0)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; return new __Record$66_72_6f_6d_O$74_6f_O(new String[]{"to", "from"}, __field1, __field0); } }).get();
public static final Object functorMaybe = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return ( ((Boolean) ((v1_1 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (v_0)).apply(((Data_Maybe.Just) (Object)(v1_1)).value0)) : Data_Maybe.__singleton$Nothing.value); }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get();
public static final Object invariantMaybe = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (Data_Functor_Invariant.imapF)).apply(Data_Maybe.functorMaybe); return new __Record$69_6d_61_70_O(new String[]{"imap"}, __field0); } }).get();
public static final Object fromMaybeprime = (java.util.function.Function<Object, Object>) (a_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Maybe.maybeprime)).apply(a_0))).apply(((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn)); };
public static final Object fromMaybe = (java.util.function.Function<Object, Object>) (a_0) -> { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn); return (java.util.function.Function<Object, Object>) (v2_2) -> { return ( ((Boolean) ((v2_2 instanceof Data_Maybe.Nothing))) ? a_0 : ( ((Boolean) ((v2_2 instanceof Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (__local_var_1)).apply(((Data_Maybe.Just) (Object)(v2_2)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; };
public static final Object fromJust = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return ( ((Boolean) ((v_1 instanceof Data_Maybe.Just))) ? ((Data_Maybe.Just) (Object)(v_1)).value0 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()); }; };
public static final Object extendMaybe = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return ( ((Boolean) ((v1_1 instanceof Data_Maybe.Nothing))) ? Data_Maybe.__singleton$Nothing.value : new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (v_0)).apply(v1_1))); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Maybe.functorMaybe; }; return new __Record$46_75_6e_63_74_6f_72_30_O$65_78_74_65_6e_64_O(new String[]{"extend", "Functor0"}, __field1, __field0); } }).get();
public static final Object eqMaybe = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_1) -> { return (java.util.function.Function<Object, Object>) (y_2) -> { return ( ((Boolean) ((x_1 instanceof Data_Maybe.Nothing))) ? (y_2 instanceof Data_Maybe.Nothing) : (((Boolean) ((x_1 instanceof Data_Maybe.Just))) && ((Boolean) ((((Boolean) ((y_2 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEq_0).get("eq"))).apply(((Data_Maybe.Just) (Object)(x_1)).value0))).apply(((Data_Maybe.Just) (Object)(y_2)).value0)))))))); }; }; return new __Record$65_71_O(new String[]{"eq"}, __field0); } }).get(); };
public static final Object ordMaybe = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { Object eqMaybe1_1 = ((java.util.function.Function<Object, Object>) (Data_Maybe.eqMaybe)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("Eq0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_2) -> { return (java.util.function.Function<Object, Object>) (y_3) -> { return ( ((Boolean) ((x_2 instanceof Data_Maybe.Nothing))) ? ( ((Boolean) ((y_3 instanceof Data_Maybe.Nothing))) ? Data_Ordering.__singleton$EQ.value : Data_Ordering.__singleton$LT.value) : ( ((Boolean) ((y_3 instanceof Data_Maybe.Nothing))) ? Data_Ordering.__singleton$GT.value : ( ((Boolean) ((((Boolean) ((x_2 instanceof Data_Maybe.Just))) && ((Boolean) ((y_3 instanceof Data_Maybe.Just)))))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(((Data_Maybe.Just) (Object)(x_2)).value0))).apply(((Data_Maybe.Just) (Object)(y_3)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return eqMaybe1_1; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get(); };
public static final Object eq1Maybe = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return ((java.util.function.Function<Object, Object>) (Data_Eq.eq)).apply(((java.util.function.Function<Object, Object>) (Data_Maybe.eqMaybe)).apply(dictEq_0)); }; return new __Record$65_71_31_O(new String[]{"eq1"}, __field0); } }).get();
public static final Object ord1Maybe = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return ((java.util.function.Function<Object, Object>) (Data_Ord.compare)).apply(((java.util.function.Function<Object, Object>) (Data_Maybe.ordMaybe)).apply(dictOrd_0)); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Maybe.eq1Maybe; }; return new __Record$45_71_31_30_O$63_6f_6d_70_61_72_65_31_O(new String[]{"compare1", "Eq10"}, __field1, __field0); } }).get();
public static final Object boundedMaybe = (java.util.function.Function<Object, Object>) (dictBounded_0) -> { Object ordMaybe1_1 = ((java.util.function.Function<Object, Object>) (Data_Maybe.ordMaybe)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBounded_0).get("Ord0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = new Data_Maybe.Just(((java.util.Map<String, Object>) dictBounded_0).get("top")); final Object __field1 = Data_Maybe.__singleton$Nothing.value; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return ordMaybe1_1; }; return new __Record$4f_72_64_30_O$62_6f_74_74_6f_6d_O$74_6f_70_O(new String[]{"top", "bottom", "Ord0"}, __field2, __field1, __field0); } }).get(); };
public static final Object applyMaybe = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return ( ((Boolean) ((v_0 instanceof Data_Maybe.Just))) ? ( ((Boolean) ((v1_1 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((Data_Maybe.Just) (Object)(v_0)).value0)).apply(((Data_Maybe.Just) (Object)(v1_1)).value0)) : Data_Maybe.__singleton$Nothing.value) : ( ((Boolean) ((v_0 instanceof Data_Maybe.Nothing))) ? Data_Maybe.__singleton$Nothing.value : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Maybe.functorMaybe; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get();
public static final Object bindMaybe = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return ( ((Boolean) ((v_0 instanceof Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (v1_1)).apply(((Data_Maybe.Just) (Object)(v_0)).value0) : ( ((Boolean) ((v_0 instanceof Data_Maybe.Nothing))) ? Data_Maybe.__singleton$Nothing.value : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Maybe.applyMaybe; }; return new __Record$41_70_70_6c_79_30_O$62_69_6e_64_O(new String[]{"bind", "Apply0"}, __field1, __field0); } }).get();
public static final Object semiringMaybe = (java.util.function.Function<Object, Object>) (dictSemiring_0) -> { Object mul_1 = ((java.util.function.Function<Object, Object>) (Data_Semiring.mul)).apply(dictSemiring_0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = Data_Maybe.__singleton$Nothing.value; final Object __field1 = new Data_Maybe.Just(((java.util.Map<String, Object>) dictSemiring_0).get("one")); final Object __field2 = (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { return ( ((Boolean) ((v_2 instanceof Data_Maybe.Nothing))) ? v1_3 : ( ((Boolean) ((v1_3 instanceof Data_Maybe.Nothing))) ? v_2 : ( ((Boolean) ((((Boolean) ((v_2 instanceof Data_Maybe.Just))) && ((Boolean) ((v1_3 instanceof Data_Maybe.Just)))))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictSemiring_0).get("add"))).apply(((Data_Maybe.Just) (Object)(v_2)).value0))).apply(((Data_Maybe.Just) (Object)(v1_3)).value0)) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }; final Object __field3 = (java.util.function.Function<Object, Object>) (x_2) -> { return (java.util.function.Function<Object, Object>) (y_3) -> { return ( ((Boolean) ((x_2 instanceof Data_Maybe.Just))) ? ( ((Boolean) ((y_3 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (mul_1)).apply(((Data_Maybe.Just) (Object)(x_2)).value0))).apply(((Data_Maybe.Just) (Object)(y_3)).value0)) : Data_Maybe.__singleton$Nothing.value) : Data_Maybe.__singleton$Nothing.value); }; }; return new __Record$61_64_64_O$6d_75_6c_O$6f_6e_65_O$7a_65_72_6f_O(new String[]{"zero", "one", "add", "mul"}, __field2, __field3, __field1, __field0); } }).get(); };
public static final Object applicativeMaybe = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = Data_Maybe.Just; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Maybe.applyMaybe; }; return new __Record$41_70_70_6c_79_30_O$70_75_72_65_O(new String[]{"pure", "Apply0"}, __field1, __field0); } }).get();
public static final Object monadMaybe = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Maybe.applicativeMaybe; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Maybe.bindMaybe; }; return new __Record$41_70_70_6c_69_63_61_74_69_76_65_30_O$42_69_6e_64_31_O(new String[]{"Applicative0", "Bind1"}, __field0, __field1); } }).get();
public static final Object altMaybe = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return ( ((Boolean) ((v_0 instanceof Data_Maybe.Nothing))) ? v1_1 : v_0); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Maybe.functorMaybe; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_6c_74_O(new String[]{"alt", "Functor0"}, __field1, __field0); } }).get();
public static final Object plusMaybe = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = Data_Maybe.__singleton$Nothing.value; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Maybe.altMaybe; }; return new __Record$41_6c_74_30_O$65_6d_70_74_79_O(new String[]{"empty", "Alt0"}, __field1, __field0); } }).get();
public static final Object alternativeMaybe = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Maybe.applicativeMaybe; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Maybe.plusMaybe; }; return new __Record$41_70_70_6c_69_63_61_74_69_76_65_30_O$50_6c_75_73_31_O(new String[]{"Applicative0", "Plus1"}, __field0, __field1); } }).get();
}
