public class Data_Functor_Product2 {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Functor.Product2"); }
    };


public static final class Product2 {
            public final Object value0;
            public final Object value1;
            public Product2(Object value0, Object value1) {
                this.value0 = value0;
                this.value1 = value1;
            }
        }
public static final Object Product2 = (java.util.function.Function<Object, Object>) (value0) -> (java.util.function.Function<Object, Object>) (value1) -> { return new Data_Functor_Product2.Product2(value0, value1); };
public static final Object showProduct2 = (java.util.function.Function<Object, Object>) (dictShow_0) -> { return (java.util.function.Function<Object, Object>) (dictShow1_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return (((String) ((((String) ((((String) ((((String) ("(Product2 ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0).get("show"))).apply(((Data_Functor_Product2.Product2) (Object)(v_2)).value0)))))) + ((String) (" "))))) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow1_1).get("show"))).apply(((Data_Functor_Product2.Product2) (Object)(v_2)).value1)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); }; };
public static final Object profunctorProduct2 = (java.util.function.Function<Object, Object>) (dictProfunctor_0) -> { return (java.util.function.Function<Object, Object>) (dictProfunctor1_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_2) -> { return (java.util.function.Function<Object, Object>) (g_3) -> { return (java.util.function.Function<Object, Object>) (v_4) -> { return new Data_Functor_Product2.Product2(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictProfunctor_0).get("dimap"))).apply(f_2))).apply(g_3))).apply(((Data_Functor_Product2.Product2) (Object)(v_4)).value0), ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictProfunctor1_1).get("dimap"))).apply(f_2))).apply(g_3))).apply(((Data_Functor_Product2.Product2) (Object)(v_4)).value1)); }; }; }; return new __Record$64_69_6d_61_70_O(new String[]{"dimap"}, __field0); } }).get(); }; };
public static final Object functorProduct2 = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> { return (java.util.function.Function<Object, Object>) (dictFunctor1_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_2) -> { return (java.util.function.Function<Object, Object>) (v_3) -> { return new Data_Functor_Product2.Product2(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0).get("map"))).apply(f_2))).apply(((Data_Functor_Product2.Product2) (Object)(v_3)).value0), ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor1_1).get("map"))).apply(f_2))).apply(((Data_Functor_Product2.Product2) (Object)(v_3)).value1)); }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get(); }; };
public static final Object eqProduct2 = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return (java.util.function.Function<Object, Object>) (dictEq1_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_2) -> { return (java.util.function.Function<Object, Object>) (y_3) -> { return (((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEq_0).get("eq"))).apply(((Data_Functor_Product2.Product2) (Object)(x_2)).value0))).apply(((Data_Functor_Product2.Product2) (Object)(y_3)).value0))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEq1_1).get("eq"))).apply(((Data_Functor_Product2.Product2) (Object)(x_2)).value1))).apply(((Data_Functor_Product2.Product2) (Object)(y_3)).value1)))); }; }; return new __Record$65_71_O(new String[]{"eq"}, __field0); } }).get(); }; };
public static final Object ordProduct2 = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { Object eqProduct21_1 = ((java.util.function.Function<Object, Object>) (Data_Functor_Product2.eqProduct2)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("Eq0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictOrd1_2) -> { Object eqProduct22_3 = ((java.util.function.Function<Object, Object>) (eqProduct21_1)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd1_2).get("Eq0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_4) -> { return (java.util.function.Function<Object, Object>) (y_5) -> { Object v_6 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(((Data_Functor_Product2.Product2) (Object)(x_4)).value0))).apply(((Data_Functor_Product2.Product2) (Object)(y_5)).value0); return ( ((Boolean) ((v_6 instanceof Data_Ordering.LT))) ? Data_Ordering.__singleton$LT.value : ( ((Boolean) ((v_6 instanceof Data_Ordering.GT))) ? Data_Ordering.__singleton$GT.value : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd1_2).get("compare"))).apply(((Data_Functor_Product2.Product2) (Object)(x_4)).value1))).apply(((Data_Functor_Product2.Product2) (Object)(y_5)).value1))); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_4) -> { return eqProduct22_3; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get(); }; };
public static final Object bifunctorProduct2 = (java.util.function.Function<Object, Object>) (dictBifunctor_0) -> { return (java.util.function.Function<Object, Object>) (dictBifunctor1_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_2) -> { return (java.util.function.Function<Object, Object>) (g_3) -> { return (java.util.function.Function<Object, Object>) (v_4) -> { return new Data_Functor_Product2.Product2(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBifunctor_0).get("bimap"))).apply(f_2))).apply(g_3))).apply(((Data_Functor_Product2.Product2) (Object)(v_4)).value0), ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBifunctor1_1).get("bimap"))).apply(f_2))).apply(g_3))).apply(((Data_Functor_Product2.Product2) (Object)(v_4)).value1)); }; }; }; return new __Record$62_69_6d_61_70_O(new String[]{"bimap"}, __field0); } }).get(); }; };
public static final Object biapplyProduct2 = (java.util.function.Function<Object, Object>) (dictBiapply_0) -> { Object bifunctorProduct21_1 = ((java.util.function.Function<Object, Object>) (Data_Functor_Product2.bifunctorProduct2)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapply_0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictBiapply1_2) -> { Object bifunctorProduct22_3 = ((java.util.function.Function<Object, Object>) (bifunctorProduct21_1)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapply1_2).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_4) -> { return (java.util.function.Function<Object, Object>) (v1_5) -> { return new Data_Functor_Product2.Product2(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapply_0).get("biapply"))).apply(((Data_Functor_Product2.Product2) (Object)(v_4)).value0))).apply(((Data_Functor_Product2.Product2) (Object)(v1_5)).value0), ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapply1_2).get("biapply"))).apply(((Data_Functor_Product2.Product2) (Object)(v_4)).value1))).apply(((Data_Functor_Product2.Product2) (Object)(v1_5)).value1)); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_4) -> { return bifunctorProduct22_3; }; return new __Record$42_69_66_75_6e_63_74_6f_72_30_O$62_69_61_70_70_6c_79_O(new String[]{"biapply", "Bifunctor0"}, __field1, __field0); } }).get(); }; };
public static final Object biapplicativeProduct2 = (java.util.function.Function<Object, Object>) (dictBiapplicative_0) -> { Object biapplyProduct21_1 = ((java.util.function.Function<Object, Object>) (Data_Functor_Product2.biapplyProduct2)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapplicative_0).get("Biapply0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictBiapplicative1_2) -> { Object biapplyProduct22_3 = ((java.util.function.Function<Object, Object>) (biapplyProduct21_1)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapplicative1_2).get("Biapply0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (a_4) -> { return (java.util.function.Function<Object, Object>) (b_5) -> { return new Data_Functor_Product2.Product2(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapplicative_0).get("bipure"))).apply(a_4))).apply(b_5), ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapplicative1_2).get("bipure"))).apply(a_4))).apply(b_5)); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_4) -> { return biapplyProduct22_3; }; return new __Record$42_69_61_70_70_6c_79_30_O$62_69_70_75_72_65_O(new String[]{"bipure", "Biapply0"}, __field1, __field0); } }).get(); }; };
}
