public class Data_Op {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Op"); }
    };


public static final Object Op = (java.util.function.Function<Object, Object>) (x_0) -> { return x_0; };
public static final Object semigroupoidOp = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(v1_1))).apply(v_0); }; }; return new __Record$63_6f_6d_70_6f_73_65_O(new String[]{"compose"}, __field0); } }).get();
public static final Object semigroupOp = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> { return ((java.util.function.Function<Object, Object>) (Data_Semigroup.semigroupFn)).apply(dictSemigroup_0); };
public static final Object newtypeOp = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object monoidOp = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> { return ((java.util.function.Function<Object, Object>) (Data_Monoid.monoidFn)).apply(dictMonoid_0); };
public static final Object contravariantOp = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(v_1))).apply(f_0); }; }; return new __Record$63_6d_61_70_O(new String[]{"cmap"}, __field0); } }).get();
public static final Object categoryOp = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Op.semigroupoidOp; }; return new __Record$53_65_6d_69_67_72_6f_75_70_6f_69_64_30_O$69_64_65_6e_74_69_74_79_O(new String[]{"identity", "Semigroupoid0"}, __field1, __field0); } }).get();
}
