public class Data_Bounded_Generic {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Bounded.Generic"); }
    };


public static final Object genericTopNoArguments = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = Data_Generic_Rep.__singleton$NoArguments.value; return new __Record$67_65_6e_65_72_69_63_54_6f_70_27_O(new String[]{"genericTop'"}, __field0); } }).get();
public static final Object genericTopArgument = (java.util.function.Function<Object, Object>) (dictBounded_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.Map<String, Object>) dictBounded_0).get("top"); return new __Record$67_65_6e_65_72_69_63_54_6f_70_27_O(new String[]{"genericTop'"}, __field0); } }).get(); };
public static final Object genericTopprime = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("genericTop'"); };
public static final Object genericTopConstructor = (java.util.function.Function<Object, Object>) (dictGenericTop_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.Map<String, Object>) dictGenericTop_0).get("genericTop'"); return new __Record$67_65_6e_65_72_69_63_54_6f_70_27_O(new String[]{"genericTop'"}, __field0); } }).get(); };
public static final Object genericTopProduct = (java.util.function.Function<Object, Object>) (dictGenericTop_0) -> { return (java.util.function.Function<Object, Object>) (dictGenericTop1_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = new Data_Generic_Rep.Product(((java.util.Map<String, Object>) dictGenericTop_0).get("genericTop'"), ((java.util.Map<String, Object>) dictGenericTop1_1).get("genericTop'")); return new __Record$67_65_6e_65_72_69_63_54_6f_70_27_O(new String[]{"genericTop'"}, __field0); } }).get(); }; };
public static final Object genericTopSum = (java.util.function.Function<Object, Object>) (dictGenericTop_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = new Data_Generic_Rep.Inr(((java.util.Map<String, Object>) dictGenericTop_0).get("genericTop'")); return new __Record$67_65_6e_65_72_69_63_54_6f_70_27_O(new String[]{"genericTop'"}, __field0); } }).get(); };
public static final Object genericTop = (java.util.function.Function<Object, Object>) (dictGeneric_0) -> { return (java.util.function.Function<Object, Object>) (dictGenericTop_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0).get("to"))).apply(((java.util.Map<String, Object>) dictGenericTop_1).get("genericTop'")); }; };
public static final Object genericBottomNoArguments = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = Data_Generic_Rep.__singleton$NoArguments.value; return new __Record$67_65_6e_65_72_69_63_42_6f_74_74_6f_6d_27_O(new String[]{"genericBottom'"}, __field0); } }).get();
public static final Object genericBottomArgument = (java.util.function.Function<Object, Object>) (dictBounded_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.Map<String, Object>) dictBounded_0).get("bottom"); return new __Record$67_65_6e_65_72_69_63_42_6f_74_74_6f_6d_27_O(new String[]{"genericBottom'"}, __field0); } }).get(); };
public static final Object genericBottomprime = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("genericBottom'"); };
public static final Object genericBottomConstructor = (java.util.function.Function<Object, Object>) (dictGenericBottom_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.Map<String, Object>) dictGenericBottom_0).get("genericBottom'"); return new __Record$67_65_6e_65_72_69_63_42_6f_74_74_6f_6d_27_O(new String[]{"genericBottom'"}, __field0); } }).get(); };
public static final Object genericBottomProduct = (java.util.function.Function<Object, Object>) (dictGenericBottom_0) -> { return (java.util.function.Function<Object, Object>) (dictGenericBottom1_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = new Data_Generic_Rep.Product(((java.util.Map<String, Object>) dictGenericBottom_0).get("genericBottom'"), ((java.util.Map<String, Object>) dictGenericBottom1_1).get("genericBottom'")); return new __Record$67_65_6e_65_72_69_63_42_6f_74_74_6f_6d_27_O(new String[]{"genericBottom'"}, __field0); } }).get(); }; };
public static final Object genericBottomSum = (java.util.function.Function<Object, Object>) (dictGenericBottom_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = new Data_Generic_Rep.Inl(((java.util.Map<String, Object>) dictGenericBottom_0).get("genericBottom'")); return new __Record$67_65_6e_65_72_69_63_42_6f_74_74_6f_6d_27_O(new String[]{"genericBottom'"}, __field0); } }).get(); };
public static final Object genericBottom = (java.util.function.Function<Object, Object>) (dictGeneric_0) -> { return (java.util.function.Function<Object, Object>) (dictGenericBottom_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0).get("to"))).apply(((java.util.Map<String, Object>) dictGenericBottom_1).get("genericBottom'")); }; };
}
