public class Data_Either {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Either"); }
    };


public static final class Left {
            public final Object value0;
            public Left(Object value0) {
                this.value0 = value0;
            }
        }
public static final class Right {
            public final Object value0;
            public Right(Object value0) {
                this.value0 = value0;
            }
        }
public static final Object Left = (java.util.function.Function<Object, Object>) (value0) -> { return new Data_Either.Left(value0); };
public static final Object Right = (java.util.function.Function<Object, Object>) (value0) -> { return new Data_Either.Right(value0); };
public static final Object showEither = (java.util.function.Function<Object, Object>) (dictShow_0) -> { return (java.util.function.Function<Object, Object>) (dictShow1_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return ( ((Boolean) ((v_2 instanceof Data_Either.Left))) ? (((String) ((((String) ("(Left ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0).get("show"))).apply(((Data_Either.Left) (Object)(v_2)).value0)))))) + ((String) (")"))) : ( ((Boolean) ((v_2 instanceof Data_Either.Right))) ? (((String) ((((String) ("(Right ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow1_1).get("show"))).apply(((Data_Either.Right) (Object)(v_2)).value0)))))) + ((String) (")"))) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); }; };
public static final Object noteprime = (java.util.function.Function<Object, Object>) (f_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Maybe.maybeprime)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(Data_Either.Left))).apply(f_0)))).apply(Data_Either.Right); };
public static final Object note = (java.util.function.Function<Object, Object>) (a_0) -> { return (java.util.function.Function<Object, Object>) (v2_1) -> { return ( ((Boolean) ((v2_1 instanceof Data_Maybe.Nothing))) ? new Data_Either.Left(a_0) : ( ((Boolean) ((v2_1 instanceof Data_Maybe.Just))) ? new Data_Either.Right(((Data_Maybe.Just) (Object)(v2_1)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; };
public static final Object genericEither = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_0) -> { return ( ((Boolean) ((x_0 instanceof Data_Generic_Rep.Inl))) ? new Data_Either.Left(((Data_Generic_Rep.Inl) (Object)(x_0)).value0) : ( ((Boolean) ((x_0 instanceof Data_Generic_Rep.Inr))) ? new Data_Either.Right(((Data_Generic_Rep.Inr) (Object)(x_0)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; final Object __field1 = (java.util.function.Function<Object, Object>) (x_0) -> { return ( ((Boolean) ((x_0 instanceof Data_Either.Left))) ? new Data_Generic_Rep.Inl(((Data_Either.Left) (Object)(x_0)).value0) : ( ((Boolean) ((x_0 instanceof Data_Either.Right))) ? new Data_Generic_Rep.Inr(((Data_Either.Right) (Object)(x_0)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; return new __Record$66_72_6f_6d_O$74_6f_O(new String[]{"to", "from"}, __field1, __field0); } }).get();
public static final Object functorEither = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (m_1) -> { return ( ((Boolean) ((m_1 instanceof Data_Either.Left))) ? m_1 : ( ((Boolean) ((m_1 instanceof Data_Either.Right))) ? new Data_Either.Right(((java.util.function.Function<Object, Object>) (f_0)).apply(((Data_Either.Right) (Object)(m_1)).value0)) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get();
public static final Object invariantEither = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (Data_Functor_Invariant.imapF)).apply(Data_Either.functorEither); return new __Record$69_6d_61_70_O(new String[]{"imap"}, __field0); } }).get();
public static final Object fromRightprime = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return ( ((Boolean) ((v1_1 instanceof Data_Either.Right))) ? ((Data_Either.Right) (Object)(v1_1)).value0 : ((java.util.function.Function<Object, Object>) (v_0)).apply(Data_Unit.unit)); }; };
public static final Object fromRight = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return ( ((Boolean) ((v1_1 instanceof Data_Either.Right))) ? ((Data_Either.Right) (Object)(v1_1)).value0 : v_0); }; };
public static final Object fromLeftprime = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return ( ((Boolean) ((v1_1 instanceof Data_Either.Left))) ? ((Data_Either.Left) (Object)(v1_1)).value0 : ((java.util.function.Function<Object, Object>) (v_0)).apply(Data_Unit.unit)); }; };
public static final Object fromLeft = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return ( ((Boolean) ((v1_1 instanceof Data_Either.Left))) ? ((Data_Either.Left) (Object)(v1_1)).value0 : v_0); }; };
public static final Object extendEither = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return ( ((Boolean) ((v1_1 instanceof Data_Either.Left))) ? v1_1 : new Data_Either.Right(((java.util.function.Function<Object, Object>) (v_0)).apply(v1_1))); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Either.functorEither; }; return new __Record$46_75_6e_63_74_6f_72_30_O$65_78_74_65_6e_64_O(new String[]{"extend", "Functor0"}, __field1, __field0); } }).get();
public static final Object eqEither = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return (java.util.function.Function<Object, Object>) (dictEq1_1) -> { return Data_Either.__direct$15(dictEq_0, dictEq1_1); }; };
private static Object __direct$15(Object dictEq_0, Object dictEq1_1) { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_2) -> { return (java.util.function.Function<Object, Object>) (y_3) -> { return ( ((Boolean) ((x_2 instanceof Data_Either.Left))) ? (((Boolean) ((y_3 instanceof Data_Either.Left))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEq_0).get("eq"))).apply(((Data_Either.Left) (Object)(x_2)).value0))).apply(((Data_Either.Left) (Object)(y_3)).value0)))) : (((Boolean) ((x_2 instanceof Data_Either.Right))) && ((Boolean) ((((Boolean) ((y_3 instanceof Data_Either.Right))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEq1_1).get("eq"))).apply(((Data_Either.Right) (Object)(x_2)).value0))).apply(((Data_Either.Right) (Object)(y_3)).value0)))))))); }; }; return new __Record$65_71_O(new String[]{"eq"}, __field0); } }).get(); }
public static final Object ordEither = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { Object eqEither1_1 = ((java.util.function.Function<Object, Object>) (Data_Either.eqEither)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("Eq0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictOrd1_2) -> { Object eqEither2_3 = ((java.util.function.Function<Object, Object>) (eqEither1_1)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd1_2).get("Eq0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_4) -> { return (java.util.function.Function<Object, Object>) (y_5) -> { return ( ((Boolean) ((x_4 instanceof Data_Either.Left))) ? ( ((Boolean) ((y_5 instanceof Data_Either.Left))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(((Data_Either.Left) (Object)(x_4)).value0))).apply(((Data_Either.Left) (Object)(y_5)).value0) : Data_Ordering.__singleton$LT.value) : ( ((Boolean) ((y_5 instanceof Data_Either.Left))) ? Data_Ordering.__singleton$GT.value : ( ((Boolean) ((((Boolean) ((x_4 instanceof Data_Either.Right))) && ((Boolean) ((y_5 instanceof Data_Either.Right)))))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd1_2).get("compare"))).apply(((Data_Either.Right) (Object)(x_4)).value0))).apply(((Data_Either.Right) (Object)(y_5)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_4) -> { return eqEither2_3; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get(); }; };
public static final Object eq1Either = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictEq1_1) -> { return ((java.util.function.Function<Object, Object>) (Data_Eq.eq)).apply(( ((Boolean) ((Data_Either.eqEither == null))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Either.eqEither)).apply(dictEq_0))).apply(dictEq1_1) : Data_Either.__direct$15(dictEq_0, dictEq1_1))); }; return new __Record$65_71_31_O(new String[]{"eq1"}, __field0); } }).get(); };
public static final Object ord1Either = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { Object ordEither1_1 = ((java.util.function.Function<Object, Object>) (Data_Either.ordEither)).apply(dictOrd_0); Object eq1Either1_2 = ((java.util.function.Function<Object, Object>) (Data_Either.eq1Either)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("Eq0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictOrd1_3) -> { return ((java.util.function.Function<Object, Object>) (Data_Ord.compare)).apply(((java.util.function.Function<Object, Object>) (ordEither1_1)).apply(dictOrd1_3)); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> { return eq1Either1_2; }; return new __Record$45_71_31_30_O$63_6f_6d_70_61_72_65_31_O(new String[]{"compare1", "Eq10"}, __field1, __field0); } }).get(); };
public static final Object either = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return (java.util.function.Function<Object, Object>) (v2_2) -> { return ( ((Boolean) ((v2_2 instanceof Data_Either.Left))) ? ((java.util.function.Function<Object, Object>) (v_0)).apply(((Data_Either.Left) (Object)(v2_2)).value0) : ( ((Boolean) ((v2_2 instanceof Data_Either.Right))) ? ((java.util.function.Function<Object, Object>) (v1_1)).apply(((Data_Either.Right) (Object)(v2_2)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }; };
public static final Object hush = (java.util.function.Function<Object, Object>) (v2_0) -> { return ( ((Boolean) ((v2_0 instanceof Data_Either.Left))) ? Data_Maybe.__singleton$Nothing.value : ( ((Boolean) ((v2_0 instanceof Data_Either.Right))) ? new Data_Maybe.Just(((Data_Either.Right) (Object)(v2_0)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); };
public static final Object isLeft = (java.util.function.Function<Object, Object>) (v2_0) -> { return ( ((Boolean) ((v2_0 instanceof Data_Either.Left))) ? true : ( ((Boolean) ((v2_0 instanceof Data_Either.Right))) ? false : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); };
public static final Object isRight = (java.util.function.Function<Object, Object>) (v2_0) -> { return ( ((Boolean) ((v2_0 instanceof Data_Either.Left))) ? false : ( ((Boolean) ((v2_0 instanceof Data_Either.Right))) ? true : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); };
public static final Object choose = (java.util.function.Function<Object, Object>) (dictAlt_0) -> { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictAlt_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (a_2) -> { return (java.util.function.Function<Object, Object>) (b_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictAlt_0).get("alt"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1).get("map"))).apply(Data_Either.Left))).apply(a_2)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1).get("map"))).apply(Data_Either.Right))).apply(b_3)); }; }; };
public static final Object boundedEither = (java.util.function.Function<Object, Object>) (dictBounded_0) -> { Object ordEither1_1 = ((java.util.function.Function<Object, Object>) (Data_Either.ordEither)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBounded_0).get("Ord0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictBounded1_2) -> { Object ordEither2_3 = ((java.util.function.Function<Object, Object>) (ordEither1_1)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBounded1_2).get("Ord0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = new Data_Either.Right(((java.util.Map<String, Object>) dictBounded1_2).get("top")); final Object __field1 = new Data_Either.Left(((java.util.Map<String, Object>) dictBounded_0).get("bottom")); final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_4) -> { return ordEither2_3; }; return new __Record$4f_72_64_30_O$62_6f_74_74_6f_6d_O$74_6f_70_O(new String[]{"top", "bottom", "Ord0"}, __field2, __field1, __field0); } }).get(); }; };
public static final Object blush = (java.util.function.Function<Object, Object>) (v2_0) -> { return ( ((Boolean) ((v2_0 instanceof Data_Either.Left))) ? new Data_Maybe.Just(((Data_Either.Left) (Object)(v2_0)).value0) : ( ((Boolean) ((v2_0 instanceof Data_Either.Right))) ? Data_Maybe.__singleton$Nothing.value : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); };
public static final Object applyEither = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return ( ((Boolean) ((v_0 instanceof Data_Either.Left))) ? v_0 : ( ((Boolean) ((v_0 instanceof Data_Either.Right))) ? ( ((Boolean) ((v1_1 instanceof Data_Either.Left))) ? v1_1 : ( ((Boolean) ((v1_1 instanceof Data_Either.Right))) ? new Data_Either.Right(((java.util.function.Function<Object, Object>) (((Data_Either.Right) (Object)(v_0)).value0)).apply(((Data_Either.Right) (Object)(v1_1)).value0)) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Either.functorEither; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get();
public static final Object bindEither = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v2_0) -> { {  if ((Boolean) ((v2_0 instanceof Data_Either.Left))) { { Object __local_var_1 = ((Data_Either.Left) (Object)(v2_0)).value0; return (java.util.function.Function<Object, Object>) (v_2) -> { return new Data_Either.Left(__local_var_1); }; } } else { {  if ((Boolean) ((v2_0 instanceof Data_Either.Right))) { { Object __local_var_1 = ((Data_Either.Right) (Object)(v2_0)).value0; return (java.util.function.Function<Object, Object>) (f_2) -> { return ((java.util.function.Function<Object, Object>) (f_2)).apply(__local_var_1); }; } } else { return (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get(); } } } }  }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Either.applyEither; }; return new __Record$41_70_70_6c_79_30_O$62_69_6e_64_O(new String[]{"bind", "Apply0"}, __field1, __field0); } }).get();
public static final Object semigroupEither = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> { Object append_1 = ((java.util.function.Function<Object, Object>) (Data_Semigroup.append)).apply(dictSemigroup_0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_2) -> { return (java.util.function.Function<Object, Object>) (y_3) -> { return ( ((Boolean) ((x_2 instanceof Data_Either.Left))) ? x_2 : ( ((Boolean) ((x_2 instanceof Data_Either.Right))) ? ( ((Boolean) ((y_3 instanceof Data_Either.Left))) ? y_3 : ( ((Boolean) ((y_3 instanceof Data_Either.Right))) ? new Data_Either.Right(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (append_1)).apply(((Data_Either.Right) (Object)(x_2)).value0))).apply(((Data_Either.Right) (Object)(y_3)).value0)) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get(); };
public static final Object applicativeEither = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = Data_Either.Right; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Either.applyEither; }; return new __Record$41_70_70_6c_79_30_O$70_75_72_65_O(new String[]{"pure", "Apply0"}, __field1, __field0); } }).get();
public static final Object monadEither = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Either.applicativeEither; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Either.bindEither; }; return new __Record$41_70_70_6c_69_63_61_74_69_76_65_30_O$42_69_6e_64_31_O(new String[]{"Applicative0", "Bind1"}, __field0, __field1); } }).get();
public static final Object altEither = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return ( ((Boolean) ((v_0 instanceof Data_Either.Left))) ? v1_1 : v_0); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Either.functorEither; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_6c_74_O(new String[]{"alt", "Functor0"}, __field1, __field0); } }).get();
}
