public class Data_Bifunctor_Join {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Bifunctor.Join"); }
    };


public static final Object Join = (java.util.function.Function<Object, Object>) (x_0) -> { return x_0; };
public static final Object showJoin = (java.util.function.Function<Object, Object>) (dictShow_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (((String) ((((String) ("(Join ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); };
public static final Object ordJoin = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return dictOrd_0; };
public static final Object newtypeJoin = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object eqJoin = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return dictEq_0; };
public static final Object bifunctorJoin = (java.util.function.Function<Object, Object>) (dictBifunctor_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBifunctor_0).get("bimap"))).apply(f_1))).apply(f_1))).apply(v_2); }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get(); };
public static final Object biapplyJoin = (java.util.function.Function<Object, Object>) (dictBiapply_0) -> { Object bifunctorJoin1_1 = ((java.util.function.Function<Object, Object>) (Data_Bifunctor_Join.bifunctorJoin)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapply_0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapply_0).get("biapply"))).apply(v_2))).apply(v1_3); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return bifunctorJoin1_1; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get(); };
public static final Object biapplicativeJoin = (java.util.function.Function<Object, Object>) (dictBiapplicative_0) -> { Object biapplyJoin1_1 = ((java.util.function.Function<Object, Object>) (Data_Bifunctor_Join.biapplyJoin)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapplicative_0).get("Biapply0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (a_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapplicative_0).get("bipure"))).apply(a_2))).apply(a_2); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return biapplyJoin1_1; }; return new __Record$41_70_70_6c_79_30_O$70_75_72_65_O(new String[]{"pure", "Apply0"}, __field1, __field0); } }).get(); };
}
