public class Data_Traversable_Accum_Internal {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Traversable.Accum.Internal"); }
    };


public static final Object StateR = (java.util.function.Function<Object, Object>) (x_0) -> { return x_0; };
public static final Object StateL = (java.util.function.Function<Object, Object>) (x_0) -> { return x_0; };
public static final Object stateR = (java.util.function.Function<Object, Object>) (v_0) -> { return v_0; };
public static final Object stateL = (java.util.function.Function<Object, Object>) (v_0) -> { return v_0; };
public static final Object functorStateR = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (k_1) -> { return (java.util.function.Function<Object, Object>) (s_2) -> { Object v_3 = ((java.util.function.Function<Object, Object>) (k_1)).apply(s_2); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __Record$61_63_63_75_6d_O$76_61_6c_75_65_O.read0(v_3); final Object __field1 = ((java.util.function.Function<Object, Object>) (f_0)).apply(__Record$61_63_63_75_6d_O$76_61_6c_75_65_O.read1(v_3)); return new __Record$61_63_63_75_6d_O$76_61_6c_75_65_O(new String[]{"accum", "value"}, __field0, __field1); } }).get(); }; }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get();
public static final Object functorStateL = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (k_1) -> { return (java.util.function.Function<Object, Object>) (s_2) -> { Object v_3 = ((java.util.function.Function<Object, Object>) (k_1)).apply(s_2); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __Record$61_63_63_75_6d_O$76_61_6c_75_65_O.read0(v_3); final Object __field1 = ((java.util.function.Function<Object, Object>) (f_0)).apply(__Record$61_63_63_75_6d_O$76_61_6c_75_65_O.read1(v_3)); return new __Record$61_63_63_75_6d_O$76_61_6c_75_65_O(new String[]{"accum", "value"}, __field0, __field1); } }).get(); }; }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get();
public static final Object applyStateR = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (x_1) -> { return (java.util.function.Function<Object, Object>) (s_2) -> { Object v_3 = ((java.util.function.Function<Object, Object>) (x_1)).apply(s_2); Object v1_4 = ((java.util.function.Function<Object, Object>) (f_0)).apply(__Record$61_63_63_75_6d_O$76_61_6c_75_65_O.read0(v_3)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __Record$61_63_63_75_6d_O$76_61_6c_75_65_O.read0(v1_4); final Object __field1 = ((java.util.function.Function<Object, Object>) (__Record$61_63_63_75_6d_O$76_61_6c_75_65_O.read1(v1_4))).apply(__Record$61_63_63_75_6d_O$76_61_6c_75_65_O.read1(v_3)); return new __Record$61_63_63_75_6d_O$76_61_6c_75_65_O(new String[]{"accum", "value"}, __field0, __field1); } }).get(); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Traversable_Accum_Internal.functorStateR; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get();
public static final Object applyStateL = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (x_1) -> { return (java.util.function.Function<Object, Object>) (s_2) -> { Object v_3 = ((java.util.function.Function<Object, Object>) (f_0)).apply(s_2); Object v1_4 = ((java.util.function.Function<Object, Object>) (x_1)).apply(__Record$61_63_63_75_6d_O$76_61_6c_75_65_O.read0(v_3)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __Record$61_63_63_75_6d_O$76_61_6c_75_65_O.read0(v1_4); final Object __field1 = ((java.util.function.Function<Object, Object>) (__Record$61_63_63_75_6d_O$76_61_6c_75_65_O.read1(v_3))).apply(__Record$61_63_63_75_6d_O$76_61_6c_75_65_O.read1(v1_4)); return new __Record$61_63_63_75_6d_O$76_61_6c_75_65_O(new String[]{"accum", "value"}, __field0, __field1); } }).get(); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Traversable_Accum_Internal.functorStateL; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get();
public static final Object applicativeStateR = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (a_0) -> { return (java.util.function.Function<Object, Object>) (s_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = s_1; final Object __field1 = a_0; return new __Record$61_63_63_75_6d_O$76_61_6c_75_65_O(new String[]{"accum", "value"}, __field0, __field1); } }).get(); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Traversable_Accum_Internal.applyStateR; }; return new __Record$41_70_70_6c_79_30_O$70_75_72_65_O(new String[]{"pure", "Apply0"}, __field1, __field0); } }).get();
public static final Object applicativeStateL = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (a_0) -> { return (java.util.function.Function<Object, Object>) (s_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = s_1; final Object __field1 = a_0; return new __Record$61_63_63_75_6d_O$76_61_6c_75_65_O(new String[]{"accum", "value"}, __field0, __field1); } }).get(); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Traversable_Accum_Internal.applyStateL; }; return new __Record$41_70_70_6c_79_30_O$70_75_72_65_O(new String[]{"pure", "Apply0"}, __field1, __field0); } }).get();
}
