public class Data_Ord_Generic {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Ord.Generic"); }
    };


public static final Object genericOrdNoConstructors = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return Data_Ordering.__singleton$EQ.value; }; }; return new __Record$67_65_6e_65_72_69_63_43_6f_6d_70_61_72_65_27_O(new String[]{"genericCompare'"}, __field0); } }).get();
public static final Object genericOrdNoArguments = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return Data_Ordering.__singleton$EQ.value; }; }; return new __Record$67_65_6e_65_72_69_63_43_6f_6d_70_61_72_65_27_O(new String[]{"genericCompare'"}, __field0); } }).get();
public static final Object genericOrdArgument = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(v_1))).apply(v1_2); }; }; return new __Record$67_65_6e_65_72_69_63_43_6f_6d_70_61_72_65_27_O(new String[]{"genericCompare'"}, __field0); } }).get(); };
public static final Object genericCompareprime = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("genericCompare'"); };
public static final Object genericOrdConstructor = (java.util.function.Function<Object, Object>) (dictGenericOrd_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericOrd_0).get("genericCompare'"))).apply(v_1))).apply(v1_2); }; }; return new __Record$67_65_6e_65_72_69_63_43_6f_6d_70_61_72_65_27_O(new String[]{"genericCompare'"}, __field0); } }).get(); };
public static final Object genericOrdProduct = (java.util.function.Function<Object, Object>) (dictGenericOrd_0) -> { return (java.util.function.Function<Object, Object>) (dictGenericOrd1_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { Object v2_4 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericOrd_0).get("genericCompare'"))).apply(((Data_Generic_Rep.Product) (Object)(v_2)).value0))).apply(((Data_Generic_Rep.Product) (Object)(v1_3)).value0); return ( ((Boolean) ((v2_4 instanceof Data_Ordering.EQ))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericOrd1_1).get("genericCompare'"))).apply(((Data_Generic_Rep.Product) (Object)(v_2)).value1))).apply(((Data_Generic_Rep.Product) (Object)(v1_3)).value1) : v2_4); }; }; return new __Record$67_65_6e_65_72_69_63_43_6f_6d_70_61_72_65_27_O(new String[]{"genericCompare'"}, __field0); } }).get(); }; };
public static final Object genericOrdSum = (java.util.function.Function<Object, Object>) (dictGenericOrd_0) -> { return (java.util.function.Function<Object, Object>) (dictGenericOrd1_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { return ( ((Boolean) ((v_2 instanceof Data_Generic_Rep.Inl))) ? ( ((Boolean) ((v1_3 instanceof Data_Generic_Rep.Inl))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericOrd_0).get("genericCompare'"))).apply(((Data_Generic_Rep.Inl) (Object)(v_2)).value0))).apply(((Data_Generic_Rep.Inl) (Object)(v1_3)).value0) : ( ((Boolean) ((v1_3 instanceof Data_Generic_Rep.Inr))) ? Data_Ordering.__singleton$LT.value : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())) : ( ((Boolean) ((v_2 instanceof Data_Generic_Rep.Inr))) ? ( ((Boolean) ((v1_3 instanceof Data_Generic_Rep.Inr))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericOrd1_1).get("genericCompare'"))).apply(((Data_Generic_Rep.Inr) (Object)(v_2)).value0))).apply(((Data_Generic_Rep.Inr) (Object)(v1_3)).value0) : ( ((Boolean) ((v1_3 instanceof Data_Generic_Rep.Inl))) ? Data_Ordering.__singleton$GT.value : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }; return new __Record$67_65_6e_65_72_69_63_43_6f_6d_70_61_72_65_27_O(new String[]{"genericCompare'"}, __field0); } }).get(); }; };
public static final Object genericCompare = (java.util.function.Function<Object, Object>) (dictGeneric_0) -> { return (java.util.function.Function<Object, Object>) (dictGenericOrd_1) -> { return (java.util.function.Function<Object, Object>) (x_2) -> { return (java.util.function.Function<Object, Object>) (y_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericOrd_1).get("genericCompare'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0).get("from"))).apply(x_2)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0).get("from"))).apply(y_3)); }; }; }; };
}
