public class Data_Functor_App {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Functor.App"); }
    };


public static final Object App = (java.util.function.Function<Object, Object>) (x_0) -> { return x_0; };
public static final Object showApp = (java.util.function.Function<Object, Object>) (dictShow_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (((String) ((((String) ("(App ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); };
public static final Object semigroupApp = (java.util.function.Function<Object, Object>) (dictApply_0) -> { return (java.util.function.Function<Object, Object>) (dictSemigroup_1) -> { Object append_2 = ((java.util.function.Function<Object, Object>) (Data_Semigroup.append)).apply(dictSemigroup_1); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_3) -> { return (java.util.function.Function<Object, Object>) (v1_4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"))).apply(append_2))).apply(v_3)))).apply(v1_4); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get(); }; };
public static final Object plusApp = (java.util.function.Function<Object, Object>) (dictPlus_0) -> { return dictPlus_0; };
public static final Object newtypeApp = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object monoidApp = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> { Object semigroupApp1_1 = ((java.util.function.Function<Object, Object>) (Data_Functor_App.semigroupApp)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_0).get("Apply0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictMonoid_2) -> { Object semigroupApp2_3 = ((java.util.function.Function<Object, Object>) (semigroupApp1_1)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonoid_2).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_0).get("pure"))).apply(((java.util.Map<String, Object>) dictMonoid_2).get("mempty")); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_4) -> { return semigroupApp2_3; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get(); }; };
public static final Object monadPlusApp = (java.util.function.Function<Object, Object>) (dictMonadPlus_0) -> { return dictMonadPlus_0; };
public static final Object monadApp = (java.util.function.Function<Object, Object>) (dictMonad_0) -> { return dictMonad_0; };
public static final Object lazyApp = (java.util.function.Function<Object, Object>) (dictLazy_0) -> { return dictLazy_0; };
public static final Object hoistLowerApp = Unsafe_Coerce.unsafeCoerce;
public static final Object hoistLiftApp = Unsafe_Coerce.unsafeCoerce;
public static final Object hoistApp = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return ((java.util.function.Function<Object, Object>) (f_0)).apply(v_1); }; };
public static final Object functorApp = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> { return dictFunctor_0; };
public static final Object extendApp = (java.util.function.Function<Object, Object>) (dictExtend_0) -> { return dictExtend_0; };
public static final Object eqApp = (java.util.function.Function<Object, Object>) (dictEq1_0) -> { return (java.util.function.Function<Object, Object>) (dictEq_1) -> { return Data_Functor_App.__direct$14(dictEq1_0, dictEq_1); }; };
private static Object __direct$14(Object dictEq1_0, Object dictEq_1) { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_2) -> { return (java.util.function.Function<Object, Object>) (y_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEq1_0).get("eq1"))).apply(dictEq_1))).apply(x_2))).apply(y_3); }; }; return new __Record$65_71_O(new String[]{"eq"}, __field0); } }).get(); }
public static final Object ordApp = (java.util.function.Function<Object, Object>) (dictOrd1_0) -> { Object eqApp1_1 = ((java.util.function.Function<Object, Object>) (Data_Functor_App.eqApp)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd1_0).get("Eq10"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictOrd_2) -> { Object eqApp2_3 = ((java.util.function.Function<Object, Object>) (eqApp1_1)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_2).get("Eq0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_4) -> { return (java.util.function.Function<Object, Object>) (y_5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd1_0).get("compare1"))).apply(dictOrd_2))).apply(x_4))).apply(y_5); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_4) -> { return eqApp2_3; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get(); }; };
public static final Object eq1App = (java.util.function.Function<Object, Object>) (dictEq1_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictEq_1) -> { return ((java.util.function.Function<Object, Object>) (Data_Eq.eq)).apply(( ((Boolean) ((Data_Functor_App.eqApp == null))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Functor_App.eqApp)).apply(dictEq1_0))).apply(dictEq_1) : Data_Functor_App.__direct$14(dictEq1_0, dictEq_1))); }; return new __Record$65_71_31_O(new String[]{"eq1"}, __field0); } }).get(); };
public static final Object ord1App = (java.util.function.Function<Object, Object>) (dictOrd1_0) -> { Object ordApp1_1 = ((java.util.function.Function<Object, Object>) (Data_Functor_App.ordApp)).apply(dictOrd1_0); Object eq1App1_2 = ((java.util.function.Function<Object, Object>) (Data_Functor_App.eq1App)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd1_0).get("Eq10"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictOrd_3) -> { return ((java.util.function.Function<Object, Object>) (Data_Ord.compare)).apply(((java.util.function.Function<Object, Object>) (ordApp1_1)).apply(dictOrd_3)); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> { return eq1App1_2; }; return new __Record$45_71_31_30_O$63_6f_6d_70_61_72_65_31_O(new String[]{"compare1", "Eq10"}, __field1, __field0); } }).get(); };
public static final Object comonadApp = (java.util.function.Function<Object, Object>) (dictComonad_0) -> { return dictComonad_0; };
public static final Object bindApp = (java.util.function.Function<Object, Object>) (dictBind_0) -> { return dictBind_0; };
public static final Object applyApp = (java.util.function.Function<Object, Object>) (dictApply_0) -> { return dictApply_0; };
public static final Object applicativeApp = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> { return dictApplicative_0; };
public static final Object alternativeApp = (java.util.function.Function<Object, Object>) (dictAlternative_0) -> { return dictAlternative_0; };
public static final Object altApp = (java.util.function.Function<Object, Object>) (dictAlt_0) -> { return dictAlt_0; };
}
