public class Data_Bifunctor {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Bifunctor"); }
    };


public static final Object bimap = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("bimap"); };
public static final Object bivoid = (java.util.function.Function<Object, Object>) (dictBifunctor_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBifunctor_0).get("bimap"))).apply((java.util.function.Function<Object, Object>) (v_1) -> { return Data_Unit.unit; }))).apply((java.util.function.Function<Object, Object>) (v_1) -> { return Data_Unit.unit; }); };
public static final Object lmap = (java.util.function.Function<Object, Object>) (dictBifunctor_0) -> { return (java.util.function.Function<Object, Object>) (f_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBifunctor_0).get("bimap"))).apply(f_1))).apply(((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn)); }; };
public static final Object rmap = (java.util.function.Function<Object, Object>) (dictBifunctor_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBifunctor_0).get("bimap"))).apply(((java.util.function.Function<Object, Object>) (Control_Category.identity)).apply(Control_Category.categoryFn)); };
public static final Object bifunctorTuple = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (g_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return new Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (f_0)).apply(((Data_Tuple.Tuple) (Object)(v_2)).value0), ((java.util.function.Function<Object, Object>) (g_1)).apply(((Data_Tuple.Tuple) (Object)(v_2)).value1)); }; }; }; return new __Record$62_69_6d_61_70_O(new String[]{"bimap"}, __field0); } }).get();
public static final Object bifunctorEither = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return (java.util.function.Function<Object, Object>) (v2_2) -> { return ( ((Boolean) ((v2_2 instanceof Data_Either.Left))) ? new Data_Either.Left(((java.util.function.Function<Object, Object>) (v_0)).apply(((Data_Either.Left) (Object)(v2_2)).value0)) : ( ((Boolean) ((v2_2 instanceof Data_Either.Right))) ? new Data_Either.Right(((java.util.function.Function<Object, Object>) (v1_1)).apply(((Data_Either.Right) (Object)(v2_2)).value0)) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }; }; return new __Record$62_69_6d_61_70_O(new String[]{"bimap"}, __field0); } }).get();
public static final Object bifunctorConst = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (f_0)).apply(v1_2); }; }; }; return new __Record$62_69_6d_61_70_O(new String[]{"bimap"}, __field0); } }).get();
}
