public class Data_Array_ST_Iterator {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Array.ST.Iterator"); }
    };


public static final class Iterator {
            public final Object value0;
            public final Object value1;
            public Iterator(Object value0, Object value1) {
                this.value0 = value0;
                this.value1 = value1;
            }
        }
public static final Object Iterator = (java.util.function.Function<Object, Object>) (value0) -> (java.util.function.Function<Object, Object>) (value1) -> { return new Data_Array_ST_Iterator.Iterator(value0, value1); };
public static final Object peek = (java.util.function.Function<Object, Object>) (v_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((Data_Array_ST_Iterator.Iterator) (Object)(v_0)).value1; Object i_2 = null /* TODO: unknown syntax PrimEffect */; return ((java.util.function.Function<Object, Object>) (((Data_Array_ST_Iterator.Iterator) (Object)(v_0)).value0)).apply(i_2); } }); };
public static final Object next = (java.util.function.Function<Object, Object>) (v_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((Data_Array_ST_Iterator.Iterator) (Object)(v_0)).value1; Object i_2 = null /* TODO: unknown syntax PrimEffect */; Object _dollar___unused_3 = ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Monad_ST_Internal.modifyImpl)).apply((java.util.function.Function<Object, Object>) (s_3) -> { Object s_prime__4 = (((int) (s_3)) + ((int) (1))); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = s_prime__4; final Object __field1 = s_prime__4; return new __Record$73_74_61_74_65_O$76_61_6c_75_65_O(new String[]{"state", "value"}, __field0, __field1); } }).get(); }))).apply(__local_var_1))).get(); return ((java.util.function.Function<Object, Object>) (((Data_Array_ST_Iterator.Iterator) (Object)(v_0)).value0)).apply(i_2); } }); };
public static final Object pushWhile = (java.util.function.Function<Object, Object>) (p_0) -> { return (java.util.function.Function<Object, Object>) (iter_1) -> { return (java.util.function.Function<Object, Object>) (array_2) -> { return (new java.util.function.Supplier<Object>() { public Object get() { Object go__break_3 = null /* TODO: unknown syntax PrimEffect */; return ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Monad_ST_Internal.$while)).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_4 = ((java.util.function.Function<Object, Object>) (Data_HeytingAlgebra.not)).apply(Data_HeytingAlgebra.heytingAlgebraBoolean); Object __local_var_5 = null /* TODO: unknown syntax PrimEffect */; return ((java.util.function.Function<Object, Object>) (__local_var_4)).apply(__local_var_5); } })))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_4 = ((Data_Array_ST_Iterator.Iterator) (Object)(iter_1)).value1; Object mx_5 = (new java.util.function.Supplier<Object>() { public Object get() { Object i_5 = null /* TODO: unknown syntax PrimEffect */; return ((java.util.function.Function<Object, Object>) (((Data_Array_ST_Iterator.Iterator) (Object)(iter_1)).value0)).apply(i_5); } }).get(); return ((java.util.function.Supplier) (Object)(( ((Boolean) ((((Boolean) ((mx_5 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (p_0)).apply(((Data_Maybe.Just) (Object)(mx_5)).value0)))))) ? (new java.util.function.Supplier<Object>() { public Object get() { Object _dollar___unused_6 = ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Array_ST.push)).apply(((Data_Maybe.Just) (Object)(mx_5)).value0))).apply(array_2))).get(); return ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Functor.$void)).apply(Control_Monad_ST_Internal.functorST))).apply(((java.util.function.Function<Object, Object>) (Data_Array_ST_Iterator.next)).apply(iter_1)))).get(); } }) : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Functor.$void)).apply(Control_Monad_ST_Internal.functorST))).apply((new java.util.function.Supplier<Object>() { public Object get() { return null /* TODO: unknown syntax PrimEffect */; } }))))).get(); } })))).get(); } }); }; }; };
public static final Object pushAll = ((java.util.function.Function<Object, Object>) (Data_Array_ST_Iterator.pushWhile)).apply((java.util.function.Function<Object, Object>) (v_0) -> { return true; });
public static final Object iterator = (java.util.function.Function<Object, Object>) (f_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (Data_Array_ST_Iterator.Iterator)).apply(f_0); Object __local_var_2 = null /* TODO: unknown syntax PrimEffect */; return ((java.util.function.Function<Object, Object>) (__local_var_1)).apply(__local_var_2); } }); };
public static final Object iterate = (java.util.function.Function<Object, Object>) (iter_0) -> { return (java.util.function.Function<Object, Object>) (f_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { Object go__break_2 = null /* TODO: unknown syntax PrimEffect */; return ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Monad_ST_Internal.$while)).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_3 = ((java.util.function.Function<Object, Object>) (Data_HeytingAlgebra.not)).apply(Data_HeytingAlgebra.heytingAlgebraBoolean); Object __local_var_4 = null /* TODO: unknown syntax PrimEffect */; return ((java.util.function.Function<Object, Object>) (__local_var_3)).apply(__local_var_4); } })))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_3 = ((java.util.function.Function<Object, Object>) (Data_Array_ST_Iterator.next)).apply(iter_0); Object mx_4 = ((java.util.function.Supplier) (Object)(__local_var_3)).get(); return ((java.util.function.Supplier) (Object)(( ((Boolean) ((mx_4 instanceof Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (f_1)).apply(((Data_Maybe.Just) (Object)(mx_4)).value0) : ( ((Boolean) ((mx_4 instanceof Data_Maybe.Nothing))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Functor.$void)).apply(Control_Monad_ST_Internal.functorST))).apply((new java.util.function.Supplier<Object>() { public Object get() { return null /* TODO: unknown syntax PrimEffect */; } })) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())))).get(); } })))).get(); } }); }; };
public static final Object exhausted = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply((java.util.function.Function<Object, Object>) (__local_var_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((java.util.function.Supplier) (Object)(__local_var_0)).get(); return ((java.util.function.Function<Object, Object>) (Data_Maybe.isNothing)).apply(__local_var_1); } }); }))).apply(Data_Array_ST_Iterator.peek);
}
