public class Data_Functor_Joker {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Functor.Joker"); }
    };


public static final Object Joker = (java.util.function.Function<Object, Object>) (x_0) -> { return x_0; };
public static final Object showJoker = (java.util.function.Function<Object, Object>) (dictShow_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (((String) ((((String) ("(Joker ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); };
public static final Object profunctorJoker = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (g_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0).get("map"))).apply(g_2))).apply(v1_3); }; }; }; return new __Record$64_69_6d_61_70_O(new String[]{"dimap"}, __field0); } }).get(); };
public static final Object ordJoker = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return dictOrd_0; };
public static final Object newtypeJoker = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object hoistJoker = (java.util.function.Function<Object, Object>) (f_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return ((java.util.function.Function<Object, Object>) (f_0)).apply(v_1); }; };
public static final Object functorJoker = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0).get("map"))).apply(f_1))).apply(v_2); }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get(); };
public static final Object eqJoker = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return dictEq_0; };
public static final Object choiceJoker = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> { Object profunctorJoker1_1 = ((java.util.function.Function<Object, Object>) (Data_Functor_Joker.profunctorJoker)).apply(dictFunctor_0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0).get("map"))).apply(Data_Either.Left))).apply(v_2); }; final Object __field1 = (java.util.function.Function<Object, Object>) (v_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0).get("map"))).apply(Data_Either.Right))).apply(v_2); }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return profunctorJoker1_1; }; return new __Record$50_72_6f_66_75_6e_63_74_6f_72_30_O$6c_65_66_74_O$72_69_67_68_74_O(new String[]{"left", "right", "Profunctor0"}, __field2, __field0, __field1); } }).get(); };
public static final Object bifunctorJoker = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (g_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0).get("map"))).apply(g_2))).apply(v1_3); }; }; }; return new __Record$62_69_6d_61_70_O(new String[]{"bimap"}, __field0); } }).get(); };
public static final Object biapplyJoker = (java.util.function.Function<Object, Object>) (dictApply_0) -> { Object bifunctorJoker1_1 = ((java.util.function.Function<Object, Object>) (Data_Functor_Joker.bifunctorJoker)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("apply"))).apply(v_2))).apply(v1_3); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return bifunctorJoker1_1; }; return new __Record$42_69_66_75_6e_63_74_6f_72_30_O$62_69_61_70_70_6c_79_O(new String[]{"biapply", "Bifunctor0"}, __field1, __field0); } }).get(); };
public static final Object biapplicativeJoker = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> { Object biapplyJoker1_1 = ((java.util.function.Function<Object, Object>) (Data_Functor_Joker.biapplyJoker)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_0).get("Apply0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (b_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_0).get("pure"))).apply(b_3); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return biapplyJoker1_1; }; return new __Record$42_69_61_70_70_6c_79_30_O$62_69_70_75_72_65_O(new String[]{"bipure", "Biapply0"}, __field1, __field0); } }).get(); };
public static final Object applyJoker = (java.util.function.Function<Object, Object>) (dictApply_0) -> { Object functorJoker1_1 = ((java.util.function.Function<Object, Object>) (Data_Functor_Joker.functorJoker)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0).get("apply"))).apply(v_2))).apply(v1_3); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return functorJoker1_1; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get(); };
public static final Object bindJoker = (java.util.function.Function<Object, Object>) (dictBind_0) -> { Object applyJoker1_1 = ((java.util.function.Function<Object, Object>) (Data_Functor_Joker.applyJoker)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBind_0).get("Apply0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (amb_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBind_0).get("bind"))).apply(v_2))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.composeFlipped)).apply(Control_Semigroupoid.semigroupoidFn))).apply(amb_3))).apply(((java.util.function.Function<Object, Object>) (Data_Newtype.unwrap)).apply(null /* TODO: PrimUndefined */))); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return applyJoker1_1; }; return new __Record$41_70_70_6c_79_30_O$62_69_6e_64_O(new String[]{"bind", "Apply0"}, __field1, __field0); } }).get(); };
public static final Object applicativeJoker = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> { Object applyJoker1_1 = ((java.util.function.Function<Object, Object>) (Data_Functor_Joker.applyJoker)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_0).get("Apply0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(Data_Functor_Joker.Joker))).apply(((java.util.function.Function<Object, Object>) (Control_Applicative.pure)).apply(dictApplicative_0)); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return applyJoker1_1; }; return new __Record$41_70_70_6c_79_30_O$70_75_72_65_O(new String[]{"pure", "Apply0"}, __field1, __field0); } }).get(); };
public static final Object monadJoker = (java.util.function.Function<Object, Object>) (dictMonad_0) -> { Object applicativeJoker1_1 = ((java.util.function.Function<Object, Object>) (Data_Functor_Joker.applicativeJoker)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */)); Object bindJoker1_2 = ((java.util.function.Function<Object, Object>) (Data_Functor_Joker.bindJoker)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonad_0).get("Bind1"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> { return applicativeJoker1_1; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> { return bindJoker1_2; }; return new __Record$41_70_70_6c_69_63_61_74_69_76_65_30_O$42_69_6e_64_31_O(new String[]{"Applicative0", "Bind1"}, __field0, __field1); } }).get(); };
}
