public class Data_Ord {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Ord"); }
    };
    // FFI provided by ../javapurs-prelude/src/Data/Ord.java
    public static Object unsafeCompareImpl = (java.util.function.Function<Object, Object>) (lt) -> (java.util.function.Function<Object, Object>) (eq) -> (java.util.function.Function<Object, Object>) (gt) -> (java.util.function.Function<Object, Object>) (x) -> (java.util.function.Function<Object, Object>) (y) -> {
        int cmp;
        if (x instanceof String && y instanceof String) {
            cmp = ((String) x).compareTo((String) y);
        } else if (x instanceof Integer && y instanceof Integer) {
            cmp = ((Integer) x).compareTo((Integer) y);
        } else if (x instanceof Double && y instanceof Double) {
            cmp = ((Double) x).compareTo((Double) y);
        } else if (x instanceof Boolean && y instanceof Boolean) {
            cmp = ((Boolean) x).compareTo((Boolean) y);
        } else {
            throw new RuntimeException("unsafeCompareImpl: Unsupported types " + x.getClass() + " and " + y.getClass());
        }
        if (cmp < 0) return lt;
        if (cmp > 0) return gt;
        return eq;
    };

    public static Object ordBooleanImpl = unsafeCompareImpl;
    public static Object ordIntImpl = unsafeCompareImpl;
    public static Object ordNumberImpl = unsafeCompareImpl;
    public static Object ordStringImpl = unsafeCompareImpl;
    public static Object ordCharImpl = unsafeCompareImpl;

    public static Object ordArrayImpl = (java.util.function.Function<Object, Object>) (f) -> (java.util.function.Function<Object, Object>) (xs) -> (java.util.function.Function<Object, Object>) (ys) -> {
        Object[] arr1 = (Object[]) xs;
        Object[] arr2 = (Object[]) ys;
        int xlen = arr1.length;
        int ylen = arr2.length;
        int i = 0;
        while (i < xlen && i < ylen) {
            Object x = arr1[i];
            Object y = arr2[i];
            int o = (Integer) ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) f).apply(x)).apply(y);
            if (o != 0) {
                return o;
            }
            i++;
        }
        if (xlen == ylen) {
            return 0;
        } else if (xlen > ylen) {
            return -1;
        } else {
            return 1;
        }
    };


public static final Object ordVoid = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return Data_Ordering.__singleton$EQ.value; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Eq.eqVoid; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get();
public static final Object ordUnit = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return Data_Ordering.__singleton$EQ.value; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Eq.eqUnit; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get();
public static final Object ordString = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordStringImpl)).apply(Data_Ordering.__singleton$LT.value))).apply(Data_Ordering.__singleton$EQ.value))).apply(Data_Ordering.__singleton$GT.value); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Eq.eqString; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get();
public static final Object ordRecordNil = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return (java.util.function.Function<Object, Object>) (v2_2) -> { return Data_Ordering.__singleton$EQ.value; }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Eq.eqRowNil; }; return new __Record$45_71_52_65_63_6f_72_64_30_O$63_6f_6d_70_61_72_65_52_65_63_6f_72_64_O(new String[]{"compareRecord", "EqRecord0"}, __field1, __field0); } }).get();
public static final Object ordProxy = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return Data_Ordering.__singleton$EQ.value; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Eq.eqProxy; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get();
public static final Object ordOrdering = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0) -> { return (java.util.function.Function<Object, Object>) (v1_1) -> { return ( ((Boolean) ((v_0 instanceof Data_Ordering.LT))) ? ( ((Boolean) ((v1_1 instanceof Data_Ordering.LT))) ? Data_Ordering.__singleton$EQ.value : Data_Ordering.__singleton$LT.value) : ( ((Boolean) ((v_0 instanceof Data_Ordering.EQ))) ? ( ((Boolean) ((v1_1 instanceof Data_Ordering.EQ))) ? Data_Ordering.__singleton$EQ.value : ( ((Boolean) ((v1_1 instanceof Data_Ordering.LT))) ? Data_Ordering.__singleton$GT.value : ( ((Boolean) ((v1_1 instanceof Data_Ordering.GT))) ? Data_Ordering.__singleton$LT.value : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))) : ( ((Boolean) ((v_0 instanceof Data_Ordering.GT))) ? ( ((Boolean) ((v1_1 instanceof Data_Ordering.GT))) ? Data_Ordering.__singleton$EQ.value : Data_Ordering.__singleton$GT.value) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Ordering.eqOrdering; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get();
public static final Object ordNumber = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordNumberImpl)).apply(Data_Ordering.__singleton$LT.value))).apply(Data_Ordering.__singleton$EQ.value))).apply(Data_Ordering.__singleton$GT.value); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Eq.eqNumber; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get();
public static final Object ordInt = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordIntImpl)).apply(Data_Ordering.__singleton$LT.value))).apply(Data_Ordering.__singleton$EQ.value))).apply(Data_Ordering.__singleton$GT.value); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Eq.eqInt; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get();
public static final Object ordChar = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordCharImpl)).apply(Data_Ordering.__singleton$LT.value))).apply(Data_Ordering.__singleton$EQ.value))).apply(Data_Ordering.__singleton$GT.value); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Eq.eqChar; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get();
public static final Object ordBoolean = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordBooleanImpl)).apply(Data_Ordering.__singleton$LT.value))).apply(Data_Ordering.__singleton$EQ.value))).apply(Data_Ordering.__singleton$GT.value); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Eq.eqBoolean; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get();
public static final Object compareRecord = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("compareRecord"); };
public static final Object ordRecord = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return (java.util.function.Function<Object, Object>) (dictOrdRecord_1) -> { Object eqRec1_2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Eq.eqRec)).apply(null /* TODO: PrimUndefined */))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrdRecord_1).get("EqRecord0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrdRecord_1).get("compareRecord"))).apply(Type_Proxy.__singleton$Proxy.value); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> { return eqRec1_2; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get(); }; };
public static final Object compare1 = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("compare1"); };
public static final Object compare = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("compare"); };
public static final Object comparing = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return (java.util.function.Function<Object, Object>) (f_1) -> { return (java.util.function.Function<Object, Object>) (x_2) -> { return (java.util.function.Function<Object, Object>) (y_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(((java.util.function.Function<Object, Object>) (f_1)).apply(x_2)))).apply(((java.util.function.Function<Object, Object>) (f_1)).apply(y_3)); }; }; }; };
public static final Object greaterThan = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return (java.util.function.Function<Object, Object>) (a1_1) -> { return (java.util.function.Function<Object, Object>) (a2_2) -> { return (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(a1_1))).apply(a2_2) instanceof Data_Ordering.GT); }; }; };
public static final Object greaterThanOrEq = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return (java.util.function.Function<Object, Object>) (a1_1) -> { return (java.util.function.Function<Object, Object>) (a2_2) -> { return (!(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(a1_1))).apply(a2_2) instanceof Data_Ordering.LT))))); }; }; };
public static final Object lessThan = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return (java.util.function.Function<Object, Object>) (a1_1) -> { return (java.util.function.Function<Object, Object>) (a2_2) -> { return (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(a1_1))).apply(a2_2) instanceof Data_Ordering.LT); }; }; };
public static final Object signum = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return (java.util.function.Function<Object, Object>) (dictRing_1) -> { Object Semiring0_2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); Object zero_3 = ((java.util.function.Function<Object, Object>) (Data_Semiring.zero)).apply(Semiring0_2); Object Semiring01_4 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); Object one_5 = ((java.util.function.Function<Object, Object>) (Data_Semiring.one)).apply(Semiring0_2); return (java.util.function.Function<Object, Object>) (x_6) -> { return ( ((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(x_6))).apply(zero_3) instanceof Data_Ordering.LT))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_1).get("sub"))).apply(((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)).get("zero")))).apply(((java.util.Map<String, Object>) Semiring01_4).get("one")) : ( ((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(x_6))).apply(zero_3) instanceof Data_Ordering.GT))) ? one_5 : x_6)); }; }; };
public static final Object lessThanOrEq = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return (java.util.function.Function<Object, Object>) (a1_1) -> { return (java.util.function.Function<Object, Object>) (a2_2) -> { return (!(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(a1_1))).apply(a2_2) instanceof Data_Ordering.GT))))); }; }; };
public static final Object max = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return (java.util.function.Function<Object, Object>) (x_1) -> { return (java.util.function.Function<Object, Object>) (y_2) -> { Object v_3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(x_1))).apply(y_2); return ( ((Boolean) ((v_3 instanceof Data_Ordering.LT))) ? y_2 : ( ((Boolean) ((v_3 instanceof Data_Ordering.EQ))) ? x_1 : ( ((Boolean) ((v_3 instanceof Data_Ordering.GT))) ? x_1 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }; };
public static final Object min = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return (java.util.function.Function<Object, Object>) (x_1) -> { return (java.util.function.Function<Object, Object>) (y_2) -> { Object v_3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(x_1))).apply(y_2); return ( ((Boolean) ((v_3 instanceof Data_Ordering.LT))) ? x_1 : ( ((Boolean) ((v_3 instanceof Data_Ordering.EQ))) ? x_1 : ( ((Boolean) ((v_3 instanceof Data_Ordering.GT))) ? y_2 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }; };
public static final Object ordArray = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { Object eqArray_1 = ((java.util.function.Function<Object, Object>) (Data_Eq.eqArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("Eq0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (xs_2) -> { return (java.util.function.Function<Object, Object>) (ys_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordIntImpl)).apply(Data_Ordering.__singleton$LT.value))).apply(Data_Ordering.__singleton$EQ.value))).apply(Data_Ordering.__singleton$GT.value))).apply(0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordArrayImpl)).apply((java.util.function.Function<Object, Object>) (x_4) -> { return (java.util.function.Function<Object, Object>) (y_5) -> { Object v_6 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(x_4))).apply(y_5); return ( ((Boolean) ((v_6 instanceof Data_Ordering.EQ))) ? 0 : ( ((Boolean) ((v_6 instanceof Data_Ordering.LT))) ? 1 : ( ((Boolean) ((v_6 instanceof Data_Ordering.GT))) ? -1 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }))).apply(xs_2))).apply(ys_3)); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return eqArray_1; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get(); };
public static final Object ord1Array = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return ((java.util.function.Function<Object, Object>) (Data_Ord.compare)).apply(((java.util.function.Function<Object, Object>) (Data_Ord.ordArray)).apply(dictOrd_0)); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> { return Data_Eq.eq1Array; }; return new __Record$45_71_31_30_O$63_6f_6d_70_61_72_65_31_O(new String[]{"compare1", "Eq10"}, __field1, __field0); } }).get();
public static final Object ordRecordCons = (java.util.function.Function<Object, Object>) (dictOrdRecord_0) -> { Object eqRowCons_1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Eq.eqRowCons)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrdRecord_0).get("EqRecord0"))).apply(null /* TODO: PrimUndefined */)))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> { return (java.util.function.Function<Object, Object>) (dictIsSymbol_3) -> { Object eqRowCons1_4 = ((java.util.function.Function<Object, Object>) (eqRowCons_1)).apply(dictIsSymbol_3); return (java.util.function.Function<Object, Object>) (dictOrd_5) -> { Object eqRowCons2_6 = ((java.util.function.Function<Object, Object>) (eqRowCons1_4)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_5).get("Eq0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_7) -> { return (java.util.function.Function<Object, Object>) (ra_8) -> { return (java.util.function.Function<Object, Object>) (rb_9) -> { Object key_10 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictIsSymbol_3).get("reflectSymbol"))).apply(Type_Proxy.__singleton$Proxy.value); Object left_11 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_5).get("compare"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeGet)).apply(key_10))).apply(ra_8)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeGet)).apply(key_10))).apply(rb_9)); return ( ((Boolean) ((!(((Boolean) ((left_11 instanceof Data_Ordering.EQ))))))) ? left_11 : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrdRecord_0).get("compareRecord"))).apply(Type_Proxy.__singleton$Proxy.value))).apply(ra_8))).apply(rb_9)); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_7) -> { return eqRowCons2_6; }; return new __Record$45_71_52_65_63_6f_72_64_30_O$63_6f_6d_70_61_72_65_52_65_63_6f_72_64_O(new String[]{"compareRecord", "EqRecord0"}, __field1, __field0); } }).get(); }; }; }; };
public static final Object clamp = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return (java.util.function.Function<Object, Object>) (low_1) -> { return (java.util.function.Function<Object, Object>) (hi_2) -> { return (java.util.function.Function<Object, Object>) (x_3) -> { Object __local_var_4 = (new java.util.function.Supplier<Object>() { public Object get() { Object v_4 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(low_1))).apply(x_3); return ( ((Boolean) ((v_4 instanceof Data_Ordering.LT))) ? x_3 : ( ((Boolean) ((v_4 instanceof Data_Ordering.EQ))) ? low_1 : ( ((Boolean) ((v_4 instanceof Data_Ordering.GT))) ? low_1 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); } }).get(); Object v_5 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(hi_2))).apply(__local_var_4); return ( ((Boolean) ((v_5 instanceof Data_Ordering.LT))) ? hi_2 : ( ((Boolean) ((v_5 instanceof Data_Ordering.EQ))) ? hi_2 : ( ((Boolean) ((v_5 instanceof Data_Ordering.GT))) ? __local_var_4 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }; }; };
public static final Object between = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return (java.util.function.Function<Object, Object>) (low_1) -> { return (java.util.function.Function<Object, Object>) (hi_2) -> { return (java.util.function.Function<Object, Object>) (x_3) -> { return ( ((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(x_3))).apply(low_1) instanceof Data_Ordering.LT))) ? false : (!(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(x_3))).apply(hi_2) instanceof Data_Ordering.GT)))))); }; }; }; };
public static final Object abs = (java.util.function.Function<Object, Object>) (dictOrd_0) -> { return (java.util.function.Function<Object, Object>) (dictRing_1) -> { Object zero_2 = ((java.util.function.Function<Object, Object>) (Data_Semiring.zero)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (x_3) -> { return ( ((Boolean) ((!(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0).get("compare"))).apply(x_3))).apply(zero_2) instanceof Data_Ordering.LT))))))) ? x_3 : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_1).get("sub"))).apply(((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)).get("zero")))).apply(x_3)); }; }; };
}
