public class Data_Semigroup_Generic {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Semigroup.Generic"); }
    };


public static final Object genericSemigroupNoConstructors = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (a_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return a_0; }; }; return new __Record$67_65_6e_65_72_69_63_41_70_70_65_6e_64_27_O(new String[]{"genericAppend'"}, __field0); } }).get();
public static final Object genericSemigroupNoArguments = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (a_0) -> { return (java.util.function.Function<Object, Object>) (v_1) -> { return a_0; }; }; return new __Record$67_65_6e_65_72_69_63_41_70_70_65_6e_64_27_O(new String[]{"genericAppend'"}, __field0); } }).get();
public static final Object genericSemigroupArgument = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictSemigroup_0).get("append"))).apply(v_1))).apply(v1_2); }; }; return new __Record$67_65_6e_65_72_69_63_41_70_70_65_6e_64_27_O(new String[]{"genericAppend'"}, __field0); } }).get(); };
public static final Object genericAppendprime = (java.util.function.Function<Object, Object>) (dict_0) -> { return ((java.util.Map<String, Object>) dict_0).get("genericAppend'"); };
public static final Object genericSemigroupConstructor = (java.util.function.Function<Object, Object>) (dictGenericSemigroup_0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1) -> { return (java.util.function.Function<Object, Object>) (v1_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemigroup_0).get("genericAppend'"))).apply(v_1))).apply(v1_2); }; }; return new __Record$67_65_6e_65_72_69_63_41_70_70_65_6e_64_27_O(new String[]{"genericAppend'"}, __field0); } }).get(); };
public static final Object genericSemigroupProduct = (java.util.function.Function<Object, Object>) (dictGenericSemigroup_0) -> { return (java.util.function.Function<Object, Object>) (dictGenericSemigroup1_1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2) -> { return (java.util.function.Function<Object, Object>) (v1_3) -> { return new Data_Generic_Rep.Product(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemigroup_0).get("genericAppend'"))).apply(((Data_Generic_Rep.Product) (Object)(v_2)).value0))).apply(((Data_Generic_Rep.Product) (Object)(v1_3)).value0), ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemigroup1_1).get("genericAppend'"))).apply(((Data_Generic_Rep.Product) (Object)(v_2)).value1))).apply(((Data_Generic_Rep.Product) (Object)(v1_3)).value1)); }; }; return new __Record$67_65_6e_65_72_69_63_41_70_70_65_6e_64_27_O(new String[]{"genericAppend'"}, __field0); } }).get(); }; };
public static final Object genericAppend = (java.util.function.Function<Object, Object>) (dictGeneric_0) -> { return (java.util.function.Function<Object, Object>) (dictGenericSemigroup_1) -> { return (java.util.function.Function<Object, Object>) (x_2) -> { return (java.util.function.Function<Object, Object>) (y_3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0).get("to"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemigroup_1).get("genericAppend'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0).get("from"))).apply(x_2)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0).get("from"))).apply(y_3))); }; }; }; };
}
