public class Effect_Class_Console {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Effect.Class.Console"); }
    };


public static final Object warnShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> { Object liftEffect_1 = ((java.util.function.Function<Object, Object>) (Effect_Class.liftEffect)).apply(dictMonadEffect_0); return (java.util.function.Function<Object, Object>) (dictShow_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(liftEffect_1))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.warnShow)).apply(dictShow_2)); }; };
public static final Object warn = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (Effect_Class.liftEffect)).apply(dictMonadEffect_0)))).apply(Effect_Console.warn); };
public static final Object timeLog = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (Effect_Class.liftEffect)).apply(dictMonadEffect_0)))).apply(Effect_Console.timeLog); };
public static final Object timeEnd = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (Effect_Class.liftEffect)).apply(dictMonadEffect_0)))).apply(Effect_Console.timeEnd); };
public static final Object time = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (Effect_Class.liftEffect)).apply(dictMonadEffect_0)))).apply(Effect_Console.time); };
public static final Object logShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> { Object liftEffect_1 = ((java.util.function.Function<Object, Object>) (Effect_Class.liftEffect)).apply(dictMonadEffect_0); return (java.util.function.Function<Object, Object>) (dictShow_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(liftEffect_1))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.logShow)).apply(dictShow_2)); }; };
public static final Object log = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (Effect_Class.liftEffect)).apply(dictMonadEffect_0)))).apply((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; }); };
public static final Object infoShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> { Object liftEffect_1 = ((java.util.function.Function<Object, Object>) (Effect_Class.liftEffect)).apply(dictMonadEffect_0); return (java.util.function.Function<Object, Object>) (dictShow_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(liftEffect_1))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.infoShow)).apply(dictShow_2)); }; };
public static final Object info = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (Effect_Class.liftEffect)).apply(dictMonadEffect_0)))).apply(Effect_Console.info); };
public static final Object groupEnd = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(Effect_Console.groupEnd); };
public static final Object groupCollapsed = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (Effect_Class.liftEffect)).apply(dictMonadEffect_0)))).apply(Effect_Console.groupCollapsed); };
public static final Object group = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (Effect_Class.liftEffect)).apply(dictMonadEffect_0)))).apply(Effect_Console.group); };
public static final Object grouped = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> { Object Monad0_1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadEffect_0).get("Monad0"))).apply(null /* TODO: PrimUndefined */); Object Bind1_2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Monad0_1).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object groupEnd1_3 = ((java.util.function.Function<Object, Object>) (Effect_Class_Console.groupEnd)).apply(dictMonadEffect_0); Object Applicative0_4 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Monad0_1).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (name_5) -> { return (java.util.function.Function<Object, Object>) (inner_6) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Bind.bind)).apply(Bind1_2))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (Effect_Class.liftEffect)).apply(dictMonadEffect_0)))).apply(Effect_Console.group))).apply(name_5)))).apply((java.util.function.Function<Object, Object>) (_dollar___unused_7) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bind1_2).get("bind"))).apply(inner_6))).apply((java.util.function.Function<Object, Object>) (result_8) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Bind.bind)).apply(Bind1_2))).apply(groupEnd1_3))).apply((java.util.function.Function<Object, Object>) (_dollar___unused_9) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Applicative0_4).get("pure"))).apply(result_8); }); }); }); }; }; };
public static final Object errorShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> { Object liftEffect_1 = ((java.util.function.Function<Object, Object>) (Effect_Class.liftEffect)).apply(dictMonadEffect_0); return (java.util.function.Function<Object, Object>) (dictShow_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(liftEffect_1))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.errorShow)).apply(dictShow_2)); }; };
public static final Object error = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (Effect_Class.liftEffect)).apply(dictMonadEffect_0)))).apply(Effect_Console.error); };
public static final Object debugShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> { Object liftEffect_1 = ((java.util.function.Function<Object, Object>) (Effect_Class.liftEffect)).apply(dictMonadEffect_0); return (java.util.function.Function<Object, Object>) (dictShow_2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(liftEffect_1))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.debugShow)).apply(dictShow_2)); }; };
public static final Object debug = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Semigroupoid.compose)).apply(Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (Effect_Class.liftEffect)).apply(dictMonadEffect_0)))).apply(Effect_Console.debug); };
public static final Object clear = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(Effect_Console.clear); };
}
