public class Test_Assert {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Test.Assert"); }
    };
    // FFI provided by ../javapurs-assert/src/Test/Assert.java
    public static Object assertImpl = (java.util.function.Function<Object, Object>) (message) ->
        (java.util.function.Function<Object, Object>) (success) ->
        (java.util.function.Supplier<Object>) () -> {
            if (!((Boolean) success)) throw new RuntimeException((String) message);
            return null;
        };

    public static Object checkThrows = (java.util.function.Function<Object, Object>) (fn) ->
        (java.util.function.Supplier<Object>) () -> {
            try {
                ((java.util.function.Supplier<Object>) fn).get();
                return false;
            } catch (Throwable thrown) {
                if (thrown instanceof RuntimeException) return true;
                RuntimeException error = new RuntimeException("Threw something other than an Error");
                error.initCause(thrown);
                throw error;
            }
        };


public static final Object assertprime = (java.util.function.Function<Object, Object>) (msg) -> (java.util.function.Function<Object, Object>) (b) -> (java.util.function.Supplier<Object>) () -> { if (!((Boolean) b)) { throw new RuntimeException((String) msg); } return null; };
public static final Object assertEqualprime = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return (java.util.function.Function<Object, Object>) (dictShow_1) -> { return (java.util.function.Function<Object, Object>) (userMessage_2) -> { return (java.util.function.Function<Object, Object>) (v_3) -> { return Test_Assert.__direct$1(dictEq_0, dictShow_1, userMessage_2, v_3); }; }; }; };
private static Object __direct$1(Object dictEq_0, Object dictShow_1, Object userMessage_2, Object v_3) { Object result_4 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEq_0).get("eq"))).apply(__Record$61_63_74_75_61_6c_O$65_78_70_65_63_74_65_64_O.read0(v_3)))).apply(__Record$61_63_74_75_61_6c_O$65_78_70_65_63_74_65_64_O.read1(v_3)); Object message_5 = (((String) ((((String) ((((String) (( ((Boolean) (java.util.Objects.equals(userMessage_2, ""))) ? (((String) ("")) + ((String) ("Expected: "))) : (((String) (userMessage_2)) + ((String) ("\nExpected: ")))))) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_1).get("show"))).apply(__Record$61_63_74_75_61_6c_O$65_78_70_65_63_74_65_64_O.read1(v_3))))))) + ((String) ("\nActual:   "))))) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_1).get("show"))).apply(__Record$61_63_74_75_61_6c_O$65_78_70_65_63_74_65_64_O.read0(v_3))))); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Bind.bind)).apply(Effect.bindEffect))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_6 = ((java.util.function.Function<Object, Object>) (Effect_Console.error)).apply(message_5); return ( ((Boolean) ((!(((Boolean) (result_4)))))) ? __local_var_6 : ( ((Boolean) (result_4)) ? (new java.util.function.Supplier<Object>() { public Object get() { return Data_Unit.unit; } }) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); } }).get()))).apply((java.util.function.Function<Object, Object>) (_dollar___unused_6) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (msg) -> (java.util.function.Function<Object, Object>) (b) -> (java.util.function.Supplier<Object>) () -> { if (!((Boolean) b)) { throw new RuntimeException((String) msg); } return null; })).apply(message_5))).apply(result_4); }); }
public static final Object assertEqual = (java.util.function.Function<Object, Object>) (dictEq_0) -> { return (java.util.function.Function<Object, Object>) (dictShow_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_Assert.assertEqualprime)).apply(dictEq_0))).apply(dictShow_1))).apply(""); }; };
public static final Object assertFalse = (java.util.function.Function<Object, Object>) (actual_0) -> { return ( ((Boolean) ((Test_Assert.assertEqualprime == null))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_Assert.assertEqualprime)).apply(Data_Eq.eqBoolean))).apply(Data_Show.showBoolean))).apply(""))).apply((new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("actual", actual_0); __map.put("expected", false);  return __map; } }).get()) : Test_Assert.__direct$1(Data_Eq.eqBoolean, Data_Show.showBoolean, "", (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("actual", actual_0); __map.put("expected", false);  return __map; } }).get())); };
public static final Object assertTrue = (java.util.function.Function<Object, Object>) (actual_0) -> { return ( ((Boolean) ((Test_Assert.assertEqualprime == null))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_Assert.assertEqualprime)).apply(Data_Eq.eqBoolean))).apply(Data_Show.showBoolean))).apply(""))).apply((new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("actual", actual_0); __map.put("expected", true);  return __map; } }).get()) : Test_Assert.__direct$1(Data_Eq.eqBoolean, Data_Show.showBoolean, "", (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("actual", actual_0); __map.put("expected", true);  return __map; } }).get())); };
public static final Object assertFalseprime = (java.util.function.Function<Object, Object>) (message_0) -> { return (java.util.function.Function<Object, Object>) (actual_1) -> { return ( ((Boolean) ((Test_Assert.assertEqualprime == null))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_Assert.assertEqualprime)).apply(Data_Eq.eqBoolean))).apply(Data_Show.showBoolean))).apply(message_0))).apply((new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = actual_1; final Object __field1 = false; return new __Record$61_63_74_75_61_6c_O$65_78_70_65_63_74_65_64_O(new String[]{"actual", "expected"}, __field0, __field1); } }).get()) : Test_Assert.__direct$1(Data_Eq.eqBoolean, Data_Show.showBoolean, message_0, (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = actual_1; final Object __field1 = false; return new __Record$61_63_74_75_61_6c_O$65_78_70_65_63_74_65_64_O(new String[]{"actual", "expected"}, __field0, __field1); } }).get())); }; };
public static final Object assertTrueprime = (java.util.function.Function<Object, Object>) (message_0) -> { return (java.util.function.Function<Object, Object>) (actual_1) -> { return ( ((Boolean) ((Test_Assert.assertEqualprime == null))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_Assert.assertEqualprime)).apply(Data_Eq.eqBoolean))).apply(Data_Show.showBoolean))).apply(message_0))).apply((new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = actual_1; final Object __field1 = true; return new __Record$61_63_74_75_61_6c_O$65_78_70_65_63_74_65_64_O(new String[]{"actual", "expected"}, __field0, __field1); } }).get()) : Test_Assert.__direct$1(Data_Eq.eqBoolean, Data_Show.showBoolean, message_0, (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = actual_1; final Object __field1 = true; return new __Record$61_63_74_75_61_6c_O$65_78_70_65_63_74_65_64_O(new String[]{"actual", "expected"}, __field0, __field1); } }).get())); }; };
public static final Object assertThrowsprime = (java.util.function.Function<Object, Object>) (msg_0) -> { return (java.util.function.Function<Object, Object>) (fn_1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Bind.bind)).apply(Effect.bindEffect))).apply(((java.util.function.Function<Object, Object>) (Test_Assert.checkThrows)).apply(fn_1)))).apply(((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (msg) -> (java.util.function.Function<Object, Object>) (b) -> (java.util.function.Supplier<Object>) () -> { if (!((Boolean) b)) { throw new RuntimeException((String) msg); } return null; })).apply(msg_0)); }; };
public static final Object assertThrows = ((java.util.function.Function<Object, Object>) (Test_Assert.assertThrowsprime)).apply("Assertion failed: An error should have been thrown");
public static final Object $assert = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (msg) -> (java.util.function.Function<Object, Object>) (b) -> (java.util.function.Supplier<Object>) () -> { if (!((Boolean) b)) { throw new RuntimeException((String) msg); } return null; })).apply("Assertion failed");
}
